"""
Resonance — FastAPI Backend Server
Generated by Meta App Factory V3
"""

import os, sys, json, logging, shutil
from typing import Optional, List
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel
from dotenv import load_dotenv
from datetime import datetime

# For PDF
try:
    import PyPDF2
except ImportError:
    PyPDF2 = None
    logging.warning("PyPDF2 not installed. PDF file extraction will not work.")

# For DOCX
try:
    from docx import Document
except ImportError:
    Document = None
    logging.warning("python-docx not installed. DOCX file extraction will not work.")


# Load .env variables
load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s [Resonance] %(message)s")
logger = logging.getLogger("Resonance")

app = FastAPI(title="Resonance API", version="3.0")

# Widen CORS origins for Vite port jumping (5173-5180)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[f"http://localhost:{p}" for p in range(5173, 5181)],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── File Upload Configuration ───────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOADS_DIR = os.path.join(SCRIPT_DIR, "uploads")
FILE_CONTEXT_PATH = os.path.join(UPLOADS_DIR, "file_context.json")

# Ensure uploads directory exists
os.makedirs(UPLOADS_DIR, exist_ok=True)

def _load_file_context():
    """Loads the file context from file_context.json."""
    if os.path.exists(FILE_CONTEXT_PATH):
        try:
            with open(FILE_CONTEXT_PATH, "r", encoding="utf-8") as f:
                return json.load(f)
        except json.JSONDecodeError:
            logger.error(f"Error decoding {FILE_CONTEXT_PATH}. Starting with empty context.")
            return {"files": []}
    return {"files": []}

def _save_file_context(context):
    """Saves the file context to file_context.json."""
    with open(FILE_CONTEXT_PATH, "w", encoding="utf-8") as f:
        json.dump(context, f, indent=2)

async def _extract_text_from_file(file_path: str, file_type: str) -> str:
    """Extracts text content from various file types."""
    extracted_text = ""
    try:
        if file_type in ["txt", "md", "csv"]:
            with open(file_path, "r", encoding="utf-8") as f:
                extracted_text = f.read()
        elif file_type == "pdf":
            if PyPDF2:
                with open(file_path, "rb") as f:
                    reader = PyPDF2.PdfReader(f)
                    for page in reader.pages:
                        extracted_text += page.extract_text() + "\n"
            else:
                extracted_text = "[PDF text extraction requires PyPDF2 library]"
        elif file_type == "docx":
            if Document:
                document = Document(file_path)
                for para in document.paragraphs:
                    extracted_text += para.text + "\n"
            else:
                extracted_text = "[DOCX text extraction requires python-docx library]"
        elif file_type in ["png", "jpg", "jpeg"]:
            extracted_text = f"[Image uploaded: {os.path.basename(file_path)}]"
        else:
            extracted_text = f"[Unsupported file type for text extraction: {file_type}]"
    except Exception as e:
        logger.error(f"Error extracting text from {file_path}: {e}")
        extracted_text = f"[Error extracting text: {e}]"
    return extracted_text

# ── Parent Configuration ────────────────────────────────
PARENT_CONFIG_PATH = os.path.join(SCRIPT_DIR, "parent_config.json")
DEFAULT_PARENT_CONFIG = {
    "pin": "1234",
    "instructions": "",
    "focus_topics": [],
    "vocabulary": [],
    "progress_log": [],
    "student_profile": {
        "hobbies_interests": [],
        "social_level": "",
        "academic_weak_areas": [],
        "stress_indicators": [],
        "learning_style_preferences": []
    },
    "council_overrides": {
        "active_strategies": ["Flashcards", "Blurting", "Spaced Repetition", "Teach-Back", "Mind Mapping"],
        "disabled_personas": []
    },
    "settings": {
        "council_intensity": "supportive",
        "session_timeout_minutes": 30
    },
    "report_intelligence": {
        "enabled": True,
        "reports": []
    }
}

# ── Council Engine Import ──────────────────────────────
SENTINEL_DIR = os.path.join(SCRIPT_DIR, "Sentinel_Bridge")
sys.path.insert(0, SENTINEL_DIR)
try:
    from council_engine import build_council_prompt, get_council_status
    COUNCIL_AVAILABLE = True
    logger.info("Council of Therapists engine loaded.")
except ImportError as e:
    COUNCIL_AVAILABLE = False
    logger.warning(f"Council engine not available: {e}")

# ── Report Digest Engine Import ────────────────────────
try:
    from report_digest import digest_report, get_digest_summary, clear_digest
    DIGEST_AVAILABLE = True
    logger.info("Report Digest engine loaded.")
except ImportError as e:
    DIGEST_AVAILABLE = False
    logger.warning(f"Report Digest engine not available: {e}")

def _load_parent_config():
    """Loads the parent configuration from parent_config.json, creating it if it doesn't exist."""
    if not os.path.exists(PARENT_CONFIG_PATH):
        _save_parent_config(DEFAULT_PARENT_CONFIG)
        logger.info(f"Created default parent_config.json at {PARENT_CONFIG_PATH}")
    try:
        with open(PARENT_CONFIG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        logger.error(f"Error decoding {PARENT_CONFIG_PATH}. Resetting to default config.")
        _save_parent_config(DEFAULT_PARENT_CONFIG)
        return DEFAULT_PARENT_CONFIG
    except Exception as e:
        logger.error(f"Error loading parent_config.json: {e}. Resetting to default config.")
        _save_parent_config(DEFAULT_PARENT_CONFIG)
        return DEFAULT_PARENT_CONFIG

def _save_parent_config(config):
    """Saves the parent configuration to parent_config.json."""
    os.makedirs(os.path.dirname(PARENT_CONFIG_PATH), exist_ok=True) # Ensure directory exists
    with open(PARENT_CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
    logger.info(f"Parent configuration saved to {PARENT_CONFIG_PATH}")

# ── Import V3 Streaming Engine ───────────────────────────
try:
    from app_stream import stream_chat, clear_stream_history
    STREAMING = True
    logger.info("V3 Streaming Engine loaded.")
except ImportError:
    STREAMING = False
    logger.warning("Streaming engine not available.")

# Pydantic models for request bodies
class ChatRequest(BaseModel):
    prompt: str
    dashboard_context: dict | None = None

class ParentConfigRequest(BaseModel):
    instructions: str | None = None
    focus_topics: list[str] | None = None
    vocabulary: list[dict] | None = None # Assuming vocabulary items are dicts like {"word": "...", "definition": "...", "example": "..."}

class AcademicWeakArea(BaseModel):
    subject: str
    specific_area: str
    severity: str  # "low", "medium", "high"

class StudentProfileRequest(BaseModel):
    hobbies_interests: Optional[List[str]] = None
    social_level: Optional[str] = None
    academic_weak_areas: Optional[List[AcademicWeakArea]] = None
    stress_indicators: Optional[List[str]] = None
    learning_style_preferences: Optional[List[str]] = None

class CouncilOverrideRequest(BaseModel):
    active_strategies: Optional[List[str]] = None
    disabled_personas: Optional[List[str]] = None

class PinVerifyRequest(BaseModel):
    pin: str

class SettingsRequest(BaseModel):
    council_intensity: Optional[str] = None  # "supportive" or "challenging"
    session_timeout_minutes: Optional[int] = None  # 15, 30, 60, or 0 (never)

class PinResetRequest(BaseModel):
    current_pin: str
    new_pin: str

class ReportSettingsRequest(BaseModel):
    enabled: Optional[bool] = None

@app.get("/")
def root():
    return {"service": "Resonance", "version": "3.0", "streaming": STREAMING}

@app.post("/api/chat/stream")
async def chat_stream(req: ChatRequest):
    if not STREAMING:
        return JSONResponse({"error": "Streaming not available."}, status_code=503)
    if not req.prompt.strip():
        return JSONResponse({"error": "No prompt."}, status_code=400)
    def generate():
        for event in stream_chat(req.prompt, dashboard_context=req.dashboard_context):
            yield f"data: {json.dumps(event)}\n\n"
    return StreamingResponse(generate(), media_type="text/event-stream")

@app.post("/api/chat/clear")
def clear_chat():
    if STREAMING: clear_stream_history()
    return {"status": "ok"}

@app.get("/api/health")
def health():
    return {"status": "healthy", "streaming": STREAMING}

@app.post("/api/upload")
async def upload_file(file: UploadFile = File(...), section_tag: Optional[str] = None):
    """
    Accepts multipart file uploads, saves them, extracts text, and updates file context.
    Optional section_tag links the file to a specific Student Profile section.
    Supported types: .txt, .pdf, .docx, .csv, .md, .png, .jpg, .jpeg
    """
    allowed_extensions = {".txt", ".pdf", ".docx", ".csv", ".md", ".png", ".jpg", ".jpeg"}
    file_extension = os.path.splitext(file.filename)[1].lower()

    if file_extension not in allowed_extensions:
        raise HTTPException(status_code=400, detail=f"File type {file_extension} not allowed.")

    # Sanitize filename to prevent path traversal
    safe_filename = os.path.basename(file.filename)
    file_path = os.path.join(UPLOADS_DIR, safe_filename)

    # Save the file
    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        logger.info(f"File saved: {file_path}")
    except Exception as e:
        logger.error(f"Could not save file {safe_filename}: {e}")
        raise HTTPException(status_code=500, detail=f"Could not save file: {e}")

    # Extract text
    extracted_text = await _extract_text_from_file(file_path, file_extension.lstrip('.'))
    logger.info(f"Text extracted from {safe_filename}, length: {len(extracted_text)}")

    # Update file context
    file_context = _load_file_context()
    new_entry = {
        "filename": safe_filename,
        "type": file_extension.lstrip('.'),
        "extracted_text": extracted_text,
        "uploaded_at": datetime.now().isoformat(),
        "section_tag": section_tag or "general"
    }
    # Remove existing entry if filename is the same (overwrite)
    file_context["files"] = [f for f in file_context["files"] if f["filename"] != safe_filename]
    file_context["files"].append(new_entry)
    _save_file_context(file_context)

    return JSONResponse({
        "status": "ok",
        "filename": safe_filename,
        "text_length": len(extracted_text),
        "section_tag": section_tag or "general"
    })

@app.get("/api/uploads")
async def get_uploads():
    """Returns a list of currently uploaded files and their metadata."""
    file_context = _load_file_context()
    return JSONResponse({"files": [{"filename": f["filename"], "type": f["type"], "uploaded_at": f["uploaded_at"], "text_length": len(f["extracted_text"]), "section_tag": f.get("section_tag", "general")} for f in file_context["files"]]})

@app.get("/api/uploads/by-section/{section}")
async def get_uploads_by_section(section: str):
    """Returns files tagged for a specific Student Profile section."""
    file_context = _load_file_context()
    section_files = [f for f in file_context["files"] if f.get("section_tag") == section]
    return JSONResponse({"files": [{"filename": f["filename"], "type": f["type"], "uploaded_at": f["uploaded_at"], "text_length": len(f["extracted_text"]), "section_tag": f.get("section_tag", "general")} for f in section_files]})

@app.delete("/api/uploads/{filename}")
async def delete_upload(filename: str):
    """Removes a specific uploaded file and its entry from file_context.json."""
    file_path = os.path.join(UPLOADS_DIR, os.path.basename(filename)) # Sanitize filename
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found.")

    try:
        os.remove(file_path)
        file_context = _load_file_context()
        file_context["files"] = [f for f in file_context["files"] if f["filename"] != filename]
        _save_file_context(file_context)
        logger.info(f"File deleted: {filename}")
        return JSONResponse({"status": "ok", "message": f"File {filename} deleted."})
    except Exception as e:
        logger.error(f"Could not delete file {filename}: {e}")
        raise HTTPException(status_code=500, detail=f"Could not delete file: {e}")

# ── Parent Configuration API Endpoints ──────────────────

@app.get("/api/parent/config")
async def get_parent_config():
    """Returns the current parent configuration (excluding the PIN)."""
    config = _load_parent_config()
    display_config = config.copy()
    display_config.pop("pin", None) # Remove pin for security
    return JSONResponse(display_config)

@app.post("/api/parent/config")
async def update_parent_config(req: ParentConfigRequest):
    """Updates the parent configuration with provided fields."""
    config = _load_parent_config()
    if req.instructions is not None:
        config["instructions"] = req.instructions
    if req.focus_topics is not None:
        config["focus_topics"] = req.focus_topics
    if req.vocabulary is not None:
        config["vocabulary"] = req.vocabulary
    _save_parent_config(config)
    return JSONResponse({"status": "ok"})

@app.post("/api/parent/verify-pin")
async def verify_parent_pin(req: PinVerifyRequest):
    """Verifies the provided PIN against the stored parent PIN."""
    config = _load_parent_config()
    is_valid = (req.pin == config.get("pin"))
    return JSONResponse({"valid": is_valid})

@app.get("/api/parent/progress")
async def get_parent_progress_log():
    """Returns the progress log from the parent configuration."""
    config = _load_parent_config()
    return JSONResponse(config.get("progress_log", []))

# ── Student Profile & Council Endpoints ─────────────────

@app.post("/api/parent/profile")
def update_student_profile(req: StudentProfileRequest):
    """Saves the structured Guided Interview data to parent_config.json."""
    config = _load_parent_config()
    profile = config.get("student_profile", {})

    # Sanitize and merge provided fields
    VALID_SOCIAL_LEVELS = ["isolated", "small_group", "social", "leader", ""]
    VALID_SEVERITIES = ["low", "medium", "high"]
    VALID_STRESSORS = ["Academic Pressure", "Social Anxiety", "Test Anxiety", "Homework Overload", "Time Management", "Peer Conflicts"]
    VALID_LEARNING_STYLES = ["Visual", "Auditory", "Kinesthetic", "Reading/Writing"]

    if req.hobbies_interests is not None:
        # Allow custom hobbies, but sanitize string length
        profile["hobbies_interests"] = [h.strip()[:50] for h in req.hobbies_interests if h.strip()][:15]
    if req.social_level is not None:
        if req.social_level in VALID_SOCIAL_LEVELS:
            profile["social_level"] = req.social_level
        else:
            raise HTTPException(status_code=400, detail=f"Invalid social_level. Must be one of: {VALID_SOCIAL_LEVELS}")
    if req.academic_weak_areas is not None:
        sanitized_areas = []
        for area in req.academic_weak_areas[:10]:  # Max 10 areas
            if area.severity not in VALID_SEVERITIES:
                raise HTTPException(status_code=400, detail=f"Invalid severity '{area.severity}'. Must be one of: {VALID_SEVERITIES}")
            sanitized_areas.append({
                "subject": area.subject.strip()[:50],
                "specific_area": area.specific_area.strip()[:100],
                "severity": area.severity,
            })
        profile["academic_weak_areas"] = sanitized_areas
    if req.stress_indicators is not None:
        profile["stress_indicators"] = [s for s in req.stress_indicators if s in VALID_STRESSORS]
    if req.learning_style_preferences is not None:
        profile["learning_style_preferences"] = [l for l in req.learning_style_preferences if l in VALID_LEARNING_STYLES]

    config["student_profile"] = profile
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "student_profile": profile})

@app.get("/api/parent/council-preview")
def get_council_preview():
    """Returns the generated Council of Therapists status and prompt preview."""
    if not COUNCIL_AVAILABLE:
        raise HTTPException(status_code=503, detail="Council engine not loaded.")
    config = _load_parent_config()
    return JSONResponse(get_council_status(config))

@app.post("/api/parent/council-overrides")
def update_council_overrides(req: CouncilOverrideRequest):
    """Updates the Council override settings (enable/disable personas, strategies)."""
    config = _load_parent_config()
    overrides = config.get("council_overrides", {})

    if req.active_strategies is not None:
        overrides["active_strategies"] = [s.strip()[:50] for s in req.active_strategies if s.strip()][:10]
    if req.disabled_personas is not None:
        overrides["disabled_personas"] = [p.strip() for p in req.disabled_personas if p.strip()][:10]

    config["council_overrides"] = overrides
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "council_overrides": overrides})

# ── Settings, PIN Reset, Profile Reset Endpoints ─────────

@app.post("/api/parent/settings")
def update_parent_settings(req: SettingsRequest):
    """Updates parent portal settings (intensity, timeout)."""
    config = _load_parent_config()
    settings = config.get("settings", {})

    VALID_INTENSITIES = ["supportive", "challenging"]
    VALID_TIMEOUTS = [0, 15, 30, 60]

    if req.council_intensity is not None:
        if req.council_intensity not in VALID_INTENSITIES:
            raise HTTPException(status_code=400, detail=f"Invalid intensity. Must be one of: {VALID_INTENSITIES}")
        settings["council_intensity"] = req.council_intensity
    if req.session_timeout_minutes is not None:
        if req.session_timeout_minutes not in VALID_TIMEOUTS:
            raise HTTPException(status_code=400, detail=f"Invalid timeout. Must be one of: {VALID_TIMEOUTS}")
        settings["session_timeout_minutes"] = req.session_timeout_minutes

    config["settings"] = settings
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "settings": settings})

@app.post("/api/parent/pin-reset")
def reset_parent_pin(req: PinResetRequest):
    """Resets the Parent Portal PIN. Requires current PIN for verification."""
    config = _load_parent_config()
    if req.current_pin != config.get("pin"):
        raise HTTPException(status_code=403, detail="Current PIN is incorrect.")
    if not req.new_pin.strip() or len(req.new_pin.strip()) < 4:
        raise HTTPException(status_code=400, detail="New PIN must be at least 4 characters.")
    config["pin"] = req.new_pin.strip()
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "message": "PIN updated successfully."})

@app.post("/api/parent/reset-profile")
def reset_student_profile(req: PinVerifyRequest):
    """Clears the student profile and council overrides. Requires PIN verification."""
    config = _load_parent_config()
    if req.pin != config.get("pin"):
        raise HTTPException(status_code=403, detail="PIN is incorrect. Cannot reset.")
    config["student_profile"] = DEFAULT_PARENT_CONFIG["student_profile"].copy()
    config["council_overrides"] = DEFAULT_PARENT_CONFIG["council_overrides"].copy()
    config["settings"] = DEFAULT_PARENT_CONFIG["settings"].copy()
    config["instructions"] = ""
    config["focus_topics"] = []
    config["vocabulary"] = []
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "message": "Profile reset to defaults."})

# ── Professional Report Endpoints ────────────────────────
REPORTS_BASE_DIR = os.path.join(SCRIPT_DIR, "Professional_Reports")

@app.post("/api/parent/report-upload")
async def upload_professional_report(file: UploadFile = File(...), category: str = "medical"):
    """
    Uploads a professional report, stores it in the category folder,
    extracts text, and triggers AI digest processing.
    """
    if not DIGEST_AVAILABLE:
        raise HTTPException(status_code=503, detail="Report digest engine not available.")

    valid_categories = ["medical", "educational", "behavioral"]
    if category not in valid_categories:
        raise HTTPException(status_code=400, detail=f"Invalid category. Must be one of: {valid_categories}")

    allowed_extensions = {".txt", ".pdf", ".docx"}
    file_extension = os.path.splitext(file.filename)[1].lower()
    if file_extension not in allowed_extensions:
        raise HTTPException(status_code=400, detail=f"File type {file_extension} not allowed. Accepted: .txt, .pdf, .docx")

    # Save to category subfolder
    category_dir = os.path.join(REPORTS_BASE_DIR, category)
    os.makedirs(category_dir, exist_ok=True)
    safe_filename = os.path.basename(file.filename)
    file_path = os.path.join(category_dir, safe_filename)

    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        logger.info(f"Report saved: {file_path}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Could not save report: {e}")

    # Extract text
    extracted_text = await _extract_text_from_file(file_path, file_extension.lstrip('.'))

    # Trigger AI digest (this calls Gemini)
    try:
        digest = digest_report(extracted_text, category, safe_filename)
        digest_status = "processed"
    except Exception as e:
        logger.error(f"Digest processing failed: {e}")
        digest = {}
        digest_status = "error"

    # Log the report in parent config
    config = _load_parent_config()
    report_intel = config.get("report_intelligence", {"enabled": True, "reports": []})
    report_entry = {
        "filename": safe_filename,
        "category": category,
        "uploaded_at": datetime.now().isoformat(),
        "status": digest_status,
    }
    # Remove duplicate entries for same filename
    report_intel["reports"] = [r for r in report_intel.get("reports", []) if r["filename"] != safe_filename]
    report_intel["reports"].append(report_entry)
    config["report_intelligence"] = report_intel
    _save_parent_config(config)

    return JSONResponse({
        "status": "ok",
        "filename": safe_filename,
        "category": category,
        "digest_status": digest_status,
        "insights_count": digest.get("total_insights", 0) if isinstance(digest, dict) else 0,
    })

@app.get("/api/parent/report-digest")
def get_report_digest():
    """Returns the parent-friendly summary of extracted clinical intelligence."""
    if not DIGEST_AVAILABLE:
        raise HTTPException(status_code=503, detail="Report digest engine not available.")
    return JSONResponse(get_digest_summary())

@app.post("/api/parent/report-settings")
def update_report_settings(req: ReportSettingsRequest):
    """Toggles the report intelligence on/off."""
    config = _load_parent_config()
    report_intel = config.get("report_intelligence", {"enabled": True, "reports": []})
    if req.enabled is not None:
        report_intel["enabled"] = req.enabled
    config["report_intelligence"] = report_intel
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "enabled": report_intel["enabled"]})

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=5006)