"""
Resonance — FastAPI Backend Server
Generated by Meta App Factory V3
"""

# ── V3.0 Resilience Integration ──────────────────────────
import os as _os, sys as _sys
_FACTORY_DIR = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), ".."))
_sys.path.insert(0, _FACTORY_DIR)
try:
    from factory import safe_post
    from local_state_manager import StateManager as _StateManager
    _v3_sm = _StateManager()
    _V3_AVAILABLE = True
except ImportError:
    _V3_AVAILABLE = False
# ── End V3 Integration ──────────────────────────────────

from auto_heal import healed_post, auto_heal, diagnose

def _v3_preflight():
    """V3: Ping Resonance_Watchdog_V3 before execution."""
    if not _V3_AVAILABLE:
        return True
    try:
        import json as _j
        _cfg_path = _os.path.join(_FACTORY_DIR, "resilience_config.json")
        if not _os.path.exists(_cfg_path):
            return True
        with open(_cfg_path) as _f:
            _cfg = _j.load(_f)
        _url = _cfg.get("cloud_health", {}).get("watchdog_url", "")
        if not _url:
            return True
        import requests as _rq
        _r = _rq.get(_url, timeout=5)
        return _r.status_code == 200
    except Exception:
        return False


import os, sys, json, logging, shutil, base64, requests as _requests
from typing import Optional, List
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel
from dotenv import load_dotenv
from datetime import datetime

# For PDF
try:
    import PyPDF2
except ImportError:
    PyPDF2 = None
    logging.warning("PyPDF2 not installed. PDF file extraction will not work.")

# For DOCX
try:
    from docx import Document
except ImportError:
    Document = None
    logging.warning("python-docx not installed. DOCX file extraction will not work.")

# For PPTX
try:
    from pptx import Presentation
except ImportError:
    Presentation = None
    logging.warning("python-pptx not installed. PPTX file extraction will not work.")


# Load .env variables (resilient to encoding issues in parent .env)
try:
    load_dotenv()
except Exception:
    pass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [Resonance] %(message)s")
logger = logging.getLogger("Resonance")

app = FastAPI(title="Resonance API", version="3.0")

# Widen CORS origins for Vite port jumping (5173-5180)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[f"http://localhost:{p}" for p in range(5173, 5181)],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── File Upload Configuration ───────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOADS_DIR = os.path.join(SCRIPT_DIR, "uploads")
FILE_CONTEXT_PATH = os.path.join(UPLOADS_DIR, "file_context.json")

# Ensure uploads directory exists
os.makedirs(UPLOADS_DIR, exist_ok=True)

def _load_file_context():
    """Loads the file context from file_context.json."""
    if os.path.exists(FILE_CONTEXT_PATH):
        try:
            with open(FILE_CONTEXT_PATH, "r", encoding="utf-8") as f:
                return json.load(f)
        except json.JSONDecodeError:
            logger.error(f"Error decoding {FILE_CONTEXT_PATH}. Starting with empty context.")
            return {"files": []}
    return {"files": []}

def _save_file_context(context):
    """Saves the file context to file_context.json."""
    with open(FILE_CONTEXT_PATH, "w", encoding="utf-8") as f:
        json.dump(context, f, indent=2)

async def _extract_text_from_file(file_path: str, file_type: str) -> str:
    """Extracts text content from various file types."""
    extracted_text = ""
    try:
        if file_type in ["txt", "md", "csv"]:
            with open(file_path, "r", encoding="utf-8") as f:
                extracted_text = f.read()
        elif file_type == "pdf":
            if PyPDF2:
                with open(file_path, "rb") as f:
                    reader = PyPDF2.PdfReader(f)
                    for page in reader.pages:
                        extracted_text += page.extract_text() + "\n"
            else:
                extracted_text = "[PDF text extraction requires PyPDF2 library]"
        elif file_type == "docx":
            if Document:
                document = Document(file_path)
                for para in document.paragraphs:
                    extracted_text += para.text + "\n"
            else:
                extracted_text = "[DOCX text extraction requires python-docx library]"
        elif file_type == "pptx":
            if Presentation:
                prs = Presentation(file_path)
                for slide_num, slide in enumerate(prs.slides, 1):
                    extracted_text += f"--- Slide {slide_num} ---\n"
                    for shape in slide.shapes:
                        if hasattr(shape, "text") and shape.text.strip():
                            extracted_text += shape.text + "\n"
            else:
                extracted_text = "[PPTX text extraction requires python-pptx library]"
        elif file_type in ["png", "jpg", "jpeg"]:
            # ── Gemini Vision OCR ──────────────────────────
            extracted_text = _extract_text_via_gemini_vision(file_path, file_type)
        else:
            extracted_text = f"[Unsupported file type for text extraction: {file_type}]"
    except Exception as e:
        logger.error(f"Error extracting text from {file_path}: {e}")
        extracted_text = f"[Error extracting text: {e}]"
    return extracted_text


def _extract_text_via_gemini_vision(file_path: str, file_type: str) -> str:
    """
    Uses Gemini 2.5 Flash multimodal vision to extract handwritten/printed
    text from an uploaded image (homework photo, whiteboard, etc.).
    """
    # Get API key from vault or env
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        try:
            from vault_client import get_secret
            api_key = get_secret("GEMINI_API_KEY")
        except Exception:
            pass
    if not api_key:
        logger.error("Gemini Vision OCR: No API key available.")
        return f"[Image uploaded: {os.path.basename(file_path)} — OCR unavailable, no API key]"

    # Read image and base64 encode
    try:
        with open(file_path, "rb") as img_f:
            image_bytes = img_f.read()
        b64_image = base64.b64encode(image_bytes).decode("utf-8")
    except Exception as e:
        logger.error(f"Gemini Vision OCR: Failed to read image: {e}")
        return f"[Image uploaded: {os.path.basename(file_path)} — could not read file]"

    mime_map = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg"}
    mime_type = mime_map.get(file_type, "image/png")

    # Call Gemini multimodal endpoint
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    headers = {"x-goog-api-key": api_key, "Content-Type": "application/json"}
    payload = {
        "contents": [{
            "parts": [
                {"text": "Extract ALL text from this image exactly as written. Include equations, numbers, letters, and any handwritten content. Preserve the structure and formatting. If it is homework, identify the subject and list each problem separately. Output ONLY the extracted text, nothing else."},
                {"inline_data": {"mime_type": mime_type, "data": b64_image}}
            ]
        }],
        "generationConfig": {"temperature": 0.1, "maxOutputTokens": 4096}
    }

    try:
        resp = _requests.post(url, json=payload, headers=headers, timeout=30)
        if resp.status_code == 200:
            data = resp.json()
            parts = data.get("candidates", [{}])[0].get("content", {}).get("parts", [])
            extracted = "".join(p.get("text", "") for p in parts).strip()
            if extracted:
                logger.info(f"Gemini Vision OCR: Extracted {len(extracted)} chars from {os.path.basename(file_path)}")
                return extracted
            else:
                logger.warning("Gemini Vision OCR: No text detected in image.")
                return f"[Image uploaded: {os.path.basename(file_path)} — no text detected]"
        else:
            logger.error(f"Gemini Vision OCR failed: {resp.status_code} {resp.text[:200]}")
            return f"[Image uploaded: {os.path.basename(file_path)} — OCR error {resp.status_code}]"
    except Exception as e:
        logger.error(f"Gemini Vision OCR exception: {e}")
        return f"[Image uploaded: {os.path.basename(file_path)} — OCR exception]"

# ── Parent Configuration ────────────────────────────────
PARENT_CONFIG_PATH = os.path.join(SCRIPT_DIR, "parent_config.json")
DEFAULT_PARENT_CONFIG = {
    "pin": "1234",
    "instructions": "",
    "focus_topics": [],
    "vocabulary": [],
    "progress_log": [],
    "student_profile": {
        "hobbies_interests": [],
        "social_level": "",
        "academic_weak_areas": [],
        "stress_indicators": [],
        "learning_style_preferences": []
    },
    "council_overrides": {
        "active_strategies": ["Flashcards", "Blurting", "Spaced Repetition", "Teach-Back", "Mind Mapping"],
        "disabled_personas": []
    },
    "settings": {
        "council_intensity": "supportive",
        "session_timeout_minutes": 30
    },
    "report_intelligence": {
        "enabled": True,
        "reports": []
    }
}

# ── Council Engine Import ──────────────────────────────
SENTINEL_DIR = os.path.join(SCRIPT_DIR, "Sentinel_Bridge")
sys.path.insert(0, SENTINEL_DIR)
try:
    from council_engine import build_council_prompt, get_council_status
    COUNCIL_AVAILABLE = True
    logger.info("Council of Therapists engine loaded.")
except ImportError as e:
    COUNCIL_AVAILABLE = False
    logger.warning(f"Council engine not available: {e}")

# ── Report Digest Engine Import ────────────────────────
try:
    from report_digest import digest_report, get_digest_summary, clear_digest
    DIGEST_AVAILABLE = True
    logger.info("Report Digest engine loaded.")
except ImportError as e:
    DIGEST_AVAILABLE = False
    logger.warning(f"Report Digest engine not available: {e}")

# ── Dr. Aris (Psychologist Agent) Import ───────────────
try:
    from dr_aris_engine import (
        analyze_profile, get_alerts as get_aris_alerts, get_proposals as get_aris_proposals,
        approve_proposal, reject_proposal, get_dr_aris_report,
        boardroom_query, get_boardroom_history
    )
    DR_ARIS_AVAILABLE = True
    logger.info("Dr. Aris psychologist engine loaded.")
except ImportError as e:
    DR_ARIS_AVAILABLE = False
    logger.warning(f"Dr. Aris engine not available: {e}")

# ── Nerve Center (Self-Healing Engine) Import ──────────
try:
    from nerve_center import NerveCenter, start_background_monitor, get_nerve_instance
    NERVE_CENTER_AVAILABLE = True
    logger.info("Nerve Center self-healing engine loaded.")
except ImportError as e:
    NERVE_CENTER_AVAILABLE = False
    logger.warning(f"Nerve Center not available: {e}")

def _load_parent_config():
    """Loads the parent configuration from parent_config.json, creating it if it doesn't exist."""
    if not os.path.exists(PARENT_CONFIG_PATH):
        _save_parent_config(DEFAULT_PARENT_CONFIG)
        logger.info(f"Created default parent_config.json at {PARENT_CONFIG_PATH}")
    try:
        with open(PARENT_CONFIG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        logger.error(f"Error decoding {PARENT_CONFIG_PATH}. Resetting to default config.")
        _save_parent_config(DEFAULT_PARENT_CONFIG)
        return DEFAULT_PARENT_CONFIG
    except Exception as e:
        logger.error(f"Error loading parent_config.json: {e}. Resetting to default config.")
        _save_parent_config(DEFAULT_PARENT_CONFIG)
        return DEFAULT_PARENT_CONFIG

def _save_parent_config(config):
    """Saves the parent configuration to parent_config.json."""
    os.makedirs(os.path.dirname(PARENT_CONFIG_PATH), exist_ok=True) # Ensure directory exists
    with open(PARENT_CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
    logger.info(f"Parent configuration saved to {PARENT_CONFIG_PATH}")

# ── Import V3 Streaming Engine ───────────────────────────
try:
    from app_stream import stream_chat, clear_stream_history
    STREAMING = True
    logger.info("V3 Streaming Engine loaded.")
except ImportError:
    STREAMING = False
    logger.warning("Streaming engine not available.")

# Pydantic models for request bodies
class ChatRequest(BaseModel):
    prompt: str
    dashboard_context: dict | None = None

class ParentConfigRequest(BaseModel):
    instructions: str | None = None
    focus_topics: list[str] | None = None
    vocabulary: list[dict] | None = None # Assuming vocabulary items are dicts like {"word": "...", "definition": "...", "example": "..."}

class AcademicWeakArea(BaseModel):
    subject: str
    specific_area: str
    severity: str  # "low", "medium", "high"

class StudentProfileRequest(BaseModel):
    hobbies_interests: Optional[List[str]] = None
    social_level: Optional[str] = None
    academic_weak_areas: Optional[List[AcademicWeakArea]] = None
    stress_indicators: Optional[List[str]] = None
    learning_style_preferences: Optional[List[str]] = None

class CouncilOverrideRequest(BaseModel):
    active_strategies: Optional[List[str]] = None
    disabled_personas: Optional[List[str]] = None

class PinVerifyRequest(BaseModel):
    pin: str

class SettingsRequest(BaseModel):
    council_intensity: Optional[str] = None  # "supportive" or "challenging"
    session_timeout_minutes: Optional[int] = None  # 15, 30, 60, or 0 (never)

class PinResetRequest(BaseModel):
    current_pin: str
    new_pin: str

class ReportSettingsRequest(BaseModel):
    enabled: Optional[bool] = None

# ── Auto-start Nerve Center Background Monitor ────────
@app.on_event("startup")
async def startup_nerve_center():
    if NERVE_CENTER_AVAILABLE:
        try:
            start_background_monitor(interval_seconds=300)  # Scan every 5 minutes
            logger.info("Nerve Center background monitor started (interval: 300s).")
        except Exception as e:
            logger.warning(f"Nerve Center background start failed: {e}")

# ── Serve Built Frontend ──────────────────────────────────
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse as _FileResponse

_FRONTEND_DIST = os.path.join(SCRIPT_DIR, "resonance_ui", "dist")
_HAS_FRONTEND = os.path.isdir(_FRONTEND_DIST)
if _HAS_FRONTEND:
    _assets_dir = os.path.join(_FRONTEND_DIST, "assets")
    if os.path.isdir(_assets_dir):
        app.mount("/assets", StaticFiles(directory=_assets_dir), name="resonance-assets")
    logger.info(f"Frontend mounted from {_FRONTEND_DIST}")
else:
    logger.warning(f"No frontend build at {_FRONTEND_DIST}. Run 'npm run build' in resonance_ui/.")

@app.get("/")
def root():
    if _HAS_FRONTEND:
        return _FileResponse(os.path.join(_FRONTEND_DIST, "index.html"))
    return {"service": "Resonance", "version": "3.0", "streaming": STREAMING, "nerve_center": NERVE_CENTER_AVAILABLE}

@app.get("/api/info")
def api_info():
    return {"service": "Resonance", "version": "3.0", "streaming": STREAMING, "nerve_center": NERVE_CENTER_AVAILABLE}

@app.post("/api/chat/stream")
async def chat_stream(req: ChatRequest):
    if not STREAMING:
        return JSONResponse({"error": "Streaming not available."}, status_code=503)
    if not req.prompt.strip():
        return JSONResponse({"error": "No prompt."}, status_code=400)
    def generate():
        for event in stream_chat(req.prompt, dashboard_context=req.dashboard_context):
            yield f"data: {json.dumps(event)}\n\n"
    return StreamingResponse(generate(), media_type="text/event-stream")

@app.post("/api/chat/clear")
def clear_chat():
    if STREAMING: clear_stream_history()
    return {"status": "ok"}

@app.get("/api/health")
def health():
    return {"status": "healthy", "streaming": STREAMING}

@app.post("/api/upload")
async def upload_file(file: UploadFile = File(...), section_tag: Optional[str] = None):
    """
    Accepts multipart file uploads, saves them, extracts text, and updates file context.
    Optional section_tag links the file to a specific Student Profile section.
    Supported types: .txt, .pdf, .docx, .csv, .md, .png, .jpg, .jpeg
    """
    allowed_extensions = {".txt", ".pdf", ".docx", ".pptx", ".csv", ".md", ".png", ".jpg", ".jpeg"}
    file_extension = os.path.splitext(file.filename)[1].lower()

    if file_extension not in allowed_extensions:
        raise HTTPException(status_code=400, detail=f"File type {file_extension} not allowed.")

    # Sanitize filename to prevent path traversal
    safe_filename = os.path.basename(file.filename)
    file_path = os.path.join(UPLOADS_DIR, safe_filename)

    # Save the file
    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        logger.info(f"File saved: {file_path}")
    except Exception as e:
        logger.error(f"Could not save file {safe_filename}: {e}")
        raise HTTPException(status_code=500, detail=f"Could not save file: {e}")

    # Extract text
    extracted_text = await _extract_text_from_file(file_path, file_extension.lstrip('.'))
    logger.info(f"Text extracted from {safe_filename}, length: {len(extracted_text)}")

    # Update file context
    file_context = _load_file_context()
    new_entry = {
        "filename": safe_filename,
        "type": file_extension.lstrip('.'),
        "extracted_text": extracted_text,
        "uploaded_at": datetime.now().isoformat(),
        "section_tag": section_tag or "general"
    }
    # Remove existing entry if filename is the same (overwrite)
    file_context["files"] = [f for f in file_context["files"] if f["filename"] != safe_filename]
    file_context["files"].append(new_entry)
    _save_file_context(file_context)

    # Study mode is available if meaningful text was extracted (not images)
    study_available = len(extracted_text) > 50 and not extracted_text.startswith("[")

    return JSONResponse({
        "status": "ok",
        "filename": safe_filename,
        "text_length": len(extracted_text),
        "section_tag": section_tag or "general",
        "study_available": study_available,
    })

@app.get("/api/uploads")
async def get_uploads():
    """Returns a list of currently uploaded files and their metadata."""
    file_context = _load_file_context()
    return JSONResponse({"files": [{"filename": f["filename"], "type": f["type"], "uploaded_at": f["uploaded_at"], "text_length": len(f["extracted_text"]), "section_tag": f.get("section_tag", "general")} for f in file_context["files"]]})

@app.get("/api/uploads/by-section/{section}")
async def get_uploads_by_section(section: str):
    """Returns files tagged for a specific Student Profile section."""
    file_context = _load_file_context()
    section_files = [f for f in file_context["files"] if f.get("section_tag") == section]
    return JSONResponse({"files": [{"filename": f["filename"], "type": f["type"], "uploaded_at": f["uploaded_at"], "text_length": len(f["extracted_text"]), "section_tag": f.get("section_tag", "general")} for f in section_files]})

@app.delete("/api/uploads/{filename}")
async def delete_upload(filename: str):
    """Removes a specific uploaded file and its entry from file_context.json."""
    file_path = os.path.join(UPLOADS_DIR, os.path.basename(filename)) # Sanitize filename
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found.")

    try:
        os.remove(file_path)
        file_context = _load_file_context()
        file_context["files"] = [f for f in file_context["files"] if f["filename"] != filename]
        _save_file_context(file_context)
        logger.info(f"File deleted: {filename}")
        return JSONResponse({"status": "ok", "message": f"File {filename} deleted."})
    except Exception as e:
        logger.error(f"Could not delete file {filename}: {e}")
        raise HTTPException(status_code=500, detail=f"Could not delete file: {e}")

# ── Parent Configuration API Endpoints ──────────────────

@app.get("/api/parent/config")
async def get_parent_config():
    """Returns the current parent configuration (excluding the PIN)."""
    config = _load_parent_config()
    display_config = config.copy()
    display_config.pop("pin", None) # Remove pin for security
    return JSONResponse(display_config)

@app.post("/api/parent/config")
async def update_parent_config(req: ParentConfigRequest):
    """Updates the parent configuration with provided fields."""
    config = _load_parent_config()
    if req.instructions is not None:
        config["instructions"] = req.instructions
    if req.focus_topics is not None:
        config["focus_topics"] = req.focus_topics
    if req.vocabulary is not None:
        config["vocabulary"] = req.vocabulary
    _save_parent_config(config)
    return JSONResponse({"status": "ok"})

@app.post("/api/parent/verify-pin")
async def verify_parent_pin(req: PinVerifyRequest):
    """Verifies the provided PIN against the stored parent PIN."""
    config = _load_parent_config()
    is_valid = (req.pin == config.get("pin"))
    return JSONResponse({"valid": is_valid})

@app.get("/api/parent/progress")
async def get_parent_progress_log():
    """Returns the progress log from the parent configuration."""
    config = _load_parent_config()
    return JSONResponse(config.get("progress_log", []))

# ── Student Profile & Council Endpoints ─────────────────

@app.post("/api/parent/profile")
def update_student_profile(req: StudentProfileRequest):
    """Saves the structured Guided Interview data to parent_config.json."""
    config = _load_parent_config()
    profile = config.get("student_profile", {})

    # Sanitize and merge provided fields
    VALID_SOCIAL_LEVELS = ["isolated", "small_group", "social", "leader", ""]
    VALID_SEVERITIES = ["low", "medium", "high"]
    VALID_STRESSORS = ["Academic Pressure", "Social Anxiety", "Test Anxiety", "Homework Overload", "Time Management", "Peer Conflicts"]
    VALID_LEARNING_STYLES = ["Visual", "Auditory", "Kinesthetic", "Reading/Writing"]

    if req.hobbies_interests is not None:
        # Allow custom hobbies, but sanitize string length
        profile["hobbies_interests"] = [h.strip()[:50] for h in req.hobbies_interests if h.strip()][:15]
    if req.social_level is not None:
        if req.social_level in VALID_SOCIAL_LEVELS:
            profile["social_level"] = req.social_level
        else:
            raise HTTPException(status_code=400, detail=f"Invalid social_level. Must be one of: {VALID_SOCIAL_LEVELS}")
    if req.academic_weak_areas is not None:
        sanitized_areas = []
        for area in req.academic_weak_areas[:10]:  # Max 10 areas
            if area.severity not in VALID_SEVERITIES:
                raise HTTPException(status_code=400, detail=f"Invalid severity '{area.severity}'. Must be one of: {VALID_SEVERITIES}")
            sanitized_areas.append({
                "subject": area.subject.strip()[:50],
                "specific_area": area.specific_area.strip()[:100],
                "severity": area.severity,
            })
        profile["academic_weak_areas"] = sanitized_areas
    if req.stress_indicators is not None:
        profile["stress_indicators"] = [s for s in req.stress_indicators if s in VALID_STRESSORS]
    if req.learning_style_preferences is not None:
        profile["learning_style_preferences"] = [l for l in req.learning_style_preferences if l in VALID_LEARNING_STYLES]

    config["student_profile"] = profile
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "student_profile": profile})

@app.get("/api/parent/council-preview")
def get_council_preview():
    """Returns the generated Council of Therapists status and prompt preview."""
    if not COUNCIL_AVAILABLE:
        raise HTTPException(status_code=503, detail="Council engine not loaded.")
    config = _load_parent_config()
    return JSONResponse(get_council_status(config))

@app.post("/api/parent/council-overrides")
def update_council_overrides(req: CouncilOverrideRequest):
    """Updates the Council override settings (enable/disable personas, strategies)."""
    config = _load_parent_config()
    overrides = config.get("council_overrides", {})

    if req.active_strategies is not None:
        overrides["active_strategies"] = [s.strip()[:50] for s in req.active_strategies if s.strip()][:10]
    if req.disabled_personas is not None:
        overrides["disabled_personas"] = [p.strip() for p in req.disabled_personas if p.strip()][:10]

    config["council_overrides"] = overrides
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "council_overrides": overrides})

# ── Settings, PIN Reset, Profile Reset Endpoints ─────────

@app.post("/api/parent/settings")
def update_parent_settings(req: SettingsRequest):
    """Updates parent portal settings (intensity, timeout)."""
    config = _load_parent_config()
    settings = config.get("settings", {})

    VALID_INTENSITIES = ["supportive", "challenging"]
    VALID_TIMEOUTS = [0, 15, 30, 60]

    if req.council_intensity is not None:
        if req.council_intensity not in VALID_INTENSITIES:
            raise HTTPException(status_code=400, detail=f"Invalid intensity. Must be one of: {VALID_INTENSITIES}")
        settings["council_intensity"] = req.council_intensity
    if req.session_timeout_minutes is not None:
        if req.session_timeout_minutes not in VALID_TIMEOUTS:
            raise HTTPException(status_code=400, detail=f"Invalid timeout. Must be one of: {VALID_TIMEOUTS}")
        settings["session_timeout_minutes"] = req.session_timeout_minutes

    config["settings"] = settings
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "settings": settings})

@app.post("/api/parent/pin-reset")
def reset_parent_pin(req: PinResetRequest):
    """Resets the Parent Portal PIN. Requires current PIN for verification."""
    config = _load_parent_config()
    if req.current_pin != config.get("pin"):
        raise HTTPException(status_code=403, detail="Current PIN is incorrect.")
    if not req.new_pin.strip() or len(req.new_pin.strip()) < 4:
        raise HTTPException(status_code=400, detail="New PIN must be at least 4 characters.")
    config["pin"] = req.new_pin.strip()
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "message": "PIN updated successfully."})

@app.post("/api/parent/reset-profile")
def reset_student_profile(req: PinVerifyRequest):
    """Clears the student profile and council overrides. Requires PIN verification."""
    config = _load_parent_config()
    if req.pin != config.get("pin"):
        raise HTTPException(status_code=403, detail="PIN is incorrect. Cannot reset.")
    config["student_profile"] = DEFAULT_PARENT_CONFIG["student_profile"].copy()
    config["council_overrides"] = DEFAULT_PARENT_CONFIG["council_overrides"].copy()
    config["settings"] = DEFAULT_PARENT_CONFIG["settings"].copy()
    config["instructions"] = ""
    config["focus_topics"] = []
    config["vocabulary"] = []
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "message": "Profile reset to defaults."})

# ── Professional Report Endpoints ────────────────────────
REPORTS_BASE_DIR = os.path.join(SCRIPT_DIR, "Professional_Reports")

@app.post("/api/parent/report-upload")
async def upload_professional_report(file: UploadFile = File(...), category: str = "medical"):
    """
    Uploads a professional report, stores it in the category folder,
    extracts text, and triggers AI digest processing.
    """
    if not DIGEST_AVAILABLE:
        raise HTTPException(status_code=503, detail="Report digest engine not available.")

    valid_categories = ["medical", "educational", "behavioral"]
    if category not in valid_categories:
        raise HTTPException(status_code=400, detail=f"Invalid category. Must be one of: {valid_categories}")

    allowed_extensions = {".txt", ".pdf", ".docx"}
    file_extension = os.path.splitext(file.filename)[1].lower()
    if file_extension not in allowed_extensions:
        raise HTTPException(status_code=400, detail=f"File type {file_extension} not allowed. Accepted: .txt, .pdf, .docx")

    # Save to category subfolder
    category_dir = os.path.join(REPORTS_BASE_DIR, category)
    os.makedirs(category_dir, exist_ok=True)
    safe_filename = os.path.basename(file.filename)
    file_path = os.path.join(category_dir, safe_filename)

    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        logger.info(f"Report saved: {file_path}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Could not save report: {e}")

    # Extract text
    extracted_text = await _extract_text_from_file(file_path, file_extension.lstrip('.'))

    # Trigger AI digest (this calls Gemini)
    try:
        digest = digest_report(extracted_text, category, safe_filename)
        digest_status = "processed"
    except Exception as e:
        logger.error(f"Digest processing failed: {e}")
        digest = {}
        digest_status = "error"

    # Log the report in parent config
    config = _load_parent_config()
    report_intel = config.get("report_intelligence", {"enabled": True, "reports": []})
    report_entry = {
        "filename": safe_filename,
        "category": category,
        "uploaded_at": datetime.now().isoformat(),
        "status": digest_status,
    }
    # Remove duplicate entries for same filename
    report_intel["reports"] = [r for r in report_intel.get("reports", []) if r["filename"] != safe_filename]
    report_intel["reports"].append(report_entry)
    config["report_intelligence"] = report_intel
    _save_parent_config(config)

    return JSONResponse({
        "status": "ok",
        "filename": safe_filename,
        "category": category,
        "digest_status": digest_status,
        "insights_count": digest.get("total_insights", 0) if isinstance(digest, dict) else 0,
    })

@app.get("/api/parent/report-digest")
def get_report_digest():
    """Returns the parent-friendly summary of extracted clinical intelligence."""
    if not DIGEST_AVAILABLE:
        raise HTTPException(status_code=503, detail="Report digest engine not available.")
    return JSONResponse(get_digest_summary())

@app.post("/api/parent/report-settings")
def update_report_settings(req: ReportSettingsRequest):
    """Toggles the report intelligence on/off."""
    config = _load_parent_config()
    report_intel = config.get("report_intelligence", {"enabled": True, "reports": []})
    if req.enabled is not None:
        report_intel["enabled"] = req.enabled
    config["report_intelligence"] = report_intel
    _save_parent_config(config)
    return JSONResponse({"status": "ok", "enabled": report_intel["enabled"]})

# ── Dr. Aris (Psychologist Agent) API Endpoints ─────────

@app.get("/api/parent/dr-aris/analysis")
def dr_aris_analysis():
    """Triggers a full Dr. Aris analysis and returns the report (profile, alerts, proposals)."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    try:
        report = analyze_profile()
        return JSONResponse(report)
    except Exception as e:
        logger.error(f"Dr. Aris analysis error: {e}")
        raise HTTPException(status_code=500, detail=f"Analysis failed: {e}")

@app.get("/api/parent/dr-aris/alerts")
def dr_aris_alerts():
    """Returns current behavioral alerts flagged by Dr. Aris."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    return JSONResponse({"alerts": get_aris_alerts()})

@app.get("/api/parent/dr-aris/proposals")
def dr_aris_proposals():
    """Returns all system update proposals with their current status."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    return JSONResponse({"proposals": get_aris_proposals()})

@app.post("/api/parent/dr-aris/proposals/{proposal_id}/approve")
def dr_aris_approve(proposal_id: str):
    """Approves a Dr. Aris proposal — injects the directive into Alex's config."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    result = approve_proposal(proposal_id)
    if result.get("status") == "error":
        raise HTTPException(status_code=404, detail=result.get("message"))
    return JSONResponse(result)

@app.post("/api/parent/dr-aris/proposals/{proposal_id}/reject")
def dr_aris_reject(proposal_id: str):
    """Rejects a Dr. Aris proposal — logs the preference for future refinement."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    result = reject_proposal(proposal_id)
    if result.get("status") == "error":
        raise HTTPException(status_code=404, detail=result.get("message"))
    return JSONResponse(result)

@app.get("/api/parent/dr-aris/report")
def dr_aris_full_report():
    """Returns the full cached Dr. Aris report without triggering a new analysis."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    return JSONResponse(get_dr_aris_report())

# ── Dr. Aris Module 1: Boardroom Consultant (B2B) ──────

class BoardroomQueryRequest(BaseModel):
    query: str
    context: str = ""

@app.post("/api/dr-aris/boardroom-query")
def dr_aris_boardroom(req: BoardroomQueryRequest):
    """Module 1: Strategic psychological consultation. Uses ONLY general market knowledge — never individual user data."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    try:
        result = boardroom_query(req.query, req.context)
        if result.get("status") == "error":
            raise HTTPException(status_code=500, detail=result.get("message"))
        return JSONResponse(result)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Dr. Aris Boardroom error: {e}")
        raise HTTPException(status_code=500, detail=f"Boardroom consultation failed: {e}")

@app.get("/api/dr-aris/boardroom-history")
def dr_aris_boardroom_log():
    """Returns the boardroom consultation history (no individual user data)."""
    if not DR_ARIS_AVAILABLE:
        raise HTTPException(status_code=503, detail="Dr. Aris engine not available.")
    return JSONResponse(get_boardroom_history())

# ── Nerve Center (Self-Healing) API Endpoints ───────────

@app.get("/api/nerve-center/status")
def nerve_center_status():
    """Returns the current Nerve Center status, circuit breaker health, and recent actions."""
    if not NERVE_CENTER_AVAILABLE:
        raise HTTPException(status_code=503, detail="Nerve Center not available.")
    nc = get_nerve_instance()
    if not nc:
        # Create a one-shot instance for status
        nc = NerveCenter()
    return JSONResponse(nc.get_status())

@app.post("/api/nerve-center/scan")
def nerve_center_scan():
    """Triggers an immediate SCAN → ANALYZE → ACT → LOG self-healing cycle."""
    if not NERVE_CENTER_AVAILABLE:
        raise HTTPException(status_code=503, detail="Nerve Center not available.")
    nc = get_nerve_instance()
    if not nc:
        nc = NerveCenter()
    report = nc.scan_and_heal()
    return JSONResponse(report)

@app.get("/api/nerve-center/review-queue")
def nerve_center_review_queue():
    """Returns failures that require manual review (not auto-healable)."""
    if not NERVE_CENTER_AVAILABLE:
        raise HTTPException(status_code=503, detail="Nerve Center not available.")
    nc = get_nerve_instance()
    if not nc:
        nc = NerveCenter()
    status = nc.get_status()
    return JSONResponse({
        "review_queue": status.get("review_queue", []),
        "total": status.get("review_queue_size", 0),
    })

# ── Dashboard API Endpoints ─────────────────────────────

FACTORY_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
REGISTRY_PATH = os.path.join(FACTORY_DIR, "registry.json")

@app.get("/api/dashboard/projects")
def dashboard_projects():
    """Returns the Project Index from registry.json."""
    try:
        with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
            registry = json.load(f)
        apps = registry.get("apps", {})
        projects = []
        for name, data in apps.items():
            projects.append({
                "name": name,
                "status": data.get("status", "unknown"),
                "type": data.get("type", "Unknown"),
                "port": data.get("port"),
                "path": data.get("path", f"Meta_App_Factory/{name}"),
                "capabilities": data.get("capabilities", []),
                "last_build": data.get("last_build"),
                "blueprint": data.get("blueprint"),
            })
        return JSONResponse({
            "projects": projects,
            "total": len(projects),
            "last_updated": registry.get("last_updated"),
        })
    except FileNotFoundError:
        return JSONResponse({"projects": [], "total": 0, "error": "registry.json not found"})
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/dashboard/health")
def dashboard_health():
    """Returns System Health: live-pings registered services and security status."""
    import requests as req_lib

    # Load registry for service list
    services = []
    try:
        with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
            registry = json.load(f)

        for name, data in registry.get("apps", {}).items():
            port = data.get("port")
            status_val = "unknown"
            if port:
                try:
                    r = req_lib.get(f"http://localhost:{port}/api/health", timeout=2)
                    status_val = "online" if r.status_code == 200 else "error"
                except Exception:
                    status_val = "offline"
            else:
                status_val = "no_port"

            services.append({
                "name": name,
                "endpoint": f"localhost:{port}" if port else "N/A",
                "status": status_val,
                "port": port,
                "type": data.get("type", "Unknown"),
            })
    except Exception as e:
        logger.warning(f"Dashboard health: registry load failed: {e}")

    # Static infrastructure services
    infra_services = [
        {"name": "n8n Cloud", "endpoint": "humanresource.app.n8n.cloud", "status": "configured", "type": "Workflow Engine"},
        {"name": "Google Drive Sync", "endpoint": "Multi-PC", "status": "active", "type": "Storage"},
    ]

    # Nerve Center status
    nerve_status = "unavailable"
    if NERVE_CENTER_AVAILABLE:
        try:
            nc = get_nerve_instance()
            if nc:
                nerve_status = "active"
            else:
                nerve_status = "idle"
        except Exception:
            nerve_status = "error"

    # Security status
    security = [
        {"item": "Credential Exposure", "status": "green", "owner": "Compliance Officer", "note": "All hardcoded keys removed"},
        {"item": "Vault Encryption", "status": "green", "owner": "Compliance Officer", "note": "Fernet AES-128 active"},
        {"item": "Isolation Boundary", "status": "green", "owner": "All agents", "note": "forbidden_references enforced"},
        {"item": "Webhook Auth", "status": "yellow", "owner": "CTO", "note": "P1: Add bearer tokens"},
    ]

    return JSONResponse({
        "services": services,
        "infrastructure": infra_services,
        "nerve_center": nerve_status,
        "security": security,
        "checked_at": datetime.now().isoformat(),
    })

@app.get("/api/dashboard/fiscal")
def dashboard_fiscal():
    """Returns Fiscal Oversight budget data."""
    try:
        sys.path.insert(0, os.path.join(FACTORY_DIR, "Project_Aether"))
        from fiscal_oversight import FiscalOversight
        fo = FiscalOversight()
        status = fo.get_status()
        return JSONResponse(status)
    except ImportError:
        return JSONResponse({
            "engine": "Not Available",
            "threshold": 10.0,
            "current_total_cost": 0.0,
            "budget_remaining": 10.0,
            "error": "fiscal_oversight module not found",
        })
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

class DashboardCommandRequest(BaseModel):
    prompt: str

@app.post("/api/dashboard/command")
def dashboard_command(req: DashboardCommandRequest):
    """Universal Input: sends a prompt to the n8n Brain webhook and returns the response."""
    webhook_url = os.getenv("WEBHOOK_URL", "")
    if not webhook_url:
        raise HTTPException(status_code=503, detail="WEBHOOK_URL not configured in .env")

    import requests as req_lib
    try:
        response = req_lib.post(
            webhook_url,
            json={"prompt": req.prompt},
            timeout=60,
        )
        response.raise_for_status()
        try:
            data = response.json()
            output = data.get("text") or data.get("output") or json.dumps(data)
        except ValueError:
            output = response.text
        return JSONResponse({"response": output, "status": "ok"})
    except req_lib.exceptions.Timeout:
        return JSONResponse({"response": "Timeout: The Brain took too long to respond.", "status": "timeout"})
    except Exception as e:
        return JSONResponse({"response": f"Error: {str(e)}", "status": "error"})

# ── Study Mode API ───────────────────────────────────────

class StudyRequest(BaseModel):
    filename: str

@app.post("/api/study/mindmap")
async def generate_mindmap(req: StudyRequest):
    """Generates a Mermaid.js knowledge graph from an uploaded document."""
    file_context = _load_file_context()
    target = next((f for f in file_context["files"] if f["filename"] == req.filename), None)
    if not target:
        raise HTTPException(status_code=404, detail="File not found in uploads")

    text = target.get("extracted_text", "")
    if len(text) < 50:
        raise HTTPException(status_code=400, detail="Not enough text content to generate a mind map")

    # Truncate to first 4000 chars for API efficiency
    text_snippet = text[:4000]

    import google.generativeai as genai
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        try:
            from vault_client import get_secret
            api_key = get_secret("GEMINI_API_KEY")
        except Exception:
            pass
    if not api_key:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")

    prompt = f"""Analyze this document and create a Mermaid.js mindmap diagram for a teenager.
Rules:
- Use the `mindmap` diagram type (radial layout, NOT flowchart)
- The root node should be the main topic with an emoji (e.g., 🧬 Biology)
- Create 3-6 branches for key themes, each with an emoji prefix (💡 for key ideas, 📝 for details, 🔬 for experiments, 🧠 for concepts, ⚡ for important facts, 🎯 for goals)
- Each branch should have 2-4 sub-items with short, punchy labels
- Keep labels SHORT (max 5 words), use teen-friendly casual language
- Add emojis to ALL nodes to make it visually scannable
- Output ONLY the raw Mermaid code, no explanation, no code fences
- Example format:
  mindmap
    root((🧬 Biology Basics))
      💡 Key Concepts
        🧠 Cells are building blocks
        ⚡ DNA carries the code
      📝 Vocabulary
        🔬 Mitosis = cell split
        🎯 Photosynthesis = food factory

Document:
{text_snippet}"""

    try:
        response = model.generate_content(prompt)
        mermaid_code = response.text.strip()
        # Clean up any accidental code fences
        if mermaid_code.startswith("```"):
            mermaid_code = mermaid_code.split("\n", 1)[-1]
        if mermaid_code.endswith("```"):
            mermaid_code = mermaid_code.rsplit("```", 1)[0].strip()
        return JSONResponse({"status": "ok", "mermaid": mermaid_code, "filename": req.filename})
    except Exception as e:
        logger.error(f"Mind map generation error: {e}")
        raise HTTPException(status_code=500, detail=f"Mind map generation failed: {str(e)}")


@app.post("/api/study/summary")
async def generate_summary(req: StudyRequest):
    """Generates a structured summary of an uploaded document."""
    file_context = _load_file_context()
    target = next((f for f in file_context["files"] if f["filename"] == req.filename), None)
    if not target:
        raise HTTPException(status_code=404, detail="File not found in uploads")

    text = target.get("extracted_text", "")
    if len(text) < 50:
        raise HTTPException(status_code=400, detail="Not enough text content to summarize")

    # Truncate to first 6000 chars for API efficiency
    text_snippet = text[:6000]

    import google.generativeai as genai
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        try:
            from vault_client import get_secret
            api_key = get_secret("GEMINI_API_KEY")
        except Exception:
            pass
    if not api_key:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")

    prompt = f"""Create a structured study summary of this document. Format it as:

## Key Concepts
- Bullet points of the main ideas

## Important Details
- Supporting facts and details

## Quick Review Questions
- 3-4 questions to test understanding

Keep it concise and student-friendly. Use simple language.

Document:
{text_snippet}"""

    try:
        response = model.generate_content(prompt)
        return JSONResponse({"status": "ok", "summary": response.text.strip(), "filename": req.filename})
    except Exception as e:
        logger.error(f"Summary generation error: {e}")
        raise HTTPException(status_code=500, detail=f"Summary generation failed: {str(e)}")

# ── Conversation-Based Study Endpoints ───────────────────────────

class ConversationStudyRequest(BaseModel):
    messages: List[dict]  # [{ "role": "user"|"assistant", "text": "..." }]

@app.post("/api/study/conversation-mindmap")
async def generate_conversation_mindmap(req: ConversationStudyRequest):
    """Generates a Mermaid.js mind map from the current conversation history."""
    if not req.messages or len(req.messages) < 2:
        raise HTTPException(status_code=400, detail="Need at least 2 messages to generate a mind map")

    # Build conversation text from messages
    convo_text = "\n".join(
        f"{'User' if m.get('role') == 'user' else 'Alex'}: {m.get('text', '')}"
        for m in req.messages[-30:]  # Last 30 messages
        if m.get('text') and m.get('role') in ('user', 'assistant')
    )
    if len(convo_text) < 50:
        raise HTTPException(status_code=400, detail="Not enough conversation content to generate a mind map")

    # Truncate for API efficiency
    convo_snippet = convo_text[:5000]

    import google.generativeai as genai
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        try:
            from vault_client import get_secret
            api_key = get_secret("GEMINI_API_KEY")
        except Exception:
            pass
    if not api_key:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")

    prompt = f"""Analyze this conversation between a student and their tutor Alex, and create a Mermaid.js mindmap diagram showing the topics and concepts discussed.
Rules:
- Use the `mindmap` diagram type (radial layout, NOT flowchart)
- The root node should be the main topic with an emoji
- Create 3-6 branches for key themes discussed, each with an emoji prefix
- Each branch should have 2-4 sub-items with short, punchy labels
- Keep labels SHORT (max 5 words), use teen-friendly casual language
- Add emojis to ALL nodes to make it visually scannable
- Output ONLY the raw Mermaid code, no explanation, no code fences
- Example format:
  mindmap
    root((🧬 What We Talked About))
      💡 Key Topics
        🧠 Concept One
        ⚡ Concept Two
      📝 Questions Asked
        🔬 Question about X
        🎯 Question about Y

Conversation:
{convo_snippet}"""

    try:
        response = model.generate_content(prompt)
        mermaid_code = response.text.strip()
        if mermaid_code.startswith("```"):
            mermaid_code = mermaid_code.split("\n", 1)[-1]
        if mermaid_code.endswith("```"):
            mermaid_code = mermaid_code.rsplit("```", 1)[0].strip()
        return JSONResponse({"status": "ok", "mermaid": mermaid_code, "source": "conversation"})
    except Exception as e:
        logger.error(f"Conversation mind map generation error: {e}")
        raise HTTPException(status_code=500, detail=f"Mind map generation failed: {str(e)}")

@app.post("/api/study/conversation-summary")
async def generate_conversation_summary(req: ConversationStudyRequest):
    """Generates a structured summary from the current conversation history."""
    if not req.messages or len(req.messages) < 2:
        raise HTTPException(status_code=400, detail="Need at least 2 messages to generate a summary")

    convo_text = "\n".join(
        f"{'User' if m.get('role') == 'user' else 'Alex'}: {m.get('text', '')}"
        for m in req.messages[-30:]
        if m.get('text') and m.get('role') in ('user', 'assistant')
    )
    if len(convo_text) < 50:
        raise HTTPException(status_code=400, detail="Not enough conversation content to summarize")

    convo_snippet = convo_text[:6000]

    import google.generativeai as genai
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        try:
            from vault_client import get_secret
            api_key = get_secret("GEMINI_API_KEY")
        except Exception:
            pass
    if not api_key:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")

    prompt = f"""Create a structured summary of this conversation between a student and their tutor Alex. Format it as:

## What We Covered
- Bullet points of the main topics discussed

## Key Takeaways
- Important things the student learned or discussed

## Quick Review Questions
- 3-4 questions to test understanding of what was discussed

Keep it concise and student-friendly. Use simple, casual language.

Conversation:
{convo_snippet}"""

    try:
        response = model.generate_content(prompt)
        return JSONResponse({"status": "ok", "summary": response.text.strip(), "source": "conversation"})
    except Exception as e:
        logger.error(f"Conversation summary generation error: {e}")
        raise HTTPException(status_code=500, detail=f"Summary generation failed: {str(e)}")

# ── Audience Validation (inherited from Aether) ─────────────────
import sys
FACTORY_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
if FACTORY_DIR not in sys.path:
    sys.path.insert(0, FACTORY_DIR)

class AudienceDetectRequest(BaseModel):
    text: str

@app.post("/api/audience/detect")
async def audience_detect(req: AudienceDetectRequest):
    """Instant audience intent detection — regex only, no API call."""
    try:
        from Project_Aether.audience_validator import AudienceValidator
        result = AudienceValidator.detect_audience_intent(req.text)
        return JSONResponse(result)
    except Exception as e:
        return JSONResponse({"detected": False, "audience_hint": "", "confidence": 0.0, "error": str(e)})

class AudienceValidateRequest(BaseModel):
    messages: List[dict] = []
    content: str = ""
    profile_id: str = "teen_learner"

class AudienceGenerateRequest(BaseModel):
    audience_description: str
    profile_id: Optional[str] = None
    context: str = ""

@app.get("/api/audience/profiles")
async def list_audience_profiles():
    """List available audience profiles."""
    try:
        from Project_Aether.audience_validator import AudienceValidator
        validator = AudienceValidator()
        return JSONResponse({"profiles": validator.list_profiles()})
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/audience/validate")
async def audience_validate(req: AudienceValidateRequest):
    """Validate conversation or content against an audience profile."""
    try:
        from Project_Aether.audience_validator import AudienceValidator
        validator = AudienceValidator()
        if req.messages:
            result = validator.validate_conversation(req.messages, req.profile_id, app_name="Resonance")
        elif req.content:
            result = validator.validate(req.content, req.profile_id, app_name="Resonance")
        else:
            raise HTTPException(status_code=400, detail="Provide 'messages' or 'content'")
        return JSONResponse(result.to_dict())
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Audience validation error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/audience/generate")
async def audience_generate(req: AudienceGenerateRequest):
    """AI-generate a new audience profile from a description using Deep_Crawler + Gemini."""
    try:
        from Project_Aether.audience_validator import AudienceValidator
        validator = AudienceValidator()
        profile = validator.generate_profile(
            audience_description=req.audience_description,
            profile_id=req.profile_id,
            context=req.context,
        )
        return JSONResponse({
            "status": "ok",
            "profile": {
                "id": profile.id,
                "name": profile.name,
                "age_range": profile.age_range,
                "description": profile.description,
                "interests": profile.interests,
                "tone_keywords": profile.tone_keywords,
                "deal_breakers": profile.deal_breakers,
            },
        })
    except Exception as e:
        logger.error(f"Profile generation error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import argparse
    import uvicorn
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=int(os.environ.get("PORT", 5006)))
    args = parser.parse_args()
    uvicorn.run(app, host="0.0.0.0", port=args.port)
# V3 AUTO-HEAL ACTIVE
