"""
Resonance — FastAPI Backend Server
Generated by Meta App Factory V3
"""

import os, sys, json, logging
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO, format="%(asctime)s [Resonance] %(message)s")
logger = logging.getLogger("Resonance")

app = FastAPI(title="Resonance API", version="3.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:5174", "http://localhost:5175"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Import V3 Streaming Engine ───────────────────────────
try:
    from app_stream import stream_chat, clear_stream_history
    STREAMING = True
    logger.info("V3 Streaming Engine loaded.")
except ImportError:
    STREAMING = False
    logger.warning("Streaming engine not available.")

class ChatRequest(BaseModel):
    prompt: str
    dashboard_context: dict | None = None

@app.get("/")
def root():
    return {"service": "Resonance", "version": "3.0", "streaming": STREAMING}

@app.post("/api/chat/stream")
async def chat_stream(req: ChatRequest):
    if not STREAMING:
        return JSONResponse({"error": "Streaming not available."}, status_code=503)
    if not req.prompt.strip():
        return JSONResponse({"error": "No prompt."}, status_code=400)
    def generate():
        for event in stream_chat(req.prompt, dashboard_context=req.dashboard_context):
            yield f"data: {json.dumps(event)}\n\n"
    return StreamingResponse(generate(), media_type="text/event-stream")

@app.post("/api/chat/clear")
def clear_chat():
    if STREAMING: clear_stream_history()
    return {"status": "ok"}

@app.get("/api/health")
def health():
    return {"status": "healthy", "streaming": STREAMING}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=5006)
