import json
import logging

# Setup Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("ReportingSkill")

class ReportingAgent:
    def __init__(self):
        pass

    def generate_daily_memo(self, decision):
        """
        Generates a narrative 'Morning Briefing' style report.
        """
        import datetime
        now = datetime.datetime.now().strftime("%H:%M ET")
        date_str = datetime.datetime.now().strftime("%Y-%m-%d")
        
        snapshot = decision.get("market_snapshot", {})
        loki = decision.get("loki_proposal", {})
        macro = decision.get("expert_opinions", {}).get("macro", {})
        vol = decision.get("expert_opinions", {}).get("volatility", {})
        sent = decision.get("expert_opinions", {}).get("sentiment", {})
        
        # Macro Section
        risk_bullets = ""
        if macro.get('events'):
            for e in macro['events']:
                impact_icon = "⚠️" if e['impact'] == "HIGH" else "🔹"
                risk_bullets += f"- {impact_icon} **{e['event']}** ({e['days_until']}d away). Strategy: *{e.get('impact', 'Check')} impact*.\n"
        else:
            risk_bullets = "- No major high-impact events in the immediate scanner."

        # Trade Recommendation
        trade_section = "## 🧘 No Trade Recommended\nLoki suggests waiting for better conditions."
        if loki.get('strategy') and loki.get('strategy') != "WAIT":
            trade_section = f"""## 🚀 Trade Opportunity: {loki.get('strategy')}
**Rationale**: {loki.get('rationale')}

### Execution Details
If you decide to take this trade:
- **Bias**: {sent.get('bias', 'Neutral').upper()}
- **Volatility**: {vol.get('signal', 'Unknown')}
"""

        md = f"""# ☕ Alpha Morning Briefing
**Date**: {date_str} | **Time**: {now}

## 🌍 Market Pulse
- **SPX**: {snapshot.get('spx', 0):.2f}
- **VIX**: {snapshot.get('vix', 0):.2f}
- **Trend**: {snapshot.get('trend_5d_pct', 0)}% (5-Day)

## ⚠️ Macro Risk Radar
{risk_bullets}

{trade_section}

---
*Generated by Alpha Architect AI*
"""
        return md

    def generate_markdown_report(self, decision):
        """
        Converts the Loki Decision Dict into a Markdown Report.
        """
        snapshot = decision.get("market_snapshot", {})
        vol = decision.get("expert_opinions", {}).get("volatility", {})
        sent = decision.get("expert_opinions", {}).get("sentiment", {})
        loki = decision.get("loki_proposal", {})
        final_action = decision.get("final_action", "WAIT")
        
        # Emoji Logic (ASCII Fallback)
        action_emoji = "[GO]" if final_action != "WAIT" else "[WAIT]"
        if final_action == "VETO": action_emoji = "[STOP]"
        
        # Watchdog
        wd = decision.get("expert_opinions", {}).get("watchdog", {})
        
        md = f"""
# Alpha Intelligence Report {action_emoji}
**Action**: `{final_action}`
**Strategy**: {loki.get('strategy', 'None')}

---

## 1. Active Position Status
*   **Verdict**: `{wd.get('verdict', 'N/A')}` ({wd.get('status', 'N/A')})
*   **Details**: {wd.get('message', 'No active trade.')}
*   **Distance to Strike**: {wd.get('distance_pct', 0)}%

## 2. Market Forensics
*   **SPX**: {snapshot.get('spx', 'N/A')}
*   **VIX**: {snapshot.get('vix', 'N/A')} (Trend: {snapshot.get('trend_5d_pct', 0)}%)

## 3. Expert Analysis & Forecast
### Volatility (The Quant)
*   **Signal**: `{vol.get('signal', 'N/A')}`
*   **Forecast (Next 24h)**: `{vol.get('forecast', 'UNKNOWN')}`
*   *Rationale*: {vol.get('rationale', 'N/A')}

### Sentiment (The Analyst)
*   **Bias**: {sent.get('bias', 'Neutral')} (Score: {sent.get('score', 0)})
*   *Narrative*: {sent.get('narrative', 'N/A')}

---

## 4. Loki's Command
> {loki.get('rationale', 'N/A')}

"""
        return md

    def print_decision(self, decision):
        report = self.generate_markdown_report(decision)
        print(report)
        return report

if __name__ == "__main__":
    print("... Testing Reporting Agent ...")
    agent = ReportingAgent()
    
    # Mock Decision
    mock_decision = {
        "market_snapshot": {"spx": 7000, "vix": 16.5, "trend_5d_pct": 1.2},
        "expert_opinions": {
            "volatility": {"vix_rank_30d": 75, "signal": "SELL_PREMIUM", "rationale": "Expensive Volatility."},
            "sentiment": {"score": 0.0, "bias": "Neutral", "narrative": "No News."}
        },
        "loki_proposal": {"strategy": "IRON_CONDOR", "rationale": "Range bound market."},
        "final_action": "IRON_CONDOR"
    }
    
    agent.print_decision(mock_decision)
