/**
 * ═══════════════════════════════════════════════════
 *  PROJECT AETHER — MASTER DASHBOARD
 *  Google Apps Script | Auto-Generated by Data Architect
 *  
 *  DEPLOYMENT:
 *  1. Create a new Google Sheet
 *  2. Go to Extensions > Apps Script
 *  3. Paste this entire file into Code.gs
 *  4. Run setupDashboard() to initialize all tabs
 *  5. Set up a time-driven trigger for autoRefresh()
 * ═══════════════════════════════════════════════════
 */

// ── Configuration ──
const CONFIG = {
  sheetName: "Project Aether Master Dashboard",
  refreshInterval: 15, // minutes
  version: "1.0.0",
  colors: {
    headerBg: "#1a1a2e",
    headerText: "#e0e0ff",
    activeBg: "#0d4d0d",
    activeText: "#4cff4c",
    placeholderBg: "#4d4d00",
    placeholderText: "#ffff4c",
    criticalBg: "#4d0d0d",
    criticalText: "#ff4c4c",
    accentBg: "#16213e",
    accentText: "#c8d6e5",
    borderColor: "#2d3436",
    sectionHeader: "#0a3d62",
    sectionText: "#ffffff",
  }
};

// ── Agent Registry (mirrors Aether_System_Map.json) ──
const AGENT_REGISTRY = [
  { name: "CEO", role: "Strategic Lead & Executive Proxy", division: "C-Suite_Core", status: "ACTIVE", model: "Claude Sonnet 4", reports_to: "Executive" },
  { name: "CFO", role: "Fiscal Strategist & Sheets Architect", division: "C-Suite_Core", status: "ACTIVE", model: "Claude Sonnet 4", reports_to: "CEO" },
  { name: "CTO", role: "Lead Systems Architect", division: "C-Suite_Core", status: "ACTIVE", model: "Claude Sonnet 4", reports_to: "CEO" },
  { name: "CMO", role: "Market Strategy & Brand Intelligence", division: "C-Suite_Core", status: "PLACEHOLDER", model: "Gemini 2.0 Flash", reports_to: "CEO" },
  { name: "Deep Crawler", role: "High-Velocity Web Mining", division: "Intelligence_Ops", status: "ACTIVE", model: "Gemini 2.0 Flash", reports_to: "CEO" },
  { name: "The Librarian", role: "Knowledge Guardian & Index Sync", division: "Intelligence_Ops", status: "ACTIVE", model: "Claude Sonnet 4", reports_to: "CEO" },
  { name: "Researcher", role: "Analytical Research & Synthesis", division: "Intelligence_Ops", status: "PLACEHOLDER", model: "Gemini 2.0 Flash", reports_to: "CEO" },
  { name: "The Critic", role: "Professional Skeptic & Quality Auditor", division: "Systems_Audit", status: "ACTIVE", model: "Claude Sonnet 4", reports_to: "CEO" },
  { name: "Compliance Officer", role: "Security, Privacy & Regulatory", division: "Systems_Audit", status: "ACTIVE", model: "Claude Sonnet 4", reports_to: "CEO" },
  { name: "Data Architect", role: "Data Pipeline Design & Schema", division: "Systems_Audit", status: "ACTIVE", model: "Claude Sonnet 4", reports_to: "CEO" },
  { name: "Graphic Designer", role: "Visual Design & Asset Creation", division: "Creative_Studio", status: "PLACEHOLDER", model: "Gemini 2.0 Flash", reports_to: "CEO" },
  { name: "Presentation Expert", role: "Strategic Narrative & Decks", division: "Creative_Studio", status: "PLACEHOLDER", model: "Claude Sonnet 4", reports_to: "CEO" },
  { name: "CX Strategist", role: "Customer Experience Strategy", division: "Creative_Studio", status: "PLACEHOLDER", model: "Gemini 2.0 Flash", reports_to: "CEO" },
];

// ── Project Registry (mirrors MASTER_INDEX.md) ──
const PROJECT_REGISTRY = [
  { name: "Alpha_V2_Genesis", status: "LATEST STABLE", type: "Trading Dashboard", port: 5005, path: "Meta_App_Factory/Alpha_V2_Genesis" },
  { name: "Meta_App_Factory", status: "Active", type: "App Orchestrator", port: 8000, path: "Meta_App_Factory/" },
  { name: "Resonance", status: "Active", type: "Multi-Agent Educational App", port: 5006, path: "Meta_App_Factory/Resonance" },
  { name: "Project Aether", status: "Active — Primary Admin", type: "Agent Infrastructure", port: null, path: "Meta_App_Factory/Project_Aether" },
  { name: "n8n Integration", status: "Active & Synced", type: "Workflow Automation", port: null, path: "Specialist Agents/Integration" },
  { name: "Alpha_Architect", status: "Active on PC #2", type: "Intelligence Architect", port: null, path: "Alpha Architect/" },
  { name: "Alexa 2", status: "Pending Review", type: "Voice Companion", port: null, path: "Alexa 2/" },
  { name: "Loki Formulator", status: "Pending Review", type: "R&D Formulation Engine", port: null, path: "Loki-Master Formulator/" },
  { name: "Project Genesis", status: "Active — Delegate AI Pilot", type: "Legal SaaS Product", port: null, path: "Meta_App_Factory/Project_Aether/Project_Genesis" },
];

// ══════════════════════════════════════════════════
//  MAIN SETUP FUNCTION — Run this first!
// ══════════════════════════════════════════════════

function setupDashboard() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  ss.rename(CONFIG.sheetName);
  
  // Create all tabs
  buildCommandCenter(ss);
  buildFiscalOversight(ss);
  buildProjectIndex(ss);
  buildBoardroomFeed(ss);
  buildSystemHealth(ss);
  buildDelegateAI(ss);
  
  // Remove default Sheet1 if it still exists
  const defaultSheet = ss.getSheetByName("Sheet1");
  if (defaultSheet && ss.getSheets().length > 1) {
    ss.deleteSheet(defaultSheet);
  }
  
  // Set Command Center as active
  ss.setActiveSheet(ss.getSheetByName("⚡ Command Center"));
  
  SpreadsheetApp.getUi().alert(
    "✅ Dashboard Deployed!\n\n" +
    "Tabs created:\n" +
    "• ⚡ Command Center — Agent statuses\n" +
    "• 💰 Fiscal Oversight — Resource tracking\n" +
    "• 📋 Project Index — MASTER_INDEX sync\n" +
    "• 📢 Boardroom Feed — Report log\n" +
    "• 🏥 System Health — Infrastructure status\n" +
    "• 🚀 Product: Delegate_AI — Pilot tracker\n\n" +
    "Run autoRefresh() or set a time trigger for auto-updates."
  );
}

// ══════════════════════════════════════════════════
//  TAB 1: AGENT COMMAND CENTER
// ══════════════════════════════════════════════════

function buildCommandCenter(ss) {
  let sheet = ss.getSheetByName("⚡ Command Center");
  if (!sheet) sheet = ss.insertSheet("⚡ Command Center");
  sheet.clear();
  sheet.setTabColor("#4caf50");
  
  // ── Title Block ──
  sheet.getRange("A1:H1").merge().setValue("⚡ PROJECT AETHER — AGENT COMMAND CENTER")
    .setBackground(CONFIG.colors.headerBg).setFontColor(CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:H2").merge()
    .setValue("Last Refresh: " + new Date().toISOString() + " | v" + CONFIG.version)
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  // ── Summary KPIs ──
  const activeCount = AGENT_REGISTRY.filter(a => a.status === "ACTIVE").length;
  const placeholderCount = AGENT_REGISTRY.filter(a => a.status === "PLACEHOLDER").length;
  
  sheet.getRange("A4").setValue("ACTIVE AGENTS").setFontWeight("bold");
  sheet.getRange("B4").setValue(activeCount).setFontSize(20).setFontWeight("bold")
    .setFontColor(CONFIG.colors.activeText).setBackground(CONFIG.colors.activeBg)
    .setHorizontalAlignment("center");
  
  sheet.getRange("C4").setValue("PLACEHOLDER").setFontWeight("bold");
  sheet.getRange("D4").setValue(placeholderCount).setFontSize(20).setFontWeight("bold")
    .setFontColor(CONFIG.colors.placeholderText).setBackground(CONFIG.colors.placeholderBg)
    .setHorizontalAlignment("center");
    
  sheet.getRange("E4").setValue("TOTAL ROSTER").setFontWeight("bold");
  sheet.getRange("F4").setValue(AGENT_REGISTRY.length).setFontSize(20).setFontWeight("bold")
    .setFontColor("#ffffff").setBackground(CONFIG.colors.sectionHeader)
    .setHorizontalAlignment("center");
  
  // ── Agent Table ──
  const headers = ["Agent", "Role", "Division", "Status", "Model", "Reports To", "Config Version", "Isolation"];
  const headerRange = sheet.getRange(6, 1, 1, headers.length);
  headerRange.setValues([headers])
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  AGENT_REGISTRY.forEach((agent, i) => {
    const row = 7 + i;
    const statusEmoji = agent.status === "ACTIVE" ? "✅" : "🟡";
    sheet.getRange(row, 1).setValue(agent.name).setFontWeight("bold");
    sheet.getRange(row, 2).setValue(agent.role);
    sheet.getRange(row, 3).setValue(agent.division);
    sheet.getRange(row, 4).setValue(statusEmoji + " " + agent.status)
      .setBackground(agent.status === "ACTIVE" ? CONFIG.colors.activeBg : CONFIG.colors.placeholderBg)
      .setFontColor(agent.status === "ACTIVE" ? CONFIG.colors.activeText : CONFIG.colors.placeholderText);
    sheet.getRange(row, 5).setValue(agent.model);
    sheet.getRange(row, 6).setValue(agent.reports_to);
    sheet.getRange(row, 7).setValue(agent.status === "ACTIVE" ? "v2.0.0" : "v1.1.0");
    sheet.getRange(row, 8).setValue("✅ Aether Boundary");
  });
  
  // ── Division Summary ──
  const divRow = 7 + AGENT_REGISTRY.length + 2;
  sheet.getRange(divRow, 1, 1, 4).merge().setValue("DIVISION BREAKDOWN")
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  const divisions = ["C-Suite_Core", "Intelligence_Ops", "Systems_Audit", "Creative_Studio"];
  divisions.forEach((div, i) => {
    const agents = AGENT_REGISTRY.filter(a => a.division === div);
    const active = agents.filter(a => a.status === "ACTIVE").length;
    const r = divRow + 1 + i;
    sheet.getRange(r, 1).setValue(div).setFontWeight("bold");
    sheet.getRange(r, 2).setValue(active + "/" + agents.length + " Active");
    sheet.getRange(r, 3).setValue(agents.map(a => a.name).join(", "));
  });
  
  // ── Formatting ──
  sheet.setColumnWidth(1, 160);
  sheet.setColumnWidth(2, 280);
  sheet.setColumnWidth(3, 150);
  sheet.setColumnWidth(4, 140);
  sheet.setColumnWidth(5, 160);
  sheet.setColumnWidth(6, 120);
  sheet.setColumnWidth(7, 120);
  sheet.setColumnWidth(8, 140);
  sheet.setFrozenRows(6);
}

// ══════════════════════════════════════════════════
//  TAB 2: FISCAL OVERSIGHT (CFO)
// ══════════════════════════════════════════════════

function buildFiscalOversight(ss) {
  let sheet = ss.getSheetByName("💰 Fiscal Oversight");
  if (!sheet) sheet = ss.insertSheet("💰 Fiscal Oversight");
  sheet.clear();
  sheet.setTabColor("#ff9800");
  
  // ── Title ──
  sheet.getRange("A1:G1").merge().setValue("💰 FISCAL OVERSIGHT — CFO DASHBOARD")
    .setBackground(CONFIG.colors.headerBg).setFontColor(CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:G2").merge()
    .setValue("Maintained by: CFO + Data Architect | Last Sync: " + new Date().toISOString())
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  // ── Resource Allocation Table ──
  sheet.getRange("A4:G4").setValues([["Resource Category", "Monthly Cost", "Annual Projection", "Status", "Owner", "ROI Score", "Notes"]])
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const resources = [
    ["n8n Cloud (Pro)", "$20.00", "=B5*12", "Active", "CTO", "HIGH", "Core workflow engine. 28 workflows active."],
    ["Claude Sonnet 4 (API)", "$0.00*", "Variable", "Active", "CEO", "CRITICAL", "* Included in Antigravity plan. Usage-based overage possible."],
    ["Gemini 2.0 Flash (API)", "$0.00*", "Variable", "Active", "Deep Crawler", "HIGH", "* Free tier. Monitor for quota limits."],
    ["Google Drive (Storage)", "$0.00", "$0.00", "Active", "The Librarian", "BASELINE", "Included in Google Workspace. 15GB limit."],
    ["Domain / Hosting", "TBD", "TBD", "Not Active", "CTO", "N/A", "No public deployment yet."],
    ["Sentry (Error Tracking)", "$0.00", "$0.00", "Configured", "Compliance", "MEDIUM", "Free tier. DSN configured."],
  ];
  
  resources.forEach((row, i) => {
    sheet.getRange(5 + i, 1, 1, 7).setValues([row]);
    if (row[3] === "Active") {
      sheet.getRange(5 + i, 4).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText);
    }
  });
  
  // ── Budget Summary ──
  const sumRow = 5 + resources.length + 2;
  sheet.getRange(sumRow, 1, 1, 3).merge().setValue("💡 BUDGET SUMMARY")
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange(sumRow + 1, 1).setValue("Total Fixed Monthly:").setFontWeight("bold");
  sheet.getRange(sumRow + 1, 2).setValue("$20.00").setFontWeight("bold").setFontSize(14);
  sheet.getRange(sumRow + 2, 1).setValue("Total Fixed Annual:").setFontWeight("bold");
  sheet.getRange(sumRow + 2, 2).setValue("$240.00").setFontWeight("bold").setFontSize(14);
  sheet.getRange(sumRow + 3, 1).setValue("Variable Costs:").setFontWeight("bold");
  sheet.getRange(sumRow + 3, 2).setValue("API usage-based (Claude + Gemini)").setFontStyle("italic");
  
  // ── Agent Cost Distribution ──
  const costRow = sumRow + 5;
  sheet.getRange(costRow, 1, 1, 4).merge().setValue("📊 AGENT RESOURCE CONSUMPTION")
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange(costRow + 1, 1, 1, 4).setValues([["Agent", "Model", "Est. Tokens/Month", "Priority"]])
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText).setFontWeight("bold");
  
  const agentCosts = [
    ["CEO", "Claude Sonnet 4", "High (delegation hub)", "P0"],
    ["CFO", "Claude Sonnet 4", "Medium (reports + sheets)", "P1"],
    ["CTO", "Claude Sonnet 4", "High (architecture + code)", "P0"],
    ["The Critic", "Claude Sonnet 4", "Medium (audit reviews)", "P1"],
    ["Deep Crawler", "Gemini 2.0 Flash", "Very High (web mining)", "P0"],
    ["The Librarian", "Claude Sonnet 4", "Low (index sync)", "P2"],
    ["Compliance Officer", "Claude Sonnet 4", "Low (periodic audits)", "P2"],
    ["Data Architect", "Claude Sonnet 4", "Medium (schema + pipeline)", "P1"],
  ];
  
  agentCosts.forEach((row, i) => {
    sheet.getRange(costRow + 2 + i, 1, 1, 4).setValues([row]);
  });
  
  // ── Formatting ──
  sheet.setColumnWidth(1, 200);
  sheet.setColumnWidth(2, 150);
  sheet.setColumnWidth(3, 160);
  sheet.setColumnWidth(4, 100);
  sheet.setColumnWidth(5, 120);
  sheet.setColumnWidth(6, 100);
  sheet.setColumnWidth(7, 350);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  TAB 3: PROJECT INDEX (Librarian)
// ══════════════════════════════════════════════════

function buildProjectIndex(ss) {
  let sheet = ss.getSheetByName("📋 Project Index");
  if (!sheet) sheet = ss.insertSheet("📋 Project Index");
  sheet.clear();
  sheet.setTabColor("#2196f3");
  
  // ── Title ──
  sheet.getRange("A1:F1").merge().setValue("📋 PROJECT INDEX — MASTER_INDEX SYNC")
    .setBackground(CONFIG.colors.headerBg).setFontColor(CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:F2").merge()
    .setValue("Maintained by: The Librarian | Source: MASTER_INDEX.md | Sync: " + new Date().toISOString())
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  // ── Project Table ──
  sheet.getRange("A4:F4").setValues([["Project", "Status", "Type", "Port", "Path", "Last Verified"]])
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  PROJECT_REGISTRY.forEach((proj, i) => {
    const row = 5 + i;
    sheet.getRange(row, 1).setValue(proj.name).setFontWeight("bold");
    sheet.getRange(row, 2).setValue(proj.status);
    sheet.getRange(row, 3).setValue(proj.type);
    sheet.getRange(row, 4).setValue(proj.port || "N/A");
    sheet.getRange(row, 5).setValue(proj.path);
    sheet.getRange(row, 6).setValue(new Date().toISOString().split("T")[0]);
    
    // Color-code by status
    if (proj.status.includes("Active") || proj.status.includes("STABLE")) {
      sheet.getRange(row, 2).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText);
    } else if (proj.status.includes("Pending")) {
      sheet.getRange(row, 2).setBackground(CONFIG.colors.placeholderBg).setFontColor(CONFIG.colors.placeholderText);
    }
  });
  
  // ── Aether Infrastructure ──
  const infraRow = 5 + PROJECT_REGISTRY.length + 2;
  sheet.getRange(infraRow, 1, 1, 4).merge().setValue("🏗️ AETHER INFRASTRUCTURE COMPONENTS")
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  const infra = [
    ["C-Suite Active Logic", "13 agent configs", "Active", "Project_Aether/C-Suite_Active_Logic/"],
    ["Boardroom Exchange", "5 reports filed", "Active", "Project_Aether/Boardroom_Exchange/"],
    ["Ingestion Chamber", "Active Watcher (watcher.py)", "Active", "Project_Aether/Ingestion_Chamber/"],
    ["Compliance Vault", "Active Watcher (vault_engine.py)", "Active", "Project_Aether/Compliance_Vault/"],
    ["Aether System Map", "5-stage pipeline schema", "Initialized", "Project_Aether/Aether_System_Map.json"],
  ];
  
  sheet.getRange(infraRow + 1, 1, 1, 4).setValues([["Component", "Description", "Status", "Path"]])
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText).setFontWeight("bold");
  
  infra.forEach((row, i) => {
    sheet.getRange(infraRow + 2 + i, 1, 1, 4).setValues([row]);
  });
  
  sheet.setColumnWidth(1, 200);
  sheet.setColumnWidth(2, 200);
  sheet.setColumnWidth(3, 180);
  sheet.setColumnWidth(4, 100);
  sheet.setColumnWidth(5, 300);
  sheet.setColumnWidth(6, 140);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  TAB 4: BOARDROOM FEED
// ══════════════════════════════════════════════════

function buildBoardroomFeed(ss) {
  let sheet = ss.getSheetByName("📢 Boardroom Feed");
  if (!sheet) sheet = ss.insertSheet("📢 Boardroom Feed");
  sheet.clear();
  sheet.setTabColor("#9c27b0");
  
  // ── Title ──
  sheet.getRange("A1:F1").merge().setValue("📢 BOARDROOM FEED — INTER-AGENT REPORTS")
    .setBackground(CONFIG.colors.headerBg).setFontColor(CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:F2").merge()
    .setValue("Source: Project_Aether/Boardroom_Exchange/ | Sync: " + new Date().toISOString())
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  // ── Report Log ──
  sheet.getRange("A4:F4").setValues([["Report", "Filed By", "Type", "Verdict", "Date", "Key Finding"]])
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const reports = [
    ["STATE_OF_THE_UNION.md", "CEO", "Inaugural Audit", "Published", "2026-03-07", "Infrastructure deployed, gaps identified"],
    ["CRITIC_VERDICT_SOTU_v1.md", "The Critic", "Formal Audit", "⚠️ REVISE", "2026-03-07", "No runtime execution layer (CRITICAL blind spot)"],
    ["CEO_REBUTTAL_SOTU_v1.md", "CEO", "Rebuttal", "ACCEPTED w/ Amendments", "2026-03-07", "CTO activation approved, revised priority matrix"],
    ["COMPLIANCE_AUDIT_CRED_v1.md", "Compliance Officer", "Security Sweep", "✅ REMEDIATED", "2026-03-07", "JWT removed from factory.py + registry.py → .env"],
    ["AETHER_RUNTIME_BLUEPRINT.md", "CTO", "Technical Blueprint", "✅ BUILT", "2026-03-07", "aether_runtime.py deployed (Phase 1-2)"],
    ["COMPLIANCE_CLEARANCE_v1.md", "Compliance Officer", "Clearance", "✅ CLEARED", "2026-03-07", "Deployment block lifted"],
    ["DEEP_CRAWLER_GENESIS_SCAN.md", "Deep Crawler", "Sector Scan", "✅ VALIDATED", "2026-03-07", "7 friction zones, L1 Legal = primary target"],
    ["CRITIC_GENESIS_VALIDATION.md", "The Critic", "Validation", "✅ APPROVED", "2026-03-07", "L1 + S1 approved, 5 deferred"],
    ["CFO_PILOT_AGENT_BUDGET.md", "CFO", "Budget Proposal", "✅ APPROVED", "2026-03-07", "$1.4K-$2.7K pilot → $62K target ARR"],
    ["DELEGATE_AI_TECH_STACK.md", "CTO", "Architecture", "✅ FILED", "2026-03-07", "10-day MVP via Aether Runtime + Supabase"],
    ["PRIVACY_SHIELD_REPORT.md", "Compliance Officer", "Privacy Audit", "✅ CLEARED", "2026-03-07", "5-layer privilege safeguards, pilot approved"],
    ["BETA_FIRM_TARGET_LIST.md", "CEO + CMO", "Market Outreach", "✅ FILED", "2026-03-07", "10 beta firms, 3-phase outreach plan"],
    ["COMPLIANCE_CLEARANCE_v2.md", "Compliance Officer", "Universal Clearance", "✅ CLEARED", "2026-03-07", "All remediations confirmed, 10 creds secured"],
    ["AETHER_DASHBOARD_LINK.md", "Data Architect", "Dashboard", "Published", "2026-03-07", "Master Dashboard deploy guide"],
  ];
  
  reports.forEach((row, i) => {
    const r = 5 + i;
    sheet.getRange(r, 1, 1, 6).setValues([row]);
    sheet.getRange(r, 1).setFontWeight("bold");
    
    if (row[3].includes("BLOCKED")) {
      sheet.getRange(r, 4).setBackground(CONFIG.colors.criticalBg).setFontColor(CONFIG.colors.criticalText);
    } else if (row[3].includes("REVISE")) {
      sheet.getRange(r, 4).setBackground(CONFIG.colors.placeholderBg).setFontColor(CONFIG.colors.placeholderText);
    } else if (row[3] === "Published" || row[3].includes("ACCEPTED")) {
      sheet.getRange(r, 4).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText);
    }
  });
  
  sheet.setColumnWidth(1, 280);
  sheet.setColumnWidth(2, 150);
  sheet.setColumnWidth(3, 160);
  sheet.setColumnWidth(4, 200);
  sheet.setColumnWidth(5, 120);
  sheet.setColumnWidth(6, 350);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  TAB 5: SYSTEM HEALTH
// ══════════════════════════════════════════════════

function buildSystemHealth(ss) {
  let sheet = ss.getSheetByName("🏥 System Health");
  if (!sheet) sheet = ss.insertSheet("🏥 System Health");
  sheet.clear();
  sheet.setTabColor("#f44336");
  
  // ── Title ──
  sheet.getRange("A1:E1").merge().setValue("🏥 SYSTEM HEALTH — INFRASTRUCTURE MONITOR")
    .setBackground(CONFIG.colors.headerBg).setFontColor(CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:E2").merge()
    .setValue("Sync: " + new Date().toISOString())
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  // ── Service Status ──
  sheet.getRange("A4:E4").setValues([["Service", "Endpoint", "Status", "Last Check", "Notes"]])
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const services = [
    ["n8n Cloud", "humanresource.app.n8n.cloud", "✅ Connected", new Date().toISOString(), "28 workflows, ANTIGRAVITY_INVENTORY active"],
    ["Meta_App_Factory API", "localhost:8000", "⏸️ Not Running", "—", "Start with Launch_Meta_App_Factory_V3.bat"],
    ["Resonance", "localhost:5006", "⏸️ Not Running", "—", "Start with Launch_Resonance_V3.bat"],
    ["Alpha_V2_Genesis", "localhost:5005", "⏸️ Not Running", "—", "Trading dashboard"],
    ["Google Drive Sync", "Multi-PC", "✅ Active", new Date().toISOString(), "SYNC_TEST + PC2_CONNECTED verified"],
    ["Sentry (Debug)", "sentry.io", "✅ Configured", "—", "DSN present in registry"],
    ["Aether Runtime", "localhost:8001*", "✅ Active", new Date().toISOString(), "v1.0.0 — ConfigLoader + Router + CriticGate + BoardroomLogger"],
  ];
  
  services.forEach((row, i) => {
    const r = 5 + i;
    sheet.getRange(r, 1, 1, 5).setValues([row]);
    if (row[2].includes("✅")) {
      sheet.getRange(r, 3).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText);
    } else if (row[2].includes("🔴")) {
      sheet.getRange(r, 3).setBackground(CONFIG.colors.criticalBg).setFontColor(CONFIG.colors.criticalText);
    } else {
      sheet.getRange(r, 3).setBackground(CONFIG.colors.placeholderBg).setFontColor(CONFIG.colors.placeholderText);
    }
  });
  
  // ── Security Status ──
  const secRow = 5 + services.length + 2;
  sheet.getRange(secRow, 1, 1, 4).merge().setValue("🔒 SECURITY STATUS")
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  const security = [
    ["Credential Exposure", "✅ REMEDIATED", "Compliance Officer", "JWT moved to .env — CLEARED"],
    ["Isolation Boundary", "✅ Enforced", "All agents", "forbidden_references verified"],
    ["Vault Encryption", "✅ Fernet AES-128", "Compliance Officer", "Chain-hashed audit trail active"],
    ["Aether Runtime", "✅ Phase 1-2 Built", "CTO", "Config Loader + Router + Critic Gate"],
    ["Webhook Auth", "🟡 Unauthenticated", "CTO", "P1: Add bearer tokens"],
    ["Config Versioning", "🟡 Not Implemented", "Data Architect", "P1: Git-based versioning needed"],
  ];
  
  sheet.getRange(secRow + 1, 1, 1, 4).setValues([["Item", "Status", "Owner", "Notes"]])
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText).setFontWeight("bold");
  
  security.forEach((row, i) => {
    sheet.getRange(secRow + 2 + i, 1, 1, 4).setValues([row]);
  });
  
  sheet.setColumnWidth(1, 200);
  sheet.setColumnWidth(2, 280);
  sheet.setColumnWidth(3, 140);
  sheet.setColumnWidth(4, 140);
  sheet.setColumnWidth(5, 350);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  AUTO-REFRESH (set as time-driven trigger)
// ══════════════════════════════════════════════════

function autoRefresh() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  buildCommandCenter(ss);
  buildFiscalOversight(ss);
  buildProjectIndex(ss);
  buildBoardroomFeed(ss);
  buildSystemHealth(ss);
  buildDelegateAI(ss);
}

// ══════════════════════════════════════════════════
//  TAB 6: PRODUCT — DELEGATE AI Tracker
// ══════════════════════════════════════════════════

function buildDelegateAI(ss) {
  // Remove old tab name if it exists
  const oldSheet = ss.getSheetByName("🎯 Mission Genesis");
  if (oldSheet) ss.deleteSheet(oldSheet);
  
  let sheet = ss.getSheetByName("🚀 Product: Delegate_AI");
  if (!sheet) sheet = ss.insertSheet("🚀 Product: Delegate_AI");
  sheet.clear();
  sheet.setTabColor("#e91e63");
  
  // ── Title ──
  sheet.getRange("A1:H1").merge().setValue("🚀 PRODUCT: DELEGATE AI — PILOT TRACKER")
    .setBackground(CONFIG.colors.headerBg).setFontColor(CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:H2").merge()
    .setValue("Product Lead: CTO | Compliance: CLEARED | Budget: APPROVED | " + new Date().toISOString())
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  // ── Opportunity Matrix ──
  sheet.getRange("A4:H4").setValues([["Rank", "Friction Zone", "Sector", "Severity", "Market Size", "Build Complexity", "Critic Score", "Status"]])
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const opportunities = [
    ["1", "Legal Task Delegation", "Legal", "🔴 CRITICAL", "440K+ firms", "LOW", "8.4/10", "✅ PRIMARY TARGET"],
    ["2", "CI/CD Pipeline Triage", "Software", "🔴 CRITICAL", "$40B market", "MEDIUM", "8.1/10", "✅ SECONDARY TARGET"],
    ["3", "Contract Analysis", "Legal", "🔴 CRITICAL", "$15B market", "HIGH", "6.2/10", "❌ Deferred (complexity)"],
    ["4", "Integration Watch", "Software", "🟡 HIGH", "$30B market", "LOW", "7.0/10", "🟡 Promising, deferred"],
    ["5", "PR Triage", "Software", "🟡 HIGH", "27M devs", "MEDIUM", "5.8/10", "❌ Saturated market"],
    ["6", "Compliance Watch", "Legal", "🟡 HIGH", "$8B market", "MEDIUM", "6.5/10", "🟡 Niche, deferred"],
    ["7", "Doc Sync", "Software", "🟡 HIGH", "$12B market", "LOW", "5.5/10", "❌ Feature, not product"],
  ];
  
  opportunities.forEach((row, i) => {
    const r = 5 + i;
    sheet.getRange(r, 1, 1, 8).setValues([row]);
    sheet.getRange(r, 2).setFontWeight("bold");
    
    if (row[7].includes("PRIMARY")) {
      sheet.getRange(r, 8).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText);
      sheet.getRange(r, 1, 1, 8).setBackground("#0a2e0a");
    } else if (row[7].includes("SECONDARY")) {
      sheet.getRange(r, 8).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText);
    } else if (row[7].includes("Deferred") || row[7].includes("Saturated") || row[7].includes("Feature")) {
      sheet.getRange(r, 8).setBackground(CONFIG.colors.criticalBg).setFontColor(CONFIG.colors.criticalText);
    } else {
      sheet.getRange(r, 8).setBackground(CONFIG.colors.placeholderBg).setFontColor(CONFIG.colors.placeholderText);
    }
  });
  
  // ── Pilot Agent: Delegate AI ──
  const pilotRow = 5 + opportunities.length + 2;
  sheet.getRange(pilotRow, 1, 1, 6).merge().setValue("🚀 PILOT AGENT: DELEGATE AI — Legal Task Delegation")
    .setBackground("#1b5e20").setFontColor("#ffffff")
    .setFontSize(14).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange(pilotRow + 1, 1, 1, 4).setValues([["Metric", "Conservative", "Target", "Optimistic"]])
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText).setFontWeight("bold");
  
  const projections = [
    ["Beta Firms", "5", "15", "30"],
    ["Total Seats", "25", "75", "200"],
    ["Price/Seat/Mo", "$49", "$69", "$99"],
    ["Monthly Recurring Revenue", "$1,225", "$5,175", "$19,800"],
    ["Annual Recurring Revenue", "$14,700", "$62,100", "$237,600"],
    ["Pilot Investment", "$1,447", "—", "$2,725"],
    ["Break-Even", "Month 6", "Month 4", "Month 4"],
    ["Year 1 ROI", "915%", "2,178%", "8,617%"],
  ];
  
  projections.forEach((row, i) => {
    const r = pilotRow + 2 + i;
    sheet.getRange(r, 1, 1, 4).setValues([row]);
    sheet.getRange(r, 1).setFontWeight("bold");
    if (row[0] === "Annual Recurring Revenue") {
      sheet.getRange(r, 1, 1, 4).setFontSize(12).setFontWeight("bold");
      sheet.getRange(r, 3).setFontColor(CONFIG.colors.activeText);
    }
    if (row[0] === "Year 1 ROI") {
      sheet.getRange(r, 1, 1, 4).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText).setFontWeight("bold");
    }
  });
  
  // ── Pipeline Status ──
  const pipeRow = pilotRow + 2 + projections.length + 2;
  sheet.getRange(pipeRow, 1, 1, 4).merge().setValue("📋 PILOT PIPELINE STATUS")
    .setBackground(CONFIG.colors.sectionHeader).setFontColor(CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  const pipeline = [
    ["Deep Crawler Scan", "✅ Complete", "Deep Crawler", "7 friction zones mapped"],
    ["Critic Validation", "✅ Complete", "The Critic", "L1 + S1 approved"],
    ["CFO Budget", "✅ Approved", "CFO", "$1.4K-$2.7K allocated"],
    ["CTO Architecture Brief", "⏳ Pending", "CTO", "Due within 48 hours"],
    ["Compliance Data Review", "⏳ Pending", "Compliance Officer", "Attorney-client privilege check"],
    ["Pilot Build", "🔲 Not Started", "CTO + Data Architect", "Awaiting architecture brief"],
    ["Beta Firm Outreach", "🔲 Not Started", "CEO + CMO", "5-10 firms targeted"],
  ];
  
  sheet.getRange(pipeRow + 1, 1, 1, 4).setValues([["Phase", "Status", "Owner", "Notes"]])
    .setBackground(CONFIG.colors.accentBg).setFontColor(CONFIG.colors.accentText).setFontWeight("bold");
  
  pipeline.forEach((row, i) => {
    const r = pipeRow + 2 + i;
    sheet.getRange(r, 1, 1, 4).setValues([row]);
    if (row[1].includes("✅")) {
      sheet.getRange(r, 2).setBackground(CONFIG.colors.activeBg).setFontColor(CONFIG.colors.activeText);
    } else if (row[1].includes("⏳")) {
      sheet.getRange(r, 2).setBackground(CONFIG.colors.placeholderBg).setFontColor(CONFIG.colors.placeholderText);
    }
  });
  
  // ── Formatting ──
  sheet.setColumnWidth(1, 200);
  sheet.setColumnWidth(2, 200);
  sheet.setColumnWidth(3, 140);
  sheet.setColumnWidth(4, 140);
  sheet.setColumnWidth(5, 140);
  sheet.setColumnWidth(6, 140);
  sheet.setColumnWidth(7, 120);
  sheet.setColumnWidth(8, 200);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  CUSTOM MENU
// ══════════════════════════════════════════════════

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu("🔄 Aether Controls")
    .addItem("Refresh All Tabs", "autoRefresh")
    .addItem("Rebuild Dashboard", "setupDashboard")
    .addSeparator()
    .addItem("About", "showAbout")
    .addToUi();
}

function showAbout() {
  SpreadsheetApp.getUi().alert(
    "Project Aether Master Dashboard\n" +
    "Version: " + CONFIG.version + "\n" +
    "Built by: Data Architect + CFO\n" +
    "Synced with: Aether_System_Map.json + MASTER_INDEX.md\n\n" +
    "For support, contact the CEO via Boardroom_Exchange."
  );
}
