"""
app_generator.py — V3.0 Hardened Agent Scaffolder
══════════════════════════════════════════════════
Automates creation of new agents that inherit the full V3.0
resilience architecture: safe_post, StateManager, Watchdog
preflight, and Antigravity_Full_v2 key (via factory .env).

Usage:
    python app_generator.py my_new_agent
    python app_generator.py my_new_agent --no-test

Part of System Hardening V3.0 — Meta_App_Factory.
"""

import os
import sys
import argparse
import subprocess
import textwrap
from datetime import datetime

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

FACTORY_DIR = os.path.dirname(os.path.abspath(__file__))
AGENTS_DIR = os.path.join(FACTORY_DIR, "agents")
TEMPLATE = os.path.join(FACTORY_DIR, "child_app_template.py")


def generate_main_py(project_name: str) -> str:
    """Generate main.py by cloning child_app_template.py with project-specific edits."""
    # Read the canonical template
    with open(TEMPLATE, "r", encoding="utf-8") as f:
        content = f.read()

    # Replace the template's module docstring
    content = content.replace(
        "child_app_template.py — V3.0 Resilience-Inherited Child App Template",
        f"{project_name} — V3.0 Hardened Agent"
    )

    # Replace placeholder project name references
    content = content.replace(
        'project="ChildApp_Example"',
        f'project="{project_name}"'
    )
    content = content.replace(
        '"agent": "child_app_template"',
        f'"agent": "{project_name}"'
    )

    # Fix FACTORY_DIR: agents live in agents/{name}/, so go up 2 levels
    content = content.replace(
        'FACTORY_DIR = os.path.dirname(os.path.abspath(__file__))',
        'FACTORY_DIR = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))'
    )

    # Replace the execute() body with a TODO placeholder
    old_body = '''    # ── Step 2: Build your payload ───────────────────────
    # Replace this with your actual data / AI output.
    target_url = "https://humanresource.app.n8n.cloud/webhook/YOUR-WEBHOOK-PATH"
    payload = {
        "agent": "%s",
        "action": "example_action",
        "data": {
            "message": "Hello from a V3.0 Hardened child app",
            "timestamp": __import__('datetime').datetime.now().isoformat(),
        }
    }

    # ── Step 3: Safe-Post (the V3 pattern) ───────────────
    # Logic: Log to StateStore -> Attempt Post -> Mark Result
    status = safe_post(target_url, payload, project="%s")

    if status == "sent":
        print("  ✅ Payload delivered to n8n Cloud.")
    elif status == "buffered":
        print("  ⚠️ Cloud lag detected. Data secured in local_pending_sync.json")
        print("     Recovery Sync Engine will deliver when cloud recovers.")
    elif status == "failed":
        print("  ❌ n8n returned a server error (5xx).")
        print("     Entry logged — run `python recovery_sync.py --force` to retry.")

    # ── Step 4: Check State ──────────────────────────────
    stats = sm.get_stats()
    print(f"\\n  State: {stats['sent']} sent, {stats['pending']} pending, "
          f"{stats['failed']} failed, buffer={'ON' if stats['safe_buffer_mode'] else 'OFF'}")''' % (project_name, project_name)

    new_body = '''    # ──────────────────────────────────────────────────────
    # TODO: IMPLEMENT LOGIC HERE
    #
    # Use safe_post() to send data to n8n Cloud:
    #
    #   target_url = "https://humanresource.app.n8n.cloud/webhook/YOUR-PATH"
    #   payload = {"action": "your_action", "data": {...}}
    #   status = safe_post(target_url, payload, project="%s")
    #
    #   if status == "sent":
    #       print("✅ Delivered")
    #   elif status == "buffered":
    #       print("⚠️ Cloud lag — data secured locally")
    #   elif status == "failed":
    #       print("❌ Server error — will retry via recovery_sync.py")
    #
    # ──────────────────────────────────────────────────────

    print(f"  %s: No logic implemented yet.")
    print(f"  Edit execute() to add your workflow.")''' % (project_name, project_name)

    content = content.replace(old_body, new_body)

    # Update the banner
    content = content.replace(
        "V3.0 Hardened Child App — Template",
        f"{project_name} — V3.0 Hardened Agent"
    )

    # Add generation timestamp
    gen_line = f"# Auto-generated by app_generator.py on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
    content = gen_line + content

    return content


def create_agent(project_name: str, run_test: bool = True):
    """Scaffold a new V3.0 hardened agent."""
    print(f"\n{'='*60}")
    print(f"  🏗️ App Generator — V3.0 Hardened")
    print(f"{'='*60}\n")

    # Validate name
    safe_name = project_name.replace(" ", "_").replace("-", "_")
    agent_dir = os.path.join(AGENTS_DIR, safe_name)

    # Step 1: Create directory
    if os.path.exists(agent_dir):
        print(f"  ⚠️ Directory already exists: agents/{safe_name}/")
        print(f"  Use a different name or delete the existing directory.")
        return False

    os.makedirs(agent_dir, exist_ok=True)
    print(f"  📁 Created: agents/{safe_name}/")

    # Step 2: Generate main.py from template
    main_py = os.path.join(agent_dir, "main.py")
    content = generate_main_py(safe_name)
    with open(main_py, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  📄 Generated: agents/{safe_name}/main.py")

    # Step 3: Create __init__.py for package imports
    init_py = os.path.join(agent_dir, "__init__.py")
    with open(init_py, "w", encoding="utf-8") as f:
        f.write(f'"""{safe_name} — V3.0 Hardened Agent"""\n')
    print(f"  📄 Created:   agents/{safe_name}/__init__.py")

    # Step 4: Verify factory linkage
    factory_py = os.path.join(FACTORY_DIR, "factory.py")
    env_file = os.path.join(FACTORY_DIR, ".env")
    resilience = os.path.join(FACTORY_DIR, "resilience_config.json")

    links = [
        ("factory.py", os.path.exists(factory_py)),
        (".env (Antigravity_Full_v2)", os.path.exists(env_file)),
        ("resilience_config.json", os.path.exists(resilience)),
        ("local_state_manager.py", os.path.exists(os.path.join(FACTORY_DIR, "local_state_manager.py"))),
    ]

    print(f"\n  Infrastructure Links:")
    all_ok = True
    for name, found in links:
        icon = "✅" if found else "❌"
        print(f"    {icon} {name}")
        if not found:
            all_ok = False

    if not all_ok:
        print(f"\n  ⚠️ Some infrastructure files are missing. The agent may not function correctly.")

    # Step 5: Preflight validation
    if run_test:
        print(f"\n  Running preflight validation...")
        try:
            result = subprocess.run(
                [sys.executable, main_py],
                capture_output=True, text=True,
                encoding="utf-8", errors="replace",
                timeout=15, cwd=agent_dir,
            )
            output = result.stdout.strip()
            if output:
                for line in output.split("\n"):
                    print(f"    {line}")

            if result.returncode == 0:
                print(f"\n  ✅ Preflight PASSED — {safe_name} can see the Watchdog")
            else:
                print(f"\n  ⚠️ Preflight returned exit code {result.returncode}")
                if result.stderr:
                    for line in result.stderr.strip().split("\n")[-3:]:
                        print(f"    {line}")
        except subprocess.TimeoutExpired:
            print(f"  ⚠️ Preflight timed out (15s)")
        except Exception as e:
            print(f"  ⚠️ Preflight error: {e}")

    # Summary
    print(f"\n{'='*60}")
    print(f"  ✅ Agent '{safe_name}' is READY")
    print(f"     Path:  agents/{safe_name}/main.py")
    print(f"     Run:   python agents/{safe_name}/main.py")
    print(f"     Edit:  Implement execute() with safe_post()")
    print(f"{'='*60}\n")
    return True


# ── Entry Point ─────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="V3.0 Hardened Agent Generator",
        epilog="Example: python app_generator.py my_new_agent"
    )
    parser.add_argument("project_name", help="Name for the new agent (e.g., my_new_agent)")
    parser.add_argument("--no-test", action="store_true",
                        help="Skip preflight validation after creation")
    args = parser.parse_args()

    create_agent(args.project_name, run_test=not args.no_test)
