@echo off
title Meta App Factory Web UI

echo Starting Antigravity Executor (AY2 Daemon)...
start "AY2 Watchdog" /min cmd /k "cd /d %~dp0 && python alpha_orchestrator.py --daemon"

echo Starting Master Architect Elite Logic (Port 5050)...
start "Master Architect" /min cmd /k "cd /d %~dp0Master_Architect_Elite_Logic && python server.py"

echo Starting Phantom QA Elite (Port 5030)...
start "Phantom QA" /min cmd /k "cd /d %~dp0Phantom_QA_Elite\backend && python server.py"

echo Starting Backend API (api.py - Port 5000)...
start "MAF Backend" cmd /k "cd /d %~dp0 && python api.py"

echo Starting CMO Agent (Port 5020)...
start "CMO Agent" /min cmd /k "cd /d %~dp0Project_Aether\C-Suite_Active_Logic\CMO\backend && python server.py"

echo Starting Sentinel Bridge (Port 5009)...
start "Sentinel Bridge" /min cmd /k "cd /d %~dp0Sentinel_Bridge && python sentinel_server.py"

echo Starting CLO Agent (Port 5080)...
start "CLO Agent" /min cmd /k "cd /d %~dp0apps\CLO_Agent && python server.py"

echo Starting CIO Agent (Port 5090)...
start "CIO Agent" /min cmd /k "cd /d %~dp0CIO_Agent && python server.py"

echo Starting Operator Agent (Port 5100)...
start "Operator Agent" /min cmd /k "cd /d %~dp0 && python operator_agent.py"

echo Starting Vite Frontend (Port 5173)...
start "MAF Frontend" cmd /k "cd /d %~dp0factory_ui && npm run dev"

echo Waiting for synchronized matrix initialization...
timeout /t 10 >nul

echo Opening browser...
start http://localhost:5173

echo Starting Claude MCP Bridge (Telemetry Server)...
start "Claude MCP Bridge" /min cmd /k "cd /d %~dp0 && python claude-mcp-bridge/mcp_server/server.py"

echo Opening VS Code with Antigravity...
start "" "code" "%~dp0"

echo Opening Claude Code (Architect Terminal)...
start "Claude Code" cmd /k "cd /d %~dp0 && claude.cmd"
start "MAF Loop Engine" cmd /k "cd /d %~dp0 && python claude-mcp-bridge/loop_ui.py"

