@echo off
title Meta App Factory Web UI

echo Starting Antigravity Executor (AY2 Daemon)...
start "AY2 Watchdog" /min cmd /k "cd /d %~dp0 && python alpha_orchestrator.py --daemon"

echo Starting Master Architect Elite Logic (Port 5050)...
start "Master Architect" /min cmd /k "cd /d %~dp0Master_Architect_Elite_Logic && python server.py"

echo Starting Phantom QA Elite (Port 5030)...
start "Phantom QA" /min cmd /k "cd /d %~dp0Phantom_QA_Elite\backend && python server.py"

echo Starting Backend API (api.py - Port 5000)...
start "MAF Backend" cmd /k "cd /d %~dp0 && python api.py"

echo Starting CMO Agent (Port 5020)...
start "CMO Agent" /min cmd /k "cd /d %~dp0Project_Aether\C-Suite_Active_Logic\CMO\backend && python server.py"

echo Starting Vite Frontend (Port 5173)...
start "MAF Frontend" cmd /k "cd /d %~dp0factory_ui && npm run dev"

echo Waiting for synchronized matrix initialization...
timeout /t 10 >nul

echo Opening browser...
start http://localhost:5173
