"""
ui_designer.py — V3 Web App Generator
═══════════════════════════════════════
Generates React/Vite + FastAPI apps with V3 Streaming Engine pre-installed.
Tkinter generation has been DEPRECATED as of V3.0.
"""

import os
import json


class UIDesigner:
    """
    The UI Designer Agent (V3 — Web-First).
    Generates a React/Vite frontend + FastAPI backend for every new app.
    Deprecated: Tkinter (V1/V2).
    """

    def __init__(self):
        self._factory_dir = os.path.dirname(os.path.abspath(__file__))

    def build_ui(self, app_path, app_name):
        """Generates a full React/Vite + FastAPI web app scaffold."""
        print(f"--- Designer V3: Building Web App for '{app_name}' ---", flush=True)

        # Create directory structure
        ui_dir = os.path.join(app_path, f"{app_name.lower()}_ui")
        src_dir = os.path.join(ui_dir, "src")
        public_dir = os.path.join(ui_dir, "public")
        os.makedirs(src_dir, exist_ok=True)
        os.makedirs(public_dir, exist_ok=True)

        # ── 1. BACKEND: server.py ─────────────────────────────
        self._write_backend(app_path, app_name)

        # ── 2. BACKEND: app_stream.py (V3 SSE bridge) ─────────
        self._write_stream_bridge(app_path, app_name)

        # ── 3. FRONTEND: package.json ─────────────────────────
        self._write_package_json(ui_dir, app_name)

        # ── 4. FRONTEND: vite.config.js ───────────────────────
        self._write_vite_config(ui_dir)

        # ── 5. FRONTEND: index.html ──────────────────────────
        self._write_index_html(ui_dir, app_name)

        # ── 6. FRONTEND: src/main.jsx ────────────────────────
        self._write_main_jsx(src_dir)

        # ── 7. FRONTEND: src/App.jsx ─────────────────────────
        self._write_app_jsx(src_dir, app_name)

        # ── 8. FRONTEND: src/index.css ───────────────────────
        self._write_index_css(src_dir)

        # ── 9. Requirements ──────────────────────────────────
        self._write_requirements(app_path)

        # ── 10. .gitignore ───────────────────────────────────
        self._write_gitignore(app_path)

        print(f"--- Designer V3: Web App scaffold created in {app_path} ---", flush=True)
        print(f"    Frontend: cd {app_name.lower()}_ui && npm install && npm run dev", flush=True)
        print(f"    Backend:  python server.py", flush=True)

    # ── BACKEND GENERATORS ──────────────────────────────────────

    def _write_backend(self, app_path, app_name):
        code = f'''"""
{app_name} — FastAPI Backend Server
Generated by Meta App Factory V3
"""

import os, sys, json, logging
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO, format="%(asctime)s [{app_name}] %(message)s")
logger = logging.getLogger("{app_name}")

app = FastAPI(title="{app_name} API", version="3.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:5174"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Import V3 Streaming Engine ───────────────────────────
try:
    from app_stream import stream_chat, clear_stream_history
    STREAMING = True
    logger.info("V3 Streaming Engine loaded.")
except ImportError:
    STREAMING = False
    logger.warning("Streaming engine not available.")

class ChatRequest(BaseModel):
    prompt: str
    dashboard_context: dict | None = None

@app.get("/")
def root():
    return {{"service": "{app_name}", "version": "3.0", "streaming": STREAMING}}

@app.post("/api/chat/stream")
async def chat_stream(req: ChatRequest):
    if not STREAMING:
        return JSONResponse({{"error": "Streaming not available."}}, status_code=503)
    if not req.prompt.strip():
        return JSONResponse({{"error": "No prompt."}}, status_code=400)
    def generate():
        for event in stream_chat(req.prompt, dashboard_context=req.dashboard_context):
            yield f"data: {{json.dumps(event)}}\\n\\n"
    return StreamingResponse(generate(), media_type="text/event-stream")

@app.post("/api/chat/clear")
def clear_chat():
    if STREAMING: clear_stream_history()
    return {{"status": "ok"}}

@app.get("/api/health")
def health():
    return {{"status": "healthy", "streaming": STREAMING}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=5005)
'''
        with open(os.path.join(app_path, "server.py"), "w", encoding="utf-8") as f:
            f.write(code)

    def _write_stream_bridge(self, app_path, app_name):
        code = f'''"""
app_stream.py — V3 SSE Streaming Bridge for {app_name}
Generated by Meta App Factory V3
"""

import os, sys, json, logging, requests

logger = logging.getLogger("{app_name}Stream")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

# Vault
_core = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
for vp in [os.path.join(SCRIPT_DIR, "..", "Alpha_V2_Genesis"), _core]:
    vc = os.path.join(vp, "vault_client.py")
    if os.path.exists(vc):
        sys.path.insert(0, vp)
        break

try:
    from vault_client import get_secret
except ImportError:
    def get_secret(key, default="", **kw):
        return os.getenv(key, default)

# LangSmith
_lsk = get_secret("LANGCHAIN_API_KEY")
if _lsk:
    os.environ["LANGCHAIN_API_KEY"] = _lsk
    os.environ["LANGCHAIN_TRACING_V2"] = "true"
    os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
    os.environ["LANGCHAIN_PROJECT"] = "{app_name}"

# History
_HIST_DIR = os.path.join(SCRIPT_DIR, ".Gemini_state")
_HIST_FILE = os.path.join(_HIST_DIR, ".stream_history.json")

def _load_history(n=6):
    try:
        if os.path.exists(_HIST_FILE):
            with open(_HIST_FILE, "r") as f: return json.load(f)[-(n*2):]
    except: pass
    return []

def _save_history(h, n=6):
    try:
        os.makedirs(_HIST_DIR, exist_ok=True)
        with open(_HIST_FILE, "w") as f: json.dump(h[-(n*2):], f, indent=2)
    except: pass

def clear_stream_history():
    _save_history([])

SYSTEM_PROMPT = (
    "You are the AI assistant for {app_name}. "
    "Be concise, technical, and helpful. Use markdown."
)

def stream_chat(prompt, dashboard_context=None):
    api_key = get_secret("GEMINI_API_KEY")
    if not api_key:
        yield {{"error": "GEMINI_API_KEY not found."}}
        return

    history = _load_history()
    history.append({{"role": "user", "content": prompt}})

    sys_prompt = SYSTEM_PROMPT
    if dashboard_context:
        sys_prompt += "\\n\\n--- LIVE STATE ---\\n" + json.dumps(dashboard_context, indent=2)

    contents = [
        {{"role": "user", "parts": [{{"text": sys_prompt + "\\nConversation begins."}}]}},
        {{"role": "model", "parts": [{{"text": "Ready to assist."}}]}},
    ]
    for m in history:
        contents.append({{"role": "user" if m["role"] == "user" else "model", "parts": [{{"text": m["content"]}}]}})

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse&key={{api_key}}"
    payload = {{"contents": contents, "generationConfig": {{"temperature": 0.7, "maxOutputTokens": 4096}}}}
    full = []

    try:
        with requests.post(url, json=payload, stream=True, timeout=120) as r:
            if r.status_code != 200:
                yield {{"error": f"Gemini {{r.status_code}}"}}
                return
            for line in r.iter_lines(decode_unicode=True):
                if not line or not line.startswith("data: "): continue
                try: chunk = json.loads(line[6:])
                except: continue
                for p in chunk.get("candidates", [{{}}])[0].get("content", {{}}).get("parts", []):
                    t = p.get("text", "")
                    if t:
                        full.append(t)
                        yield {{"text": t}}
        if full:
            history.append({{"role": "assistant", "content": "".join(full)}})
            _save_history(history)
        yield {{"text": "", "done": True}}
    except Exception as e:
        yield {{"error": str(e)}}
'''
        with open(os.path.join(app_path, "app_stream.py"), "w", encoding="utf-8") as f:
            f.write(code)

    # ── FRONTEND GENERATORS ─────────────────────────────────────

    def _write_package_json(self, ui_dir, app_name):
        pkg = {
            "name": app_name.lower().replace(" ", "-") + "-ui",
            "private": True,
            "version": "3.0.0",
            "type": "module",
            "scripts": {
                "dev": "vite",
                "build": "vite build",
                "preview": "vite preview",
            },
            "dependencies": {
                "react": "^19.0.0",
                "react-dom": "^19.0.0",
            },
            "devDependencies": {
                "@vitejs/plugin-react": "^4.4.1",
                "vite": "^6.3.0",
            },
        }
        with open(os.path.join(ui_dir, "package.json"), "w") as f:
            json.dump(pkg, f, indent=2)

    def _write_vite_config(self, ui_dir):
        code = '''import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 },
})
'''
        with open(os.path.join(ui_dir, "vite.config.js"), "w") as f:
            f.write(code)

    def _write_index_html(self, ui_dir, app_name):
        html = f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{app_name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
'''
        with open(os.path.join(ui_dir, "index.html"), "w") as f:
            f.write(html)

    def _write_main_jsx(self, src_dir):
        code = '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
'''
        with open(os.path.join(src_dir, "main.jsx"), "w") as f:
            f.write(code)

    def _write_app_jsx(self, src_dir, app_name):
        code = f'''import {{ useState, useEffect, useRef }} from 'react'

const API = 'http://localhost:5005';

function Chat() {{
  const [msgs, setMsgs] = useState([]);
  const [input, setInput] = useState('');
  const [streaming, setStreaming] = useState(false);
  const end = useRef(null);

  useEffect(() => {{ end.current?.scrollIntoView({{ behavior: 'smooth' }}); }}, [msgs]);

  const send = async () => {{
    const p = input.trim();
    if (!p || streaming) return;
    setInput('');
    setMsgs(m => [...m, {{ role: 'user', text: p }}]);
    setStreaming(true);
    setMsgs(m => [...m, {{ role: 'assistant', text: '' }}]);

    try {{
      const res = await fetch(`${{API}}/api/chat/stream`, {{
        method: 'POST',
        headers: {{ 'Content-Type': 'application/json' }},
        body: JSON.stringify({{ prompt: p }}),
      }});
      const reader = res.body.getReader();
      const dec = new TextDecoder();
      let buf = '';
      while (true) {{
        const {{ done, value }} = await reader.read();
        if (done) break;
        buf += dec.decode(value, {{ stream: true }});
        const lines = buf.split('\\n');
        buf = lines.pop() || '';
        for (const line of lines) {{
          if (!line.startsWith('data: ')) continue;
          try {{
            const ev = JSON.parse(line.slice(6));
            if (ev.error || ev.done) break;
            if (ev.text) setMsgs(m => {{
              const c = [...m];
              c[c.length - 1] = {{ role: 'assistant', text: c[c.length - 1].text + ev.text }};
              return c;
            }});
          }} catch {{}}
        }}
      }}
    }} catch (e) {{
      setMsgs(m => {{
        const c = [...m];
        c[c.length - 1] = {{ role: 'assistant', text: '❌ ' + e.message }};
        return c;
      }});
    }} finally {{ setStreaming(false); }}
  }};

  return (
    <div style={{{{ display: 'flex', flexDirection: 'column', height: '100vh', background: '#0a0e17', color: '#e2e8f0', fontFamily: 'Inter, sans-serif' }}}}>
      <header style={{{{ padding: '1rem 1.5rem', borderBottom: '1px solid rgba(99,102,241,0.15)', background: 'rgba(10,14,23,0.95)' }}}}>
        <h1 style={{{{ fontSize: '1.2rem', background: 'linear-gradient(135deg, #e2e8f0, #a78bfa)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}}}}>
          {app_name}
        </h1>
      </header>
      <div style={{{{ flex: 1, overflow: 'auto', padding: '1rem', display: 'flex', flexDirection: 'column', gap: '0.6rem' }}}}>
        {{msgs.map((m, i) => (
          <div key={{i}} style={{{{ alignSelf: m.role === 'user' ? 'flex-end' : 'flex-start', maxWidth: '80%', padding: '0.7rem 1rem', borderRadius: '12px', fontSize: '0.85rem', lineHeight: 1.5, background: m.role === 'user' ? 'linear-gradient(135deg, #6366f1, #7c3aed)' : 'rgba(30,41,59,0.8)', border: m.role === 'assistant' ? '1px solid rgba(99,102,241,0.15)' : 'none', color: 'white' }}}}>
            {{m.text}}
          </div>
        ))}}
        <div ref={{end}} />
      </div>
      <div style={{{{ display: 'flex', gap: '0.5rem', padding: '0.8rem 1rem', borderTop: '1px solid rgba(99,102,241,0.15)', background: 'rgba(10,14,23,0.5)' }}}}>
        <input value={{input}} onChange={{e => setInput(e.target.value)}} onKeyDown={{e => e.key === 'Enter' && send()}} placeholder="Ask anything..." disabled={{streaming}} style={{{{ flex: 1, background: 'rgba(15,23,42,0.6)', border: '1px solid rgba(99,102,241,0.15)', borderRadius: '10px', padding: '0.6rem 1rem', color: '#e2e8f0', fontSize: '0.85rem', outline: 'none' }}}} />
        <button onClick={{send}} disabled={{streaming || !input.trim()}} style={{{{ width: 40, height: 40, borderRadius: 10, border: 'none', background: 'linear-gradient(135deg, #6366f1, #7c3aed)', color: 'white', fontSize: '1.1rem', cursor: 'pointer' }}}}>↑</button>
      </div>
    </div>
  );
}}

export default function App() {{
  return <Chat />;
}}
'''
        with open(os.path.join(src_dir, "App.jsx"), "w") as f:
            f.write(code)

    def _write_index_css(self, src_dir):
        css = '''@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Inter', sans-serif; background: #0a0e17; color: #e2e8f0; }
'''
        with open(os.path.join(src_dir, "index.css"), "w") as f:
            f.write(css)

    def _write_requirements(self, app_path):
        reqs = "fastapi\nuvicorn\nrequests\npython-dotenv\npostgrest\ncryptography\nlangsmith\n"
        with open(os.path.join(app_path, "requirements.txt"), "w") as f:
            f.write(reqs)

    def _write_gitignore(self, app_path):
        gi = ".env\n.vault_pw\nvault.enc\nvault.enc.salt\nnode_modules/\ndist/\n__pycache__/\n*.pyc\n.DS_Store\nThumbs.db\n"
        path = os.path.join(app_path, ".gitignore")
        if not os.path.exists(path):
            with open(path, "w") as f:
                f.write(gi)


if __name__ == "__main__":
    des = UIDesigner()
    des.build_ui(".", "TestApp")
