from auto_heal import healed_post, auto_heal, diagnose

"""
app_stream.py — Multi-Agent V3 Streaming Engine
Generated by Meta App Factory Prompt Architect
═════════════════════════════════════════════════
Dynamic persona routing based on build_plan.json.
"""

import os
import sys
import json
import logging
import requests

logger = logging.getLogger("AppStream")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ── Load Build Plan ──────────────────────────────────────────
BUILD_PLAN = {}
try:
    with open(os.path.join(SCRIPT_DIR, "build_plan.json"), "r") as f:
        BUILD_PLAN = json.load(f)
except Exception as e:
    logger.warning(f"No build_plan.json found: {e}")

# ── Environment & Keys ───────────────────────────────────────
if "pythoncore-3.14-64" in sys.executable:
    sys.path.insert(0, os.path.join(SCRIPT_DIR, "..", "Alpha_V2_Genesis"))
    sys.path.insert(0, os.path.join(SCRIPT_DIR, "..", "..", ".system_core"))

try:
    from vault_client import get_secret
except ImportError:
    def get_secret(key, default="", **kw):
        return os.getenv(key, default)

# Setup basic local memory
_HISTORY_DIR = os.environ.get("Resonance2_RUNTIME_DIR", os.path.join(SCRIPT_DIR, "runtime"))
if not os.path.exists(_HISTORY_DIR):
    _HISTORY_DIR = os.path.join(SCRIPT_DIR, ".Gemini_state")
os.makedirs(_HISTORY_DIR, exist_ok=True)
_STREAM_HISTORY = os.path.join(_HISTORY_DIR, ".chat_history.json")

def _load_history(max_turns=10):
    try:
        if os.path.exists(_STREAM_HISTORY):
            with open(_STREAM_HISTORY, "r") as f:
                history = json.load(f)
            return history[-(max_turns * 2):]
    except Exception:
        pass
    return []

def _save_history(history, max_turns=10):
    try:
        with open(_STREAM_HISTORY, "w") as f:
            json.dump(history[-(max_turns * 2):], f, indent=2)
    except Exception as e:
        logger.warning(f"Failed to save history: {e}")

def clear_stream_history():
    _save_history([])

# ── Agent System Prompts ─────────────────────────────────────
# We generate the base system prompt dynamically from the build plan
def _build_system_prompt():
    agents = BUILD_PLAN.get("agents", [])
    features = BUILD_PLAN.get("features", [])
    
    prompt = "You are the primary orchestration agent for this application.\n\n"
    if agents:
        prompt += "AVAILABLE PERSONAS/AGENTS IN THIS APP:\n"
        for idx, agent in enumerate(agents):
            prompt += f"{idx+1}. {agent.get('name', 'Unknown')} ({agent.get('provider', 'gemini')}): {agent.get('role', '')}\n"
            if agent.get("system_prompt"):
                prompt += f"   System Prompt: {agent.get('system_prompt')}\n"
        prompt += "\n"
        
    if features:
        prompt += f"CORE FEATURES TO SUPPORT:\n- " + "\n- ".join(features) + "\n\n"
        
    prompt += "Provide helpful, direct responses. If a specific agent's persona is requested, adopt that persona."
    return prompt

# ── Streaming Client ─────────────────────────────────────────
def stream_chat(prompt, project_name="App", dashboard_context=None, agent_override=None):
    """Generator: yields SSE text chunks from Gemini."""
    api_key = get_secret("GEMINI_API_KEY")
    if not api_key:
        yield {"error": "GEMINI_API_KEY not found."}
        return

    history = _load_history()
    history.append({"role": "user", "content": prompt})

    sys_prompt = _build_system_prompt()
    if dashboard_context:
        sys_prompt += f"\n\nLIVE CONTEXT:\n{json.dumps(dashboard_context, indent=2)}"

    contents = [
        {"role": "user", "parts": [{"text": sys_prompt + "\n\nConversation starts now."}]},
        {"role": "model", "parts": [{"text": "Understood. I'm ready."}]},
    ]
    for msg in history:
        role = "user" if msg["role"] == "user" else "model"
        contents.append({"role": role, "parts": [{"text": msg["content"]}]})

    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse"
    headers = {"x-goog-api-key": api_key, "Content-Type": "application/json"}
    payload = {
        "contents": contents,
        "generationConfig": {"temperature": 0.7, "maxOutputTokens": 4096},
    }

    # ── SWDR v1.0: Exponential Backoff + Circuit Breaker ────────
    import time
    import random

    try:
        from circuit_breaker import CircuitBreaker
        _cb = CircuitBreaker("resonance2-gemini", failure_threshold=3, cooldown_seconds=60)
    except ImportError:
        _cb = None

    if _cb and not _cb.can_call():
        yield {"error": "🛑 Gemini circuit breaker OPEN. Cooling down — please retry shortly."}
        try:
            from error_aggregator import ErrorAggregator
            ErrorAggregator("Resonance2").log_critical(
                "Gemini circuit breaker OPEN — streaming call blocked",
                context={"action": "soft_pause"}
            )
        except ImportError:
            pass
        return

    full_response = []
    max_retries = 3
    backoff_base = 2
    last_error = None

    for attempt in range(max_retries):
        try:
            with requests.post(url, json=payload, headers=headers, stream=True, timeout=120) as resp:
                if resp.status_code != 200:
                    raise Exception(f"API error ({resp.status_code})")

                for line in resp.iter_lines(decode_unicode=True):
                    if not line or not line.startswith("data: "): continue
                    try:
                        chunk = json.loads(line[6:])
                    except json.JSONDecodeError:
                        continue
                    candidates = chunk.get("candidates", [])
                    if not candidates: continue
                    parts = candidates[0].get("content", {}).get("parts", [])
                    for part in parts:
                        text = part.get("text", "")
                        if text:
                            full_response.append(text)
                            yield {"text": text}

            # If we reached here, streaming succeeded
            if _cb: _cb.record_success()

            complete_text = "".join(full_response)
            if complete_text:
                history.append({"role": "assistant", "content": complete_text})
                _save_history(history)
            yield {"done": True}
            return  # Success — exit the retry loop

        except Exception as e:
            last_error = e
            if _cb: _cb.record_failure()
            if attempt < max_retries - 1:
                delay = backoff_base * (2 ** attempt) + random.uniform(-0.4, 0.4) * backoff_base
                logger.warning(f"Gemini stream attempt {attempt+1} failed: {e}. Backoff {delay:.1f}s...")
                time.sleep(delay)
                full_response = []  # Reset for retry
            else:
                # Final failure — log and yield error
                try:
                    from error_aggregator import ErrorAggregator
                    ErrorAggregator("Resonance2").log_critical(
                        f"Gemini streaming failed after {max_retries} attempts",
                        context={"error": str(e), "action": "overseer_notify"}
                    )
                except ImportError:
                    pass
                yield {"error": f"Streaming failed after {max_retries} attempts: {str(last_error)}"}

# V3 MIGRATION COMPLETE
# V3 AUTO-HEAL ACTIVE
