import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import api from '../services/api';

const EquipmentIngestionModal = ({ isOpen, onClose, onIngestSuccess }) => {
  const [activeTab, setActiveTab] = useState('SINGLE'); // 'SINGLE' or 'BULK'
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState(null);

  // Lookup State (populated on mount from paginated backend routes)
  const [categories, setCategories] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [technicians, setTechnicians] = useState([]);
  const [locations, setLocations] = useState([]);
  const [hms, setHms] = useState([]);
  const [lookupsLoading, setLookupsLoading] = useState(true);

  // Payload State — equipment_id is auto-generated by backend
  const [payload, setPayload] = useState({
    nomenclature: '',
    category_id: '',
    status: 'ACTIVE',
    department_id: '',
    assigned_tech_id: '',
    location_id: '',
    assigned_hm_id: ''
  });

  // Bulk State
  const [bulkFile, setBulkFile] = useState(null);

  // Fetch bounded lookups on mount
  useEffect(() => {
    if (!isOpen) return;
    const fetchLookups = async () => {
      setLookupsLoading(true);
      try {
        const [catRes, depRes, techRes, hmsRes, locRes] = await Promise.all([
          api.get('/admin/lookups/categories?limit=100&offset=0'),
          api.get('/admin/lookups/departments?limit=100&offset=0'),
          api.get('/admin/lookups/technicians?limit=100&offset=0'),
          api.get('/mwo/hms'),
          api.get('/admin/lookups/locations?limit=100&offset=0')
        ]);
        setCategories(catRes.data.data || []);
        setDepartments(depRes.data.data || []);
        setTechnicians(techRes.data.data || []);
        setHms(hmsRes.data.data || []);
        setLocations(locRes.data.data || []);
      } catch (err) {
        console.error("Lookup transit failure:", err);
        setError("Failed to load lookup data. Check backend connectivity.");
      } finally {
        setLookupsLoading(false);
      }
    };
    fetchLookups();
    // Reset form
    setPayload({ nomenclature: '', category_id: '', status: 'ACTIVE', department_id: '', assigned_tech_id: '', location_id: '', assigned_hm_id: '' });
    setBulkFile(null);
    setActiveTab('SINGLE');
    setError(null);
  }, [isOpen]);

  // Transit Lockout: Escape key listener
  useEffect(() => {
    const handleEsc = (e) => {
      if (e.key === 'Escape' && !isProcessing) onClose();
    };
    document.addEventListener('keydown', handleEsc);
    return () => document.removeEventListener('keydown', handleEsc);
  }, [onClose, isProcessing]);

  if (!isOpen) return null;

  const handleChange = (field, value) => {
    setPayload(prev => ({ ...prev, [field]: value }));
  };

  const handleSingleSubmit = async (e) => {
    e.preventDefault();
    if (isProcessing) return;

    try {
      setIsProcessing(true);
      setError(null);

      // Atomic Ingestion Dispatch — PK auto-generated by backend
      await api.post('/admin/ingest/equipment', {
        nomenclature: payload.nomenclature.trim(),
        category_id: payload.category_id,
        status: payload.status,
        department_id: payload.department_id,
        assigned_tech_id: payload.assigned_tech_id || null,
        location_id: payload.location_id,
        assigned_hm_id: payload.assigned_hm_id
      });

      // Success Resolution Phase — Transit Lockout HELD
      await onIngestSuccess();

      // Post-resolution teardown
      onClose();
    } catch (err) {
      setError(err.response?.data?.detail || 'Equipment ingestion failed.');
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDownloadTemplate = async () => {
    try {
      const response = await api.get('/admin/ingest/equipment/template', { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'equipment_ingestion_template.xlsx');
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      setError('Failed to download template.');
    }
  };

  const handleBulkSubmit = async (e) => {
    e.preventDefault();
    if (!bulkFile || isProcessing) return;
    
    try {
      setIsProcessing(true);
      setError(null);
      
      const formData = new FormData();
      formData.append('file', bulkFile);
      
      await api.post('/admin/ingest/equipment/bulk', formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      });
      
      await onIngestSuccess();
      onClose();
    } catch (err) {
      setError(err.response?.data?.detail || 'Bulk equipment ingestion failed.');
    } finally {
      setIsProcessing(false);
    }
  };

  const inputStyle = {
    width: '100%', padding: '0.65rem', background: 'rgba(10, 14, 23, 0.8)',
    border: '1px solid rgba(16, 185, 129, 0.25)', borderRadius: '6px',
    color: '#e2e8f0', fontSize: '0.85rem', outline: 'none', boxSizing: 'border-box',
    transition: 'border-color 0.2s'
  };

  const labelStyle = {
    display: 'block', marginBottom: '0.25rem', color: '#94a3b8',
    fontSize: '0.7rem', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em'
  };

  const fieldGroup = { marginBottom: '0.9rem' };
  const isFormValid = payload.nomenclature.trim() && payload.category_id && payload.department_id && payload.location_id && payload.assigned_hm_id;

  const handleLocationChange = (loc) => {
    // Basic auto HM mapping based on modulo logic
    let autoHm = '';
    if (hms.length > 0) {
      // Just pick the first HM for simplicity now since locations are dynamic
      autoHm = hms[0]?.user_id || hms[0]?.id || ''; 
    }
    setPayload(prev => ({ ...prev, location_id: loc, assigned_hm_id: autoHm }));
  };

  const modalContent = (
    <div
      style={{ position: 'fixed', inset: 0, zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(4px)' }}
      onClick={() => { if (!isProcessing) onClose(); }}
    >
      <div
        style={{ background: 'linear-gradient(145deg, rgba(15, 23, 42, 0.98), rgba(30, 41, 59, 0.95))', border: '1px solid rgba(16, 185, 129, 0.25)', borderRadius: '16px', padding: '2rem', width: '540px', maxWidth: '92vw', boxShadow: '0 25px 60px rgba(0,0,0,0.5)' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
          <div>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#e2e8f0', margin: 0 }}>
              Ingest New Equipment
            </h3>
            <p style={{ color: '#64748b', fontSize: '0.75rem', margin: '0.25rem 0 0 0' }}>
              PK auto-generated | FK-normalized insertion
            </p>
          </div>
          <button
            onClick={onClose}
            disabled={isProcessing}
            style={{ background: 'rgba(239, 68, 68, 0.15)', color: '#ef4444', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: '6px', padding: '0.3rem 0.6rem', cursor: isProcessing ? 'not-allowed' : 'pointer', fontSize: '0.75rem', fontWeight: 600, opacity: isProcessing ? 0.5 : 1 }}
          >
            ESC
          </button>
        </div>

        {/* Error Banner */}
        {error && (
          <div style={{ padding: '0.6rem', background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', borderRadius: '6px', color: '#ef4444', fontSize: '0.8rem', marginBottom: '1rem' }}>
            {error}
          </div>
        )}

        {/* Tab Selection */}
        <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.5rem', borderBottom: '1px solid rgba(148, 163, 184, 0.2)', paddingBottom: '0.5rem' }}>
          <button
            onClick={() => setActiveTab('SINGLE')}
            disabled={isProcessing}
            style={{ background: 'none', border: 'none', color: activeTab === 'SINGLE' ? '#10b981' : '#94a3b8', fontSize: '0.85rem', fontWeight: 700, cursor: isProcessing ? 'not-allowed' : 'pointer', padding: '0.5rem 1rem', borderBottom: activeTab === 'SINGLE' ? '2px solid #10b981' : '2px solid transparent', transition: 'all 0.2s' }}
          >
            SINGLE INGESTION
          </button>
          <button
            onClick={() => setActiveTab('BULK')}
            disabled={isProcessing}
            style={{ background: 'none', border: 'none', color: activeTab === 'BULK' ? '#10b981' : '#94a3b8', fontSize: '0.85rem', fontWeight: 700, cursor: isProcessing ? 'not-allowed' : 'pointer', padding: '0.5rem 1rem', borderBottom: activeTab === 'BULK' ? '2px solid #10b981' : '2px solid transparent', transition: 'all 0.2s' }}
          >
            BULK XLSX UPLOAD
          </button>
        </div>

        {lookupsLoading ? (
          <div style={{ color: '#94a3b8', textAlign: 'center', padding: '2rem', fontSize: '0.85rem' }}>
            Loading lookup data...
          </div>
        ) : activeTab === 'SINGLE' ? (
          <form onSubmit={handleSingleSubmit}>
            {/* Nomenclature */}
            <div style={fieldGroup}>
              <label style={labelStyle}>Nomenclature <span style={{ color: '#ef4444' }}>*</span></label>
              <input
                type="text"
                value={payload.nomenclature}
                onChange={e => handleChange('nomenclature', e.target.value)}
                disabled={isProcessing}
                placeholder="Human-readable equipment name"
                style={{ ...inputStyle, cursor: isProcessing ? 'not-allowed' : 'text' }}
              />
            </div>

            {/* Location + Assigned HM */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem', marginBottom: '0.9rem' }}>
              <div>
                <label style={labelStyle}>Location <span style={{ color: '#ef4444' }}>*</span></label>
                <select
                  value={payload.location_id}
                  onChange={e => handleLocationChange(e.target.value)}
                  disabled={isProcessing}
                  style={{ ...inputStyle, cursor: isProcessing ? 'not-allowed' : 'pointer', appearance: 'auto' }}
                >
                  <option value="" style={{ background: '#0f172a', color: '#64748b' }}>-- Select Location --</option>
                  {locations.map(loc => (
                    <option key={loc.id} value={loc.id} style={{ background: '#0f172a', color: '#e2e8f0' }}>{loc.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label style={labelStyle}>Assigned HM <span style={{ color: '#ef4444' }}>*</span></label>
                <select
                  value={payload.assigned_hm_id}
                  onChange={e => handleChange('assigned_hm_id', e.target.value)}
                  disabled={isProcessing}
                  style={{ ...inputStyle, cursor: isProcessing ? 'not-allowed' : 'pointer', appearance: 'auto' }}
                >
                  <option value="" style={{ background: '#0f172a', color: '#64748b' }}>-- Auto Mapped HM --</option>
                  {hms.map(hm => (
                    <option key={hm.user_id} value={hm.user_id} style={{ background: '#0f172a', color: '#e2e8f0' }}>{hm.name} ({hm.user_id})</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Category + Department */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem' }}>
              <div style={fieldGroup}>
                <label style={labelStyle}>Category <span style={{ color: '#ef4444' }}>*</span></label>
                <select
                  value={payload.category_id}
                  onChange={e => handleChange('category_id', e.target.value)}
                  disabled={isProcessing}
                  style={{ ...inputStyle, cursor: isProcessing ? 'not-allowed' : 'pointer', appearance: 'auto' }}
                >
                  <option value="" style={{ background: '#0f172a', color: '#64748b' }}>-- Select Category --</option>
                  {categories.map(cat => (
                    <option key={cat.id} value={cat.id} style={{ background: '#0f172a', color: '#e2e8f0' }}>{cat.name}</option>
                  ))}
                </select>
                {categories.length === 0 && <p style={{ color: '#f59e0b', fontSize: '0.7rem', margin: '0.3rem 0 0' }}>No categories found. Seed lookup data first.</p>}
              </div>
              <div style={fieldGroup}>
                <label style={labelStyle}>Department <span style={{ color: '#ef4444' }}>*</span></label>
                <select
                  value={payload.department_id}
                  onChange={e => handleChange('department_id', e.target.value)}
                  disabled={isProcessing}
                  style={{ ...inputStyle, cursor: isProcessing ? 'not-allowed' : 'pointer', appearance: 'auto' }}
                >
                  <option value="" style={{ background: '#0f172a', color: '#64748b' }}>-- Select Department --</option>
                  {departments.map(dep => (
                    <option key={dep.id} value={dep.id} style={{ background: '#0f172a', color: '#e2e8f0' }}>{dep.name}</option>
                  ))}
                </select>
                {departments.length === 0 && <p style={{ color: '#f59e0b', fontSize: '0.7rem', margin: '0.3rem 0 0' }}>No departments found. Seed lookup data first.</p>}
              </div>
            </div>

            {/* Status + Assigned Tech */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem' }}>
              <div style={fieldGroup}>
                <label style={labelStyle}>Status</label>
                <select
                  value={payload.status}
                  onChange={e => handleChange('status', e.target.value)}
                  disabled={isProcessing}
                  style={{ ...inputStyle, cursor: isProcessing ? 'not-allowed' : 'pointer', appearance: 'auto' }}
                >
                  <option value="ACTIVE" style={{ background: '#0f172a', color: '#e2e8f0' }}>ACTIVE</option>
                  <option value="DEGRADED" style={{ background: '#0f172a', color: '#e2e8f0' }}>DEGRADED</option>
                  <option value="OFFLINE" style={{ background: '#0f172a', color: '#e2e8f0' }}>OFFLINE</option>
                </select>
              </div>
              <div style={fieldGroup}>
                <label style={labelStyle}>Assigned Tech <span style={{ color: '#64748b', fontWeight: 400 }}>(optional)</span></label>
                <select
                  value={payload.assigned_tech_id}
                  onChange={e => handleChange('assigned_tech_id', e.target.value)}
                  disabled={isProcessing}
                  style={{ ...inputStyle, cursor: isProcessing ? 'not-allowed' : 'pointer', appearance: 'auto' }}
                >
                  <option value="" style={{ background: '#0f172a', color: '#64748b' }}>-- Unassigned --</option>
                  {technicians.map(tech => (
                    <option key={tech.id} value={tech.id} style={{ background: '#0f172a', color: '#e2e8f0' }}>{tech.name} ({tech.id})</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Action Buttons */}
            <div style={{ display: 'flex', gap: '1rem', marginTop: '0.5rem' }}>
              <button
                type="button"
                onClick={onClose}
                disabled={isProcessing}
                style={{ flex: 1, padding: '0.7rem', background: 'rgba(148, 163, 184, 0.1)', color: '#94a3b8', border: '1px solid rgba(148, 163, 184, 0.2)', borderRadius: '8px', cursor: isProcessing ? 'not-allowed' : 'pointer', fontWeight: 600, fontSize: '0.85rem', opacity: isProcessing ? 0.5 : 1, transition: 'all 0.2s' }}
              >
                CANCEL
              </button>
              <button
                type="submit"
                disabled={isProcessing || !isFormValid}
                style={{ flex: 1, padding: '0.7rem', background: isProcessing || !isFormValid ? 'rgba(16, 185, 129, 0.15)' : 'linear-gradient(135deg, #10b981, #059669)', color: isProcessing || !isFormValid ? '#64748b' : '#fff', border: 'none', borderRadius: '8px', cursor: isProcessing || !isFormValid ? 'not-allowed' : 'pointer', fontWeight: 700, fontSize: '0.85rem', transition: 'all 0.2s', boxShadow: isProcessing || !isFormValid ? 'none' : '0 4px 15px rgba(16, 185, 129, 0.25)' }}
              >
                {isProcessing ? 'INGESTING...' : 'INGEST EQUIPMENT'}
              </button>
            </div>
          </form>
        ) : (
          <form onSubmit={handleBulkSubmit}>
            <div style={{ marginBottom: '1.5rem', textAlign: 'center' }}>
              <button
                type="button"
                onClick={handleDownloadTemplate}
                disabled={isProcessing}
                style={{ background: 'rgba(56, 189, 248, 0.15)', color: '#38bdf8', border: '1px solid rgba(56, 189, 248, 0.3)', borderRadius: '6px', padding: '0.6rem 1.2rem', cursor: isProcessing ? 'not-allowed' : 'pointer', fontSize: '0.8rem', fontWeight: 600, transition: 'all 0.2s' }}
              >
                ⬇ DOWNLOAD XLSX TEMPLATE
              </button>
              <p style={{ color: '#64748b', fontSize: '0.75rem', marginTop: '0.5rem' }}>
                Download the exact schema mapping needed for bulk upload.
              </p>
            </div>
            
            <div style={{ ...fieldGroup, background: 'rgba(10, 14, 23, 0.5)', padding: '1.5rem', borderRadius: '8px', border: '1px dashed rgba(16, 185, 129, 0.4)', textAlign: 'center' }}>
              <label style={{ ...labelStyle, marginBottom: '1rem', cursor: 'pointer' }}>
                Select XLSX File
                <input
                  type="file"
                  accept=".xlsx"
                  onChange={e => setBulkFile(e.target.files[0])}
                  disabled={isProcessing}
                  style={{ display: 'none' }}
                />
              </label>
              <div style={{ color: bulkFile ? '#10b981' : '#94a3b8', fontSize: '0.85rem', fontWeight: 600, wordBreak: 'break-all' }}>
                {bulkFile ? bulkFile.name : 'No file chosen'}
              </div>
            </div>

            {/* Action Buttons */}
            <div style={{ display: 'flex', gap: '1rem', marginTop: '0.5rem' }}>
              <button
                type="button"
                onClick={onClose}
                disabled={isProcessing}
                style={{ flex: 1, padding: '0.7rem', background: 'rgba(148, 163, 184, 0.1)', color: '#94a3b8', border: '1px solid rgba(148, 163, 184, 0.2)', borderRadius: '8px', cursor: isProcessing ? 'not-allowed' : 'pointer', fontWeight: 600, fontSize: '0.85rem', opacity: isProcessing ? 0.5 : 1, transition: 'all 0.2s' }}
              >
                CANCEL
              </button>
              <button
                type="submit"
                disabled={isProcessing || !bulkFile}
                style={{ flex: 1, padding: '0.7rem', background: isProcessing || !bulkFile ? 'rgba(16, 185, 129, 0.15)' : 'linear-gradient(135deg, #10b981, #059669)', color: isProcessing || !bulkFile ? '#64748b' : '#fff', border: 'none', borderRadius: '8px', cursor: isProcessing || !bulkFile ? 'not-allowed' : 'pointer', fontWeight: 700, fontSize: '0.85rem', transition: 'all 0.2s', boxShadow: isProcessing || !bulkFile ? 'none' : '0 4px 15px rgba(16, 185, 129, 0.25)' }}
              >
                {isProcessing ? 'UPLOADING...' : 'UPLOAD BULK XLSX'}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );

  return ReactDOM.createPortal(modalContent, document.body);
};

export default EquipmentIngestionModal;
