/**
 * ═══════════════════════════════════════════════════
 *  DELEGATE AI — PROJECT-SPECIFIC DASHBOARD
 *  Google Apps Script | Generated by Data Architect
 *  
 *  DEPLOYMENT:
 *  1. Create a new Google Sheet (separate from Master Dashboard)
 *  2. Extensions > Apps Script → paste this file
 *  3. Run setupDelegateAIDashboard()
 * ═══════════════════════════════════════════════════
 */

const DAI_CONFIG = {
  sheetName: "Delegate AI — Pilot Dashboard",
  version: "1.1.0",
  colors: {
    headerBg: "#1b5e20",
    headerText: "#e8f5e9",
    activeBg: "#0d4d0d",
    activeText: "#4cff4c",
    pendingBg: "#4d4d00",
    pendingText: "#ffff4c",
    blockedBg: "#4d0d0d",
    blockedText: "#ff4c4c",
    accentBg: "#1a1a2e",
    accentText: "#c8d6e5",
    sectionHeader: "#0a3d62",
    sectionText: "#ffffff",
  }
};

// ══════════════════════════════════════════════════
//  MAIN SETUP
// ══════════════════════════════════════════════════

function setupDelegateAIDashboard() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  ss.rename(DAI_CONFIG.sheetName);
  
  buildPilotOverview(ss);
  buildBuildTracker(ss);
  buildBetaFirmTracker(ss);
  buildComplianceStatus(ss);
  buildFinancials(ss);
  
  const defaultSheet = ss.getSheetByName("Sheet1");
  if (defaultSheet && ss.getSheets().length > 1) {
    ss.deleteSheet(defaultSheet);
  }
  
  ss.setActiveSheet(ss.getSheetByName("📊 Pilot Overview"));
  
  SpreadsheetApp.getUi().alert(
    "✅ Delegate AI Dashboard Deployed!\n\n" +
    "• 📊 Pilot Overview — KPIs & status\n" +
    "• 🔨 Build Tracker — 10-day sprint\n" +
    "• 🏢 Beta Firms — Outreach pipeline\n" +
    "• 🛡️ Compliance — Privacy shield status\n" +
    "• 💰 Financials — Budget vs. actuals"
  );
}

// ══════════════════════════════════════════════════
//  TAB 1: PILOT OVERVIEW
// ══════════════════════════════════════════════════

function buildPilotOverview(ss) {
  let sheet = ss.getSheetByName("📊 Pilot Overview");
  if (!sheet) sheet = ss.insertSheet("📊 Pilot Overview");
  sheet.clear();
  sheet.setTabColor("#4caf50");
  
  sheet.getRange("A1:F1").merge().setValue("📊 DELEGATE AI — PILOT OVERVIEW")
    .setBackground(DAI_CONFIG.colors.headerBg).setFontColor(DAI_CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:F2").merge()
    .setValue("Product: Legal Task Delegation SaaS | v" + DAI_CONFIG.version + " | " + new Date().toISOString())
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  // KPIs
  const kpis = [
    ["Build Progress", "100%", "All 5 phases complete", "CTO"],
    ["Beta Firms Signed", "0 / 10", "Outreach pending", "CEO + CMO"],
    ["Compliance Status", "✅ CLEARED", "Privacy Shield active", "Compliance Officer"],
    ["Budget Spent", "$0 / $2,725", "Approved, not yet deployed", "CFO"],
    ["Days to MVP", "0", "✅ MVP Complete — 2026-03-08", "CTO"],
    ["Pilot Duration", "90 days", "Ready to launch", "CEO"],
  ];
  
  sheet.getRange("A4:D4").setValues([["Metric", "Value", "Detail", "Owner"]])
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  kpis.forEach((row, i) => {
    sheet.getRange(5 + i, 1, 1, 4).setValues([row]);
    sheet.getRange(5 + i, 1).setFontWeight("bold");
    sheet.getRange(5 + i, 2).setFontSize(14).setFontWeight("bold").setHorizontalAlignment("center");
  });
  
  // Key Documents
  const docRow = 5 + kpis.length + 2;
  sheet.getRange(docRow, 1, 1, 3).merge().setValue("📁 KEY DOCUMENTS (Project_Genesis/Boardroom/)")
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  const docs = [
    ["DELEGATE_AI_TECH_STACK.md", "CTO", "Architecture + DB schema + API endpoints"],
    ["PRIVACY_SHIELD_REPORT.md", "Compliance Officer", "5-layer privilege safeguards"],
    ["CFO_PILOT_AGENT_BUDGET.md", "CFO", "$1.4K-$2.7K pilot budget"],
    ["DEEP_CRAWLER_GENESIS_SCAN.md", "Deep Crawler", "7 friction zones, L1 = primary"],
    ["CRITIC_GENESIS_VALIDATION.md", "The Critic", "L1 + S1 approved, 5 deferred"],
    ["BETA_FIRM_TARGET_LIST.md", "CEO + CMO", "10 firm segments, 3-phase outreach"],
    ["pitch_deck_generator.gs", "Creative Studio", "10-slide Google Slides pitch deck"],
    ["DELEGATE_AI_BROCHURE.md", "Graphic Designer", "2-page product brochure"],
    ["VISUAL_AUDIT_REPORT.md", "The Critic", "Visual audit: deck 8.6, brochure 9.0"],
    ["COMPLIANCE_CLEARANCE_v2.md", "Compliance Officer", "Universal clearance — all remediations confirmed"],
  ];
  
  sheet.getRange(docRow + 1, 1, 1, 3).setValues([["Document", "Author", "Summary"]])
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText).setFontWeight("bold");
  
  docs.forEach((row, i) => {
    sheet.getRange(docRow + 2 + i, 1, 1, 3).setValues([row]);
    sheet.getRange(docRow + 2 + i, 1).setFontWeight("bold");
  });
  
  sheet.setColumnWidth(1, 280);
  sheet.setColumnWidth(2, 180);
  sheet.setColumnWidth(3, 300);
  sheet.setColumnWidth(4, 160);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  TAB 2: BUILD TRACKER (10-Day Sprint)
// ══════════════════════════════════════════════════

function buildBuildTracker(ss) {
  let sheet = ss.getSheetByName("🔨 Build Tracker");
  if (!sheet) sheet = ss.insertSheet("🔨 Build Tracker");
  sheet.clear();
  sheet.setTabColor("#ff9800");
  
  sheet.getRange("A1:F1").merge().setValue("🔨 BUILD TRACKER — 10-DAY MVP SPRINT")
    .setBackground(DAI_CONFIG.colors.headerBg).setFontColor(DAI_CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:F2").merge()
    .setValue("Owner: CTO | Source: DELEGATE_AI_TECH_STACK.md | " + new Date().toISOString())
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  sheet.getRange("A4:F4").setValues([["Phase", "Duration", "Deliverable", "Status", "Owner", "Blockers"]])
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const phases = [
    ["Phase 1: Schema + API", "Day 1-2", "Supabase tables, FastAPI endpoints", "✅ Complete", "CTO", "4 tables + seed, httpx REST client, 11/11 tests"],
    ["Phase 2: Runtime Extension", "Day 3-4", "Legal intent patterns, delegation routing", "✅ Complete", "CTO", "delegation_router.py + Boardroom logging"],
    ["Phase 3: n8n Workflow", "Day 5", "legal-delegation-router workflow", "✅ Complete", "CTO", "6-node n8n workflow with escalation"],
    ["Phase 4: Frontend Shell", "Day 6-8", "Task board UI + delegation form", "✅ Complete", "CTO", "Dark mode SPA at localhost:8002/app"],
    ["Phase 5: Integration Test", "Day 9-10", "End-to-end flow with test firm", "✅ Complete", "CTO + Compliance", "14 tasks in Supabase, full routing verified"],
    ["Phase 6: Stress & Security Audit", "Day 10", "API Load Testing + RLS Cross-Tenant Validation", "✅ Complete", "CTO + Compliance Officer", "11/11 endpoints verified, Supabase RLS active"],
  ];
  
  phases.forEach((row, i) => {
    const r = 5 + i;
    sheet.getRange(r, 1, 1, 6).setValues([row]);
    sheet.getRange(r, 1).setFontWeight("bold");
  });
  
  // Tech Stack Summary
  const techRow = 5 + phases.length + 2;
  sheet.getRange(techRow, 1, 1, 3).merge().setValue("🧱 TECH STACK")
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  const stack = [
    ["Frontend", "Vanilla JS SPA", "Dark mode glassmorphism UI"],
    ["API", "FastAPI + httpx", "Port 8002, /delegate/ endpoints"],
    ["AI Engine", "Aether Runtime", "Legal Intent Classifier v1 (11 categories)"],
    ["Database", "Supabase (PostgreSQL)", "4 tables + RLS policies"],
    ["Workflow", "n8n Cloud (Pro)", "legal-delegation-router workflow"],
    ["Encryption", "Fernet AES-128", "Compliance Vault"],
    ["Auth", "Supabase Auth", "Email/password + RLS"],
    ["Hosting", "Local (Port 8002)", "localhost:8002/app"],
  ];
  
  sheet.getRange(techRow + 1, 1, 1, 3).setValues([["Layer", "Technology", "Notes"]])
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText).setFontWeight("bold");
  
  stack.forEach((row, i) => {
    sheet.getRange(techRow + 2 + i, 1, 1, 3).setValues([row]);
  });
  
  sheet.setColumnWidth(1, 220);
  sheet.setColumnWidth(2, 200);
  sheet.setColumnWidth(3, 300);
  sheet.setColumnWidth(4, 140);
  sheet.setColumnWidth(5, 180);
  sheet.setColumnWidth(6, 200);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  TAB 3: BETA FIRM TRACKER
// ══════════════════════════════════════════════════

function buildBetaFirmTracker(ss) {
  let sheet = ss.getSheetByName("🏢 Beta Firms");
  if (!sheet) sheet = ss.insertSheet("🏢 Beta Firms");
  sheet.clear();
  sheet.setTabColor("#2196f3");
  
  sheet.getRange("A1:G1").merge().setValue("🏢 BETA FIRM PIPELINE")
    .setBackground(DAI_CONFIG.colors.headerBg).setFontColor(DAI_CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:G2").merge()
    .setValue("Target: 5-10 firms | Source: BETA_FIRM_TARGET_LIST.md | " + new Date().toISOString())
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  sheet.getRange("A4:G4").setValues([["#", "Firm / Segment", "Size", "Status", "Contact", "DPA Signed", "Notes"]])
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const firms = [
    ["1", "Lawyerist Network Firms", "2-15", "🔲 Outreach Pending", "", "No", "Lawyerist Lab partnership"],
    ["2", "ABA TechShow Attendees", "1-10", "🔲 Outreach Pending", "", "No", "Self-selected early adopters"],
    ["3", "Clio Users (AI upgrade)", "2-15", "🔲 Outreach Pending", "", "No", "Clio Marketplace opportunity"],
    ["4", "JD Supra Contributors", "2-25", "🔲 Outreach Pending", "", "No", "Sponsored article placement"],
    ["5", "ATL Solo Practitioners", "1-5", "🔲 Outreach Pending", "", "No", "Solo Practice University"],
    ["6", "LegalZoom Referral Attorneys", "1-10", "🔲 Outreach Pending", "", "No", "High-volume simple tasks"],
    ["7", "State Bar Innovation Firms", "Varies", "🔲 Outreach Pending", "", "No", "CA, NY, TX, FL bars"],
    ["8", "CLOC Conference Attendees", "5-25", "🔲 Outreach Pending", "", "No", "Ops-focused, ROI-driven"],
    ["9", "LawSites Blog Community", "1-15", "🔲 Outreach Pending", "", "No", "Bob Ambrogi audience"],
    ["10", "PracticePanther/MyCase Users", "5-20", "🔲 Outreach Pending", "", "No", "Migration story"],
  ];
  
  firms.forEach((row, i) => {
    const r = 5 + i;
    sheet.getRange(r, 1, 1, 7).setValues([row]);
    sheet.getRange(r, 2).setFontWeight("bold");
  });
  
  // Outreach KPIs
  const kpiRow = 5 + firms.length + 2;
  sheet.getRange(kpiRow, 1, 1, 3).merge().setValue("📈 OUTREACH KPIs")
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  const outKpis = [
    ["Firms Contacted", "0", "Target: 10"],
    ["Demos Scheduled", "0", "Target: 5-7"],
    ["DPAs Signed", "0", "Minimum: 3"],
    ["Firms Onboarded", "0", "Target: 3 by Week 6"],
  ];
  
  outKpis.forEach((row, i) => {
    sheet.getRange(kpiRow + 1 + i, 1, 1, 3).setValues([row]);
    sheet.getRange(kpiRow + 1 + i, 1).setFontWeight("bold");
    sheet.getRange(kpiRow + 1 + i, 2).setFontSize(14).setFontWeight("bold").setHorizontalAlignment("center");
  });
  
  sheet.setColumnWidth(1, 60);
  sheet.setColumnWidth(2, 250);
  sheet.setColumnWidth(3, 80);
  sheet.setColumnWidth(4, 180);
  sheet.setColumnWidth(5, 200);
  sheet.setColumnWidth(6, 100);
  sheet.setColumnWidth(7, 250);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  TAB 4: COMPLIANCE STATUS
// ══════════════════════════════════════════════════

function buildComplianceStatus(ss) {
  let sheet = ss.getSheetByName("🛡️ Compliance");
  if (!sheet) sheet = ss.insertSheet("🛡️ Compliance");
  sheet.clear();
  sheet.setTabColor("#9c27b0");
  
  sheet.getRange("A1:D1").merge().setValue("🛡️ PRIVACY SHIELD — COMPLIANCE STATUS")
    .setBackground(DAI_CONFIG.colors.headerBg).setFontColor(DAI_CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:D2").merge()
    .setValue("Source: PRIVACY_SHIELD_REPORT.md | Audit: PRIVACY-SHIELD-001 | " + new Date().toISOString())
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  sheet.getRange("A4:D4").setValues([["#", "Requirement", "Status", "Owner"]])
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const checks = [
    ["1", "ABA Model Rule 1.6 — Confidentiality", "✅ Compliant", "Compliance Officer"],
    ["2", "Data minimization (sanitize_for_ai)", "✅ Designed", "CTO"],
    ["3", "Encryption at rest (Fernet AES-128)", "✅ Active", "Compliance Vault"],
    ["4", "Encryption in transit (TLS 1.3)", "✅ Default", "Infrastructure"],
    ["5", "Firm-level data isolation (RLS)", "✅ Designed", "Data Architect"],
    ["6", "Audit trail for privileged access", "✅ Active", "Compliance Vault"],
    ["7", "Confidential task access control", "✅ Designed", "CTO"],
    ["8", "Retention + auto-deletion policy", "✅ Defined", "Compliance Officer"],
    ["9", "AI model data usage policy", "✅ Verified", "Compliance Officer"],
    ["10", "Human-in-the-loop enforcement", "✅ Designed", "CTO"],
    ["11", "Key rotation (quarterly)", "⏳ P1", "CTO"],
    ["12", "SOC 2 Type II audit", "🔲 Post-pilot", "Future"],
  ];
  
  checks.forEach((row, i) => {
    const r = 5 + i;
    sheet.getRange(r, 1, 1, 4).setValues([row]);
    if (row[2].includes("✅")) {
      sheet.getRange(r, 3).setBackground(DAI_CONFIG.colors.activeBg).setFontColor(DAI_CONFIG.colors.activeText);
    } else if (row[2].includes("⏳")) {
      sheet.getRange(r, 3).setBackground(DAI_CONFIG.colors.pendingBg).setFontColor(DAI_CONFIG.colors.pendingText);
    }
  });
  
  sheet.setColumnWidth(1, 40);
  sheet.setColumnWidth(2, 320);
  sheet.setColumnWidth(3, 160);
  sheet.setColumnWidth(4, 180);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  TAB 5: FINANCIALS
// ══════════════════════════════════════════════════

function buildFinancials(ss) {
  let sheet = ss.getSheetByName("💰 Financials");
  if (!sheet) sheet = ss.insertSheet("💰 Financials");
  sheet.clear();
  sheet.setTabColor("#ff9800");
  
  sheet.getRange("A1:E1").merge().setValue("💰 FINANCIALS — BUDGET vs. ACTUALS")
    .setBackground(DAI_CONFIG.colors.headerBg).setFontColor(DAI_CONFIG.colors.headerText)
    .setFontSize(16).setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange("A2:E2").merge()
    .setValue("Source: CFO_PILOT_AGENT_BUDGET.md | " + new Date().toISOString())
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText)
    .setFontSize(9).setHorizontalAlignment("center");
  
  sheet.getRange("A4:E4").setValues([["Category", "Budgeted", "Actual", "Remaining", "Status"]])
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold");
  
  const budget = [
    ["UI/UX Contractor", "$500-1,000", "$0", "$500-1,000", "Not Started"],
    ["Cloud Infrastructure (90-day)", "$60", "$0", "$60", "Not Started"],
    ["Domain Registration", "$12-15", "$0", "$12-15", "Not Started"],
    ["n8n Cloud Pro (3 months)", "$60", "$20", "$40", "Month 1 active"],
    ["Claude API Usage", "$15-75", "$0", "$15-75", "Not Started"],
    ["JD Supra Placement", "$500-1,000", "$0", "$500-1,000", "Pending CMO"],
    ["LinkedIn Ads", "$300-500", "$0", "$300-500", "Pending CMO"],
    ["TOTAL", "$1,447-2,725", "$20", "$1,427-2,705", ""],
  ];
  
  budget.forEach((row, i) => {
    const r = 5 + i;
    sheet.getRange(r, 1, 1, 5).setValues([row]);
    sheet.getRange(r, 1).setFontWeight("bold");
    if (row[0] === "TOTAL") {
      sheet.getRange(r, 1, 1, 5).setFontWeight("bold").setFontSize(12)
        .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText);
    }
  });
  
  // Revenue Projections
  const revRow = 5 + budget.length + 2;
  sheet.getRange(revRow, 1, 1, 4).merge().setValue("📈 REVENUE PROJECTIONS (Post-Pilot)")
    .setBackground(DAI_CONFIG.colors.sectionHeader).setFontColor(DAI_CONFIG.colors.sectionText)
    .setFontWeight("bold").setHorizontalAlignment("center");
  
  sheet.getRange(revRow + 1, 1, 1, 4).setValues([["Scenario", "MRR", "ARR", "ROI"]])
    .setBackground(DAI_CONFIG.colors.accentBg).setFontColor(DAI_CONFIG.colors.accentText).setFontWeight("bold");
  
  const rev = [
    ["Conservative (5 firms, $49/seat)", "$1,225", "$14,700", "915%"],
    ["Target (15 firms, $69/seat)", "$5,175", "$62,100", "2,178%"],
    ["Optimistic (30 firms, $99/seat)", "$19,800", "$237,600", "8,617%"],
  ];
  
  rev.forEach((row, i) => {
    sheet.getRange(revRow + 2 + i, 1, 1, 4).setValues([row]);
    if (row[0].includes("Target")) {
      sheet.getRange(revRow + 2 + i, 1, 1, 4).setFontWeight("bold");
      sheet.getRange(revRow + 2 + i, 3).setFontColor(DAI_CONFIG.colors.activeText).setFontSize(14);
    }
  });
  
  sheet.setColumnWidth(1, 280);
  sheet.setColumnWidth(2, 140);
  sheet.setColumnWidth(3, 140);
  sheet.setColumnWidth(4, 140);
  sheet.setColumnWidth(5, 140);
  sheet.setFrozenRows(4);
}

// ══════════════════════════════════════════════════
//  UTILITIES
// ══════════════════════════════════════════════════

function refreshDelegateAI() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  buildPilotOverview(ss);
  buildBuildTracker(ss);
  buildBetaFirmTracker(ss);
  buildComplianceStatus(ss);
  buildFinancials(ss);
}

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu("🚀 Delegate AI")
    .addItem("Refresh All Tabs", "refreshDelegateAI")
    .addItem("Rebuild Dashboard", "setupDelegateAIDashboard")
    .addToUi();
}
