"""
Meta App Factory — Safe HTTP Utilities
========================================
Shared utilities for HTTP operations. All apps generated by the Factory
should import from here to avoid common pitfalls.

Key guard: HTTP headers MUST be ASCII-only (RFC 7230). Unicode characters
like emojis will cause `UnicodeEncodeError` on many HTTP clients.
This module provides helpers to sanitize headers while keeping message
bodies fully UTF-8.

Usage:
    from utils.safe_http import ascii_safe, safe_headers

    headers = safe_headers({
        "Title": "[AI] 🤖 Robot Alert - 3pm",
        "Priority": "3",
        "Actions": "http, ✅ Done, http://localhost/done",
    })
    # All header values are now ASCII-safe; emojis stripped from values.
"""


# ── V3.0 Resilience Integration ──────────────────────────
import os as _os, sys as _sys
_FACTORY_DIR = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), ".."))
_sys.path.insert(0, _FACTORY_DIR)
try:
    from factory import safe_post
    from local_state_manager import StateManager as _StateManager
    _v3_sm = _StateManager()
    _V3_AVAILABLE = True
except ImportError:
    _V3_AVAILABLE = False
# ── End V3 Integration ──────────────────────────────────

from auto_heal import healed_post, auto_heal, diagnose

def _v3_preflight():
    """V3: Ping Resonance_Watchdog_V3 before execution."""
    if not _V3_AVAILABLE:
        return True
    try:
        import json as _j
        _cfg_path = _os.path.join(_FACTORY_DIR, "resilience_config.json")
        if not _os.path.exists(_cfg_path):
            return True
        with open(_cfg_path) as _f:
            _cfg = _j.load(_f)
        _url = _cfg.get("cloud_health", {}).get("watchdog_url", "")
        if not _url:
            return True
        import requests as _rq
        _r = _rq.get(_url, timeout=5)
        return _r.status_code == 200
    except Exception:
        return False


def ascii_safe(text: str) -> str:
    """
    Strip non-ASCII characters from a string.
    Use for HTTP header values that must comply with RFC 7230.

    Args:
        text: Any string, may contain emoji or Unicode.

    Returns:
        ASCII-only string with non-ASCII chars removed.
    """
    return text.encode("ascii", "ignore").decode("ascii").strip()


def safe_headers(headers: dict[str, str]) -> dict[str, str]:
    """
    Sanitize all header values to ASCII-only.
    Keys are typically already ASCII (Content-Type, Title, etc.)
    but values may contain user-generated content with emojis.

    Args:
        headers: Dict of header name → value.

    Returns:
        New dict with all values made ASCII-safe.
    """
    return {k: ascii_safe(v) for k, v in headers.items()}


def utf8_body(text: str) -> bytes:
    """
    Encode message body as UTF-8 bytes.
    Unlike headers, HTTP bodies CAN contain full Unicode/emoji.

    Args:
        text: Message body text (emoji OK).

    Returns:
        UTF-8 encoded bytes.
    """
    return text.encode("utf-8")
# V3 AUTO-HEAL ACTIVE
