"""
Meta App Factory — Safe HTTP Utilities
========================================
Shared utilities for HTTP operations. All apps generated by the Factory
should import from here to avoid common pitfalls.

Key guard: HTTP headers MUST be ASCII-only (RFC 7230). Unicode characters
like emojis will cause `UnicodeEncodeError` on many HTTP clients.
This module provides helpers to sanitize headers while keeping message
bodies fully UTF-8.

Usage:
    from utils.safe_http import ascii_safe, safe_headers

    headers = safe_headers({
        "Title": "[AI] 🤖 Robot Alert - 3pm",
        "Priority": "3",
        "Actions": "http, ✅ Done, http://localhost/done",
    })
    # All header values are now ASCII-safe; emojis stripped from values.
"""


def ascii_safe(text: str) -> str:
    """
    Strip non-ASCII characters from a string.
    Use for HTTP header values that must comply with RFC 7230.

    Args:
        text: Any string, may contain emoji or Unicode.

    Returns:
        ASCII-only string with non-ASCII chars removed.
    """
    return text.encode("ascii", "ignore").decode("ascii").strip()


def safe_headers(headers: dict[str, str]) -> dict[str, str]:
    """
    Sanitize all header values to ASCII-only.
    Keys are typically already ASCII (Content-Type, Title, etc.)
    but values may contain user-generated content with emojis.

    Args:
        headers: Dict of header name → value.

    Returns:
        New dict with all values made ASCII-safe.
    """
    return {k: ascii_safe(v) for k, v in headers.items()}


def utf8_body(text: str) -> bytes:
    """
    Encode message body as UTF-8 bytes.
    Unlike headers, HTTP bodies CAN contain full Unicode/emoji.

    Args:
        text: Message body text (emoji OK).

    Returns:
        UTF-8 encoded bytes.
    """
    return text.encode("utf-8")
