import os
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from docx import Document
from openpyxl import Workbook
import json

class FileFactory:
    """
    Generates physical files (PDF, DOCX, XLSX, PPTX) from text or structured data.
    Designed to fulfill 'Download' requests.
    """
    def __init__(self, output_dir=None):
        # Default to a 'generated_files' dir in the skills folder if not specified
        if not output_dir:
            base_dir = os.path.dirname(os.path.abspath(__file__))
            self.output_dir = os.path.join(base_dir, "generated_files")
        else:
            self.output_dir = output_dir
            
        os.makedirs(self.output_dir, exist_ok=True)

    def create_file(self, content, file_type, file_name):
        """
        Generates a file.
        file_type: 'pdf', 'docx', 'xlsx', 'pptx', 'txt'
        content: String (for pdf/docx/txt) or List of Dicts (for xlsx) or JSON (for pptx)
        """
        try:
            file_path = os.path.join(self.output_dir, file_name)
            
            if file_type.lower() == 'pdf':
                self._create_pdf(content, file_path)
            elif file_type.lower() == 'docx':
                self._create_docx(content, file_path)
            elif file_type.lower() == 'xlsx':
                self._create_xlsx(content, file_path)
            elif file_type.lower() == 'pptx':
                self._create_presentation(content, file_path)
            else:
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(str(content))
                    
            return file_path
        except Exception as e:
            return f"File Generation Error: {str(e)}"

    def generate_image(self, prompt, file_name="image.png"):
        """
        Generates an image using DALL-E 3 and saves it locally.
        """
        try:
            from openai import OpenAI
            import requests
            
            client = OpenAI() # Uses OPENAI_API_KEY from env
            
            response = client.images.generate(
                model="dall-e-3",
                prompt=prompt,
                size="1024x1024",
                quality="standard",
                n=1,
            )
            
            image_url = response.data[0].url
            file_path = os.path.join(self.output_dir, file_name)
            
            img_data = requests.get(image_url).content
            with open(file_path, 'wb') as handler:
                handler.write(img_data)
                
            return file_path
        except Exception as e:
            return f"Image Generation Error: {str(e)}"

    def _create_presentation(self, content, path):
        """
        Content expected to be JSON:
        {
            "title": "Presentation Title",
            "slides": [
                {"title": "Slide 1", "content": "Bullet 1\\nBullet 2", "image_path": "optional/path/to/img.png"},
                ...
            ]
        }
        """
        from pptx import Presentation
        from pptx.util import Inches
        import json
        
        prs = Presentation()
        
        try:
             data = json.loads(content)
        except:
             data = {"title": "Error Parsing JSON", "slides": []}

        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = data.get("title", "Presentation")
        subtitle.text = "Generated by Adv_Autonomous_Agent"
        
        # Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        
        for slide_data in data.get("slides", []):
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            title_shape.text = slide_data.get("title", "Slide")
            tf = body_shape.text_frame
            tf.text = slide_data.get("content", "")
            
            # Image Injection
            img_path = slide_data.get("image_path")
            if img_path and os.path.exists(img_path):
                # Add image on the right side
                left = Inches(5.5)
                top = Inches(2)
                width = Inches(4)
                slide.shapes.add_picture(img_path, left, top, width=width)

        prs.save(path)

    def _create_pdf(self, content, path):
        c = canvas.Canvas(path, pagesize=letter)
        width, height = letter
        text_object = c.beginText(40, height - 40)
        text_object.setFont("Helvetica", 10)
        
        # Simple text wrapping
        max_width = 80
        lines = content.split('\n')
        
        for line in lines:
            # Check for page break
            if text_object.getY() < 40:
                c.drawText(text_object)
                c.showPage()
                text_object = c.beginText(40, height - 40)
                text_object.setFont("Helvetica", 10)
            text_object.textLine(line)
            
        c.drawText(text_object)
        c.save()

    def _create_docx(self, content, path):
        doc = Document()
        for line in content.split('\n'):
            doc.add_paragraph(line)
        doc.save(path)

    def _create_xlsx(self, content, path):
        # Expecting content to be a JSON string representation of a list of dicts, or a raw list of dicts
        import json
        data = []
        if isinstance(content, str):
            try: data = json.loads(content)
            except: data = [{"Error": "Could not parse JSON content for Excel"}]
        elif isinstance(content, list):
            data = content
            
        if not data:
             data = [{"Status": "No Data Provided"}]

        df = pd.DataFrame(data)
        df.to_excel(path, index=False)

if __name__ == "__main__":
    ff = FileFactory()
    # Test PPTX
    slides = """
    {
        "title": "Project Macaron",
        "slides": [
            {"title": "Market Analysis", "content": "- Growing demand\\n- Luxury niche"},
            {"title": "Financials", "content": "- High ROI\\n- Low Overhead"}
        ]
    }
    """
    print(ff.create_file(slides, "pptx", "test.pptx"))
