"""
__APP_NAME__ — FastAPI Backend Server
Generated by Meta App Factory V3
Portable: Works across PC1/PC2 via Google Drive sync.
"""

# ── V3.0 Resilience Integration ──────────────────────────
import os as _os, sys as _sys
_FACTORY_DIR = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), ".."))
_sys.path.insert(0, _FACTORY_DIR)
try:
    from factory import safe_post
    from local_state_manager import StateManager as _StateManager
    _v3_sm = _StateManager()
    _V3_AVAILABLE = True
except ImportError:
    _V3_AVAILABLE = False
# ── End V3 Integration ──────────────────────────────────

from auto_heal import healed_post, auto_heal, diagnose

def _v3_preflight():
    """V3: Ping Resonance_Watchdog_V3 before execution."""
    if not _V3_AVAILABLE:
        return True
    try:
        import json as _j
        _cfg_path = _os.path.join(_FACTORY_DIR, "resilience_config.json")
        if not _os.path.exists(_cfg_path):
            return True
        with open(_cfg_path) as _f:
            _cfg = _j.load(_f)
        _url = _cfg.get("cloud_health", {}).get("watchdog_url", "")
        if not _url:
            return True
        import requests as _rq
        _r = _rq.get(_url, timeout=5)
        return _r.status_code == 200
    except Exception:
        return False


import os, sys, json, logging
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel

# ── Portability: Load .env for cross-PC environment ──────
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# ── Portability: Runtime Data Isolation ──────────────────
# Machine-specific data (logs, state) goes to AppData/Local
# so Google Drive sync doesn't cause conflicts between PCs.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
APP_NAME = "__APP_NAME__"
RUNTIME_DIR = os.environ.get(
    APP_NAME.upper() + "_RUNTIME_DIR",
    os.path.join(os.environ.get("LOCALAPPDATA", SCRIPT_DIR), APP_NAME, "runtime")
)
os.makedirs(RUNTIME_DIR, exist_ok=True)

# ── Portability: Read port from config.json ──────────────
DEFAULT_PORT = __PORT__
try:
    with open(os.path.join(SCRIPT_DIR, "config.json"), "r") as _f:
        DEFAULT_PORT = json.load(_f).get("port", DEFAULT_PORT)
except Exception:
    pass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [__APP_NAME__] %(message)s")
logger = logging.getLogger("__APP_NAME__")
logger.info(f"Runtime dir: {RUNTIME_DIR}")

app = FastAPI(title="__APP_NAME__ API", version="3.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Import V3 Streaming Engine ───────────────────────────
try:
    from app_stream import stream_chat, clear_stream_history
    STREAMING = True
    logger.info("V3 Streaming Engine loaded.")
except ImportError:
    STREAMING = False
    logger.warning("Streaming engine not available.")

class ChatRequest(BaseModel):
    prompt: str
    dashboard_context: dict | None = None

@app.get("/")
def root():
    return {"service": "__APP_NAME__", "version": "3.0", "streaming": STREAMING, "port": DEFAULT_PORT}

@app.post("/api/chat/stream")
async def chat_stream(req: ChatRequest):
    if not STREAMING:
        return JSONResponse({"error": "Streaming not available."}, status_code=503)
    if not req.prompt.strip():
        return JSONResponse({"error": "No prompt."}, status_code=400)
    def generate():
        for event in stream_chat(req.prompt, dashboard_context=req.dashboard_context):
            yield f"data: {json.dumps(event)}\n\n"
    return StreamingResponse(generate(), media_type="text/event-stream")

@app.post("/api/chat/clear")
def clear_chat():
    if STREAMING: clear_stream_history()
    return {"status": "ok"}

@app.get("/api/health")
def health():
    return {"status": "healthy", "streaming": STREAMING, "runtime_dir": RUNTIME_DIR}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=DEFAULT_PORT)
# V3 AUTO-HEAL ACTIVE
