"""
app_stream.py — Multi-Agent V3 Streaming Engine
Generated by Meta App Factory Prompt Architect
═════════════════════════════════════════════════
Dynamic persona routing based on build_plan.json.
"""

# ── V3.0 Resilience Integration ──────────────────────────
import os as _os, sys as _sys
_FACTORY_DIR = _os.path.normpath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), ".."))
_sys.path.insert(0, _FACTORY_DIR)
try:
    from factory import safe_post
    from local_state_manager import StateManager as _StateManager
    _v3_sm = _StateManager()
    _V3_AVAILABLE = True
except ImportError:
    _V3_AVAILABLE = False
# ── End V3 Integration ──────────────────────────────────

from auto_heal import healed_post, auto_heal, diagnose

def _v3_preflight():
    """V3: Ping Resonance_Watchdog_V3 before execution."""
    if not _V3_AVAILABLE:
        return True
    try:
        import json as _j
        _cfg_path = _os.path.join(_FACTORY_DIR, "resilience_config.json")
        if not _os.path.exists(_cfg_path):
            return True
        with open(_cfg_path) as _f:
            _cfg = _j.load(_f)
        _url = _cfg.get("cloud_health", {}).get("watchdog_url", "")
        if not _url:
            return True
        import requests as _rq
        _r = _rq.get(_url, timeout=5)
        return _r.status_code == 200
    except Exception:
        return False


import os
import sys
import json
import logging
import requests

logger = logging.getLogger("AppStream")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ── Load Build Plan ──────────────────────────────────────────
BUILD_PLAN = {}
try:
    with open(os.path.join(SCRIPT_DIR, "build_plan.json"), "r") as f:
        BUILD_PLAN = json.load(f)
except Exception as e:
    logger.warning(f"No build_plan.json found: {e}")

# ── Environment & Keys ───────────────────────────────────────
if "pythoncore-3.14-64" in sys.executable:
    sys.path.insert(0, os.path.join(SCRIPT_DIR, "..", "Alpha_V2_Genesis"))
    sys.path.insert(0, os.path.join(SCRIPT_DIR, "..", "..", ".system_core"))

try:
    from vault_client import get_secret
except ImportError:
    def get_secret(key, default="", **kw):
        return os.getenv(key, default)

# Setup basic local memory
_HISTORY_DIR = os.environ.get("Resonance4_RUNTIME_DIR", os.path.join(SCRIPT_DIR, "runtime"))
if not os.path.exists(_HISTORY_DIR):
    _HISTORY_DIR = os.path.join(SCRIPT_DIR, ".Gemini_state")
os.makedirs(_HISTORY_DIR, exist_ok=True)
_STREAM_HISTORY = os.path.join(_HISTORY_DIR, ".chat_history.json")

def _load_history(max_turns=10):
    try:
        if os.path.exists(_STREAM_HISTORY):
            with open(_STREAM_HISTORY, "r") as f:
                history = json.load(f)
            return history[-(max_turns * 2):]
    except Exception:
        pass
    return []

def _save_history(history, max_turns=10):
    try:
        with open(_STREAM_HISTORY, "w") as f:
            json.dump(history[-(max_turns * 2):], f, indent=2)
    except Exception as e:
        logger.warning(f"Failed to save history: {e}")

def clear_stream_history():
    _save_history([])

# ── Agent System Prompts ─────────────────────────────────────
# We generate the base system prompt dynamically from the build plan
def _build_system_prompt():
    agents = BUILD_PLAN.get("agents", [])
    features = BUILD_PLAN.get("features", [])
    
    prompt = "You are the primary orchestration agent for this application.\n\n"
    if agents:
        prompt += "AVAILABLE PERSONAS/AGENTS IN THIS APP:\n"
        for idx, agent in enumerate(agents):
            prompt += f"{idx+1}. {agent.get('name', 'Unknown')} ({agent.get('provider', 'gemini')}): {agent.get('role', '')}\n"
            if agent.get("system_prompt"):
                prompt += f"   System Prompt: {agent.get('system_prompt')}\n"
        prompt += "\n"
        
    if features:
        prompt += f"CORE FEATURES TO SUPPORT:\n- " + "\n- ".join(features) + "\n\n"
        
    prompt += "Provide helpful, direct responses. If a specific agent's persona is requested, adopt that persona."
    return prompt

# ── Streaming Client ─────────────────────────────────────────
def stream_chat(prompt, project_name="App", dashboard_context=None, agent_override=None):
    """Generator: yields SSE text chunks from Gemini."""
    api_key = get_secret("GEMINI_API_KEY")
    if not api_key:
        yield {"error": "GEMINI_API_KEY not found."}
        return

    history = _load_history()
    history.append({"role": "user", "content": prompt})

    sys_prompt = _build_system_prompt()
    if dashboard_context:
        sys_prompt += f"\n\nLIVE CONTEXT:\n{json.dumps(dashboard_context, indent=2)}"

    contents = [
        {"role": "user", "parts": [{"text": sys_prompt + "\n\nConversation starts now."}]},
        {"role": "model", "parts": [{"text": "Understood. I'm ready."}]},
    ]
    for msg in history:
        role = "user" if msg["role"] == "user" else "model"
        contents.append({"role": role, "parts": [{"text": msg["content"]}]})

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse&key={api_key}"
    payload = {
        "contents": contents,
        "generationConfig": {"temperature": 0.7, "maxOutputTokens": 4096},
    }

    full_response = []
    try:
        with requests.post(url, json=payload, stream=True, timeout=120) as resp:
            if resp.status_code != 200:
                yield {"error": f"API error ({resp.status_code})."}
                return

            for line in resp.iter_lines(decode_unicode=True):
                if not line or not line.startswith("data: "): continue
                try:
                    chunk = json.loads(line[6:])
                except json.JSONDecodeError:
                    continue
                candidates = chunk.get("candidates", [])
                if not candidates: continue
                parts = candidates[0].get("content", {}).get("parts", [])
                for part in parts:
                    text = part.get("text", "")
                    if text:
                        full_response.append(text)
                        yield {"text": text}

        complete_text = "".join(full_response)
        if complete_text:
            history.append({"role": "assistant", "content": complete_text})
            _save_history(history)
        yield {"done": True}

    except Exception as e:
        yield {"error": f"Streaming failed: {str(e)}"}

# V3 MIGRATION COMPLETE
# V3 AUTO-HEAL ACTIVE
