# Auto-generated by app_generator.py on 2026-04-30 11:58
"""
personnel_archiver — V3.0 Hardened Agent
═════════════════════════════════════════════════════════════════════
This is the standard boilerplate for every Antigravity child agent.
It inherits 100% of the Hardened V3.0 architecture:

  • Antigravity_Full_v2 API key — inherited automatically via
    the factory's .env access. Child apps NEVER handle raw keys.

  • StateManager — every outgoing call is logged with a UUID +
    timestamp in local_pending_sync.json BEFORE the HTTP POST.

  • Safe-Buffer mode — if n8n Cloud is unreachable, payloads
    are queued to pending_sync/ and the Recovery Sync Engine
    (recovery_sync.py) delivers them when connectivity returns.

  • Watchdog preflight — cloud health is validated before any
    data-heavy operation via the Resonance_Watchdog_V3 ping
    (ID: Ap8cp7Q5jkcmCKmd).

Usage:
    1. Copy this file and rename to your agent's name.
    2. Implement your logic in the execute() function.
    3. Run:  python my_agent.py

Author: Antigravity Ops Intelligence
Framework: V3.0 Resilience Inheritance
"""

import os
import sys
import json

# ── Resolve paths relative to Meta_App_Factory ──────────────
# This ensures all child apps, regardless of where they're run,
# can find factory.py, local_state_manager.py, and .env.
FACTORY_DIR = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sys.path.insert(0, FACTORY_DIR)

# ── Import the V3.0 Hardened Factory ────────────────────────
# The factory module auto-loads the .env file, giving this app
# access to Antigravity_Full_v2 (N8N_API_KEY), GEMINI_API_KEY,
# and all other credentials without ever exposing raw keys.
from factory import safe_post                       # V3 Safe-Post pattern
from local_state_manager import StateManager        # UUID + state tracking

# ── Initialize State ────────────────────────────────────────
sm = StateManager()


# ═══════════════════════════════════════════════════════════
#  PREFLIGHT CHECK — Call before any data-heavy operation
# ═══════════════════════════════════════════════════════════

def preflight() -> bool:
    """
    Validate cloud health by pinging the Resonance_Watchdog_V3
    (ID: Ap8cp7Q5jkcmCKmd) before any heavy work.

    Returns True if healthy, False if unreachable.
    """
    import requests

    # Load watchdog URL from resilience config
    cfg_path = os.path.join(FACTORY_DIR, "resilience_config.json")
    if not os.path.exists(cfg_path):
        print("⚠️ resilience_config.json not found — skipping preflight")
        return True

    with open(cfg_path) as f:
        cfg = json.load(f)

    url = cfg.get("cloud_health", {}).get("watchdog_url", "")
    if not url:
        return True

    try:
        r = requests.get(url, timeout=5)
        latency = r.elapsed.total_seconds() * 1000
        healthy = r.status_code == 200
        icon = "🟢" if healthy else "🔴"
        print(f"  Preflight: {icon} Watchdog {r.status_code} ({latency:.0f}ms)")
        return healthy
    except Exception as e:
        print(f"  Preflight: 🔴 Watchdog UNREACHABLE ({e})")
        return False


# ═══════════════════════════════════════════════════════════
#  EXECUTE — Your agent logic goes here
# ═══════════════════════════════════════════════════════════

def execute():
    """
    Personnel Archiver Logic.
    Extracts files one by one, creates a folder for each based on the filename,
    and moves them to the target directory.
    """
    import shutil

    source_dir = r"C:\Users\mpetr\OneDrive - Gelato Petrini\Desktop\Personell_Temporary"
    dest_base_dir = r"C:\Remote Files\EMPLOYEE_PERSONEL\Employees HF Delray Beach\TERMINATED\Terminated 2026"

    # ── Step 1: Preflight ────────────────────────────────
    if not preflight():
        print("  ⚠️ Cloud is unhealthy — but local file ops will proceed.")

    # ── Step 2: Ensure Base Directory ────────────────────
    if not os.path.exists(dest_base_dir):
        print(f"  📁 Creating base destination: {dest_base_dir}")
        os.makedirs(dest_base_dir, exist_ok=True)

    if not os.path.exists(source_dir):
        print(f"  ❌ Source directory not found: {source_dir}")
        return

    # ── Step 3: Iterate and Move ─────────────────────────
    files = [f for f in os.listdir(source_dir) if os.path.isfile(os.path.join(source_dir, f))]
    
    if not files:
        print("  ℹ️ No files found in source directory.")
        return

    print(f"  📦 Found {len(files)} files to process.")

    for file_name in files:
        source_path = os.path.join(source_dir, file_name)
        
        # Get filename without extension
        name_without_ext = os.path.splitext(file_name)[0]
        
        # Create specific destination folder
        dest_folder = os.path.join(dest_base_dir, name_without_ext)
        os.makedirs(dest_folder, exist_ok=True)
        
        # Move the file
        dest_path = os.path.join(dest_folder, file_name)
        try:
            shutil.move(source_path, dest_path)
            print(f"  ✅ Moved: {file_name} -> {dest_folder}")
        except Exception as e:
            print(f"  ❌ Failed to move {file_name}: {e}")

    print("\n  🎉 All files processed successfully.")


# ═══════════════════════════════════════════════════════════
#  ENTRY POINT
# ═══════════════════════════════════════════════════════════

if __name__ == "__main__":
    print(f"\n{'='*60}")
    print(f"  🚀 personnel_archiver — V3.0 Hardened Agent")
    print(f"{'='*60}\n")

    execute()

    print(f"\n{'='*60}\n")
