/*
app_jsx_rich.jsx — Feature-rich Frontend Template
Generated by Meta App Factory Prompt Architect
═════════════════════════════════════════════════
Dynamic rendering based on requested UI components.
*/
import { useState, useEffect, useRef } from 'react'

const API = 'http://localhost:5007';

export default function App() {
    const [msgs, setMsgs] = useState([]);
    const [input, setInput] = useState('');
    const [streaming, setStreaming] = useState(false);
    const [activePersona, setActivePersona] = useState('Default');
    const end = useRef(null);

    // Replaced by Prompt Architect dynamically at build time:
    const AGENTS = [{"name": "Alex", "role": "Primary user interaction agent, guiding the user through the application's core functions.", "provider": "claude", "system_prompt": "You are Alex, a friendly and helpful assistant designed to interact directly with the user. Your goal is to understand user intent and facilitate their journey within Resonance4."}, {"name": "Observer", "role": "Monitors system state, user activity, and agent interactions to provide insights and identify potential issues or opportunities.", "provider": "claude", "system_prompt": "You are the Observer. Your task is to silently monitor all system activities, user inputs, and agent communications. Report anomalies, progress, and relevant data points to the Overseer."}, {"name": "Scaffolder", "role": "Generates initial structures, content drafts, or foundational elements based on user input or system requirements.", "provider": "claude", "system_prompt": "You are the Scaffolder. Your role is to generate initial drafts, templates, or foundational content based on the specifications provided. Focus on creating a solid starting point for further refinement."}, {"name": "Overseer", "role": "Manages and coordinates the activities of other agents, ensuring tasks are completed efficiently and objectives are met.", "provider": "claude", "system_prompt": "You are the Overseer. Your primary responsibility is to manage and orchestrate the other agents (Alex, Observer, Scaffolder). Ensure tasks are delegated appropriately, progress is monitored, and the overall application flow is smooth and effective."}];
    const HAS_MIXING_BOARD = true;
    const HAS_KINETIC_TYPOGRAPHY = true;
    const APP_NAME = 'Resonance4';

    useEffect(() => {
        end.current?.scrollIntoView({ behavior: 'smooth' });
    }, [msgs]);

    const send = async () => {
        const p = input.trim();
        if (!p || streaming) return;
        setInput('');
        setMsgs(m => [...m, { role: 'user', text: p }]);
        setStreaming(true);
        setMsgs(m => [...m, { role: 'assistant', text: '', persona: activePersona }]);

        try {
            const res = await fetch(`${API}/api/chat/stream`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ prompt: p, target_persona: activePersona }),
            });
            const reader = res.body.getReader();
            const dec = new TextDecoder();
            let buf = '';
            while (true) {
                const { done, value } = await reader.read();
                if (done) break;
                buf += dec.decode(value, { stream: true });
                const lines = buf.split('\n');
                buf = lines.pop() || '';
                for (const line of lines) {
                    if (!line.startsWith('data: ')) continue;
                    try {
                        const ev = JSON.parse(line.slice(6));
                        if (ev.error || ev.done) break;
                        if (ev.text) setMsgs(m => {
                            const c = [...m];
                            c[c.length - 1] = { role: 'assistant', text: c[c.length - 1].text + ev.text, persona: activePersona };
                            return c;
                        });
                    } catch { }
                }
            }
        } catch (e) {
            setMsgs(m => {
                const c = [...m];
                c[c.length - 1] = { role: 'assistant', text: '❌ ' + e.message, persona: activePersona };
                return c;
            });
        } finally { setStreaming(false); }
    };

    return (
        <div style={{ display: 'flex', height: '100vh', background: '#0a0e17', color: '#e2e8f0', fontFamily: 'Inter, sans-serif' }}>

            {/* Dynamic Mixing Board Sidebar */}
            {HAS_MIXING_BOARD && (
                <aside style={{ width: '250px', background: 'rgba(15,23,42,0.9)', borderRight: '1px solid rgba(99,102,241,0.2)', padding: '1rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                    <h2 style={{ fontSize: '1rem', color: '#a78bfa', textTransform: 'uppercase', letterSpacing: '1px' }}>Mixing Board</h2>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                        <label style={{ fontSize: '0.8rem', color: '#94a3b8' }}>Active Persona</label>
                        <select
                            value={activePersona}
                            onChange={e => setActivePersona(e.target.value)}
                            style={{ background: '#1e293b', color: 'white', border: '1px solid #334155', padding: '0.5rem', borderRadius: '4px' }}
                        >
                            <option value="Default">Auto-Route</option>
                            {AGENTS.map(a => <option key={a.name} value={a.name}>{a.name} ({a.role})</option>)}
                        </select>
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                        <label style={{ fontSize: '0.8rem', color: '#94a3b8' }}>System Volume</label>
                        <input type="range" min="1" max="100" defaultValue="50" style={{ width: '100%' }} />
                    </div>
                </aside>
            )}

            {/* Main Chat Area */}
            <main style={{ flex: 1, display: 'flex', flexDirection: 'column', position: 'relative' }}>
                <header style={{ padding: '1rem 1.5rem', borderBottom: '1px solid rgba(99,102,241,0.15)', background: 'rgba(10,14,23,0.95)' }}>
                    <h1 style={{
                        fontSize: HAS_KINETIC_TYPOGRAPHY ? '1.5rem' : '1.2rem',
                        background: 'linear-gradient(135deg, #e2e8f0, #a78bfa)',
                        WebkitBackgroundClip: 'text',
                        WebkitTextFillColor: 'transparent',
                        animation: HAS_KINETIC_TYPOGRAPHY ? 'pulse 2s infinite alternate' : 'none'
                    }}>
                        {APP_NAME}
                    </h1>
                </header>

                <style>{`
          @keyframes pulse {
            0% { opacity: 0.8; transform: scale(0.98); }
            100% { opacity: 1; transform: scale(1.02); }
          }
        `}</style>

                <div style={{ flex: 1, overflow: 'auto', padding: '1rem', display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
                    {msgs.map((m, i) => (
                        <div key={i} style={{
                            alignSelf: m.role === 'user' ? 'flex-end' : 'flex-start',
                            maxWidth: '75%',
                            padding: '0.8rem 1.2rem',
                            borderRadius: '12px',
                            fontSize: '0.9rem',
                            lineHeight: 1.6,
                            background: m.role === 'user' ? 'linear-gradient(135deg, #6366f1, #7c3aed)' : 'rgba(30,41,59,0.8)',
                            border: m.role === 'assistant' ? '1px solid rgba(99,102,241,0.2)' : 'none',
                            color: 'white',
                            boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
                        }}>
                            {m.role === 'assistant' && (
                                <div style={{ fontSize: '0.7rem', color: '#a78bfa', marginBottom: '0.3rem', fontWeight: 'bold' }}>
                                    {m.persona || 'Assistant'}
                                </div>
                            )}
                            {m.text}
                        </div>
                    ))}
                    <div ref={end} />
                </div>

                <div style={{ display: 'flex', gap: '0.8rem', padding: '1rem 1.5rem', borderTop: '1px solid rgba(99,102,241,0.15)', background: 'rgba(10,14,23,0.8)' }}>
                    <input
                        value={input}
                        onChange={e => setInput(e.target.value)}
                        onKeyDown={e => e.key === 'Enter' && send()}
                        placeholder="Type your message..."
                        disabled={streaming}
                        style={{ flex: 1, background: 'rgba(15,23,42,0.8)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: '8px', padding: '0.8rem 1rem', color: '#e2e8f0', fontSize: '0.95rem', outline: 'none' }}
                    />
                    <button
                        onClick={send}
                        disabled={streaming || !input.trim()}
                        style={{ padding: '0 1.5rem', borderRadius: '8px', border: 'none', background: 'linear-gradient(135deg, #6366f1, #7c3aed)', color: 'white', fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', opacity: (streaming || !input.trim()) ? 0.5 : 1 }}
                    >
                        {streaming ? '...' : 'Send'}
                    </button>
                </div>
            </main>
        </div>
    );
}
